### ISSUE TITLE
/av user not showing data

### ISSUE THREAD

**Issue by SiuanSong** [Ben12345rocks/VotingPlugin#1192]
**Versions**
VotingPlugin 6.6.3
Purpur 1.17.1 #1387

**Describe the bug**
When using /av user, the data is not being shown.

**Screenshots/Configs**
![Image](https://i.imgur.com/dydyCcA.png)
![Image](https://i.imgur.com/ztgqbX7.png)

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/ better?

**Comment by SiuanSong** [comment]
Did not seem to make a difference  :(

**Comment by BenCodez** [comment]
Now?
https://bencodez.com/job/VotingPlugin/

**Comment by andrewkm** [comment]
I am unable to reproduce this.
Works as intended here via 1.17.1, voting plugin build 256.

![image](https://i.imgur.com/DZB8glo.png)

**Comment by BenCodez** [comment]
> I am unable to reproduce this.
> Works as intended here via 1.17.1, voting plugin build 256.
> 
> ![image](https://camo.githubusercontent.com/a6143ffdc2fc1774755f7c3c067eb4448f82afbe042c371bb75faa3457577ea3/68747470733a2f2f692e696d6775722e636f6d2f445a4238676c6f2e706e67)

Using MySQL?

**Comment by andrewkm** [comment]
Yes.

**Comment by BenCodez** [comment]
> Yes.

That will effect it

**Comment by andrewkm** [comment]
> > Yes.
> 
> 
> 
> That will effect it

I'm just replying that it's not an issue for me. :)
