### ISSUE TITLE
Everytime I vote it does a first time vote

### ISSUE THREAD

**Issue by RestrictionVR** [Ben12345rocks/VotingPlugin#1193]
I don't know if it's just because I'm doing it from a vote testing site so I just thought this could be a issue or not?

![image](https://user-images.githubusercontent.com/14044689/134778610-19b942f8-a952-4547-b200-3a232a1708c8.png)
![image](https://user-images.githubusercontent.com/14044689/134778613-b44f4cb1-ddbf-46b2-9778-af4c7b90196c.png)

**Comment by BenCodez** [comment]
You fix it?
