### ISSUE TITLE
Monthly Rewards appered on the 26th, second place didnt work & 4-10 posted once?

### ISSUE THREAD

**Issue by TomLewis** [Ben12345rocks/VotingPlugin#1194]
**Versions**
paper 1.12.2 using 6.6.3
Using MySQL storage (Converted from Flatfile)

**Relevant information & Context**

1. Monthly rewards are set to 1, 2 & 3 for top 3 voters and then 4-10 for runner ups, only 1 & 3 fired and only 1 of the 4-10 worked. Im surprised the second place person didnt have a message sent as its a copy/paste of the first one with variables changed!!
2. Even though its set for winners each month, it fired yesterday on the 26th, that's not the end of the month?
3. Your docs say I can bundle a group of monthly winners together by using `'4-10':` But when I had a Discord message send, it only sent one discord message (Since removed from the config ive attached)

Notes:

- `/av CurrentPluginTime` shows the correct date/time.

SpecialRewards.yml 
https://gist.github.com/TomLewis/f6a85d9b083c5e2835db6fa713198b5f

what is going on?

Screenshot, you can see that only the 1st 3rd and then 1 runner up was posted to discord, I have since removed the runner up discord message from the config. Why wasnt 2 posted?
![Screenshot 2021-09-27 at 11 14 11](https://user-images.githubusercontent.com/144046/134900242-43f140dd-fec4-4ecb-9808-4dc98fa5dca6.png)

Edit: 
I just found this in ServerData.yml, so I guess I change that 27 to 1? Then its the 1st each month? 
Also how does the "PrevWeek" work? is it the week number each year?
```
Month: SEPTEMBER
PrevWeek: 40
PrevDay: 27
```

**Comment by BenCodez** [comment]
Should only be concerned with what Month says, if that changes, it triggers a month change

As for why it reset, I got no idea. 

I'll do some testing locally on the rewards and such

**Comment by TomLewis** [comment]
I figured it out, I'm so stupid, I through it sends them all at once, it waits until they log in! This explains why they were coming in drips and drabs! 

I think its that simple for all the answers, I just assumed it was all sent at once! Commands are run when they log in! I changed my time to the 1st, so I will wait and see if it changes then!

1. Does the MySQL store the "pending" rewards to each users data so it persists over server reboot?

**Comment by BenCodez** [comment]
You can add ForceOffline to the rewards to make it run right away

Rewards persist over restarts.

**Comment by TomLewis** [comment]
oh smashing, can I run forceoffline just for that one command? because I send them an item too, aswell as a discord message to announce the winners, unless there's a way I can run 1 command to include all the top 10 winners and list their positions?

That might be neater method anyway, as long as I can use new lines to space it all out nice and neat using placeholders.

```
      - 'discord broadcast #648511913206087680 `/vote` :third_place: **%player%** came third place
        in the most votes %TopVoter% and won a Bronze Doubloon (%date%)'
```

I also coould only find these placeholders to use insize prizes
```
%player% = Player name
%money% = Money player got (With random number support)
%exp% = Exp player got (With random number support)
%date% = Date of execution
%currentdate% = Current date
Also javascript support for text/messages (wiki page on the side)
```
on https://github.com/BenCodez/VotingPlugin/wiki/Rewards
But I wanted to have the placeholder to show the number that they got in the top votes, so like number 1 or number 2

**Comment by BenCodez** [comment]
TopVoter placeholders, will update specialrewards.yml to include these:
%place% - place in topvoter
%topvoter% - topvoter type
%votes% - current total votes related to top voter

as for having one command run offline and the rest when online this could work:

    Rewards:
      Commands:
      - command offline
      ForceOffline: true
      Rewards:
        Commands:
        - online command

**Comment by TomLewis** [comment]
> TopVoter placeholders, will update specialrewards.yml to include these:
> %place% - place in topvoter
> %topvoter% - topvoter type
> %votes% - current total votes related to top voter
> 
> as for having one command run offline and the rest when online this could work:
> 
> ```
> Rewards:
>   Commands:
>   - command offline
>   ForceOffline: true
>   Rewards:
>     Commands:
>     - online command
> ```

Thanks for the placeholders! 

Can you give me an example using the SpecialRewards.yml that I attached, as im confused as to how I would get both an item to run when they are online and command to run for all contestants offline.

Being able to run one command offline that could write out the top voters that month like this:
```
 - 'discord broadcast #648511913206087680 
        1st - Username
        2nd - Username
        .
        .
        .
        10th - Username
```

**Comment by BenCodez** [comment]
Like this:

    MonthlyAwards:
      # Position. 1 is first in top voter, 2 is second, etc...
      # Using 1-10 will reward players in first to tenth place with the same reward
      '1':
        Rewards:
          ForceOffline: true
          Commands:
          - 'discord broadcast #648511913206087680 :tada: **%player%** won first place
            in the most votes this month! (%date%)'
          Rewards:
            Messages:
              Player: '&8[&3VOTE&8] &aYou came in first place in %TopVoter%!'
              Broadcast: '&8[&3VOTE COMPETITION&8]&e %player% won first place in the most
                votes this month!'
            Sound:
              Enabled: true
              Sound: BLOCK_ANVIL_USE
              Volume: 1.0
              Pitch: 1.0
            Title:
              Enabled: true
              Title: '&cYou WON top Voter this month!'
              SubTitle: Congratulations, you win the top voter prizes!
              FadeIn: 10
              ShowTime: 100
              FadeOut: 10
            Effect:
              Enabled: true
              Effect: REDSTONE
              Data: 300
              Particles: 100
              Radius: 5
            Items:
              FirstPlace:
                Material: 'GOLD_NUGGET'
                Data: 0
                Amount: 1
                Name: '&31st Place Gold Doubloon'
                Lore: 
                - '&3Pick a prize at /warp cove'
                - '&3Find the Vote Trader!'
                - ' '
                - '&8⚑&o Top Monthly Voter'
                - ' '
                - '&f&lRARITY'
                - '&e▌ ✪✪✪'
                - ' '
                - '&f&lHOW TO OBTAIN'
                - '&6▌ Be a top monthly voter! &f/vote'

**Comment by TomLewis** [comment]
Rewards inside a Rewards! its Rewards-ception! thanks, I will give this a try!

**Comment by TomLewis** [comment]
Sorry for the initial discord broadcast that runs once, how do I get each player placeholder? %player_1% %player_2% %player_3% etc?

**Comment by BenCodez** [comment]
just %player% should do it?

**Comment by TomLewis** [comment]
Oh its still posting a message per player, so it will be 10 separate discord messages!
Sorry, Im trying to post just 1 Discord message with all winners in it, so its tidy.

**Comment by BenCodez** [comment]
Then you could use placeholderapi placeholders for that, /av placeholders will list them all
