### ISSUE TITLE
Vote ranks

### ISSUE THREAD

**Issue by Olivires** [Ben12345rocks/VotingPlugin#1196]
**Versions**
Latest released by 16 October 2021

**Relevant information**
I edited SpecialRewards.yml to the following

Cumulative:
  # Number of votes required
  # Allows multiple cumulative rewards
  # Number be be around ' (E.g. '1')
  # Can have multiple listed here
  '20':
    # Wether or not votes must be made in same day/week
    # Useful if you want to require a certain number of voting sites to be voted on
    # for a daily/weekly reward instead of all of them
    # Valid options
    # AllTime
    # Monthly
    # Weekly
    # Daily
    Enabled: true
    TotalToUse: AllTime
    Rewards: 
      Commands:
        Console:
        - lp user %player% parent set strawberry
      Messages:
        Player: '&aYou ranked up!'
  '40':
    Enabled: true
    TotalToUse: AllTime
    Rewards: 
      Commands:
        Console:
        - lp user %player% parent set grape
      Messages:
        Player: '&aYou ranked up!'
  '80':
    Enabled: true
    TotalToUse: AllTime
    Rewards: 
      Commands:
        Console:
        - lp user %player% parent set apple
      Messages:
        Player: '&aYou ranked up!'
   '160':
    Enabled: true
    TotalToUse: AllTime
    Rewards: 
      Commands:
        Console:
        - lp user %player% parent set banana
      Messages:
        Player: '&aYou ranked up!'
   '320':
    Enabled: true
    TotalToUse: AllTime
    Rewards: 
      Commands:
       Console:
        - lp user %player% parent set olive
      Messages:
        Player: '&aYou ranked up!'
        
**Context**
After editing it, I restarted the server and got an error message in console. 16.10 14:36:29 [Server] INFO [VotingPlugin] Successfully hooked into vault economy!
16.10 14:36:29 [Server] INFO [VotingPlugin] Hooked into vault permissions
16.10 14:36:29 [Server] ERROR [VotingPlugin] Failed to load a file, check startup log
16.10 14:36:29 [Server] INFO [VotingPlugin] VotingPlugin is up to date! Version: 6.7

How can I fix this?

**Comment by BenCodez** [comment]
You never send the file?

**Comment by Olivires** [comment]
> You never send the file?

sorry i hit enter too fast, i edited

**Comment by BenCodez** [comment]
Send the file in pastebin.com

**Comment by Olivires** [comment]
> Send the file in pastebin.com

https://pastebin.com/G2tRAApD

**Comment by BenCodez** [comment]
https://pastebin.com/TGNeTiSb

**Comment by Olivires** [comment]
tysmmmm
