### ISSUE TITLE
Rewards Won't Pay Out

### ISSUE THREAD

**Issue by Olivires** [Ben12345rocks/VotingPlugin#1197]
**Versions**
Latest Version I am pretty sure.

**Relevant information**

**Context**
So when I am opped and I vote, I get keys. When normal players vote, they don't get keys and I have no idea if they need a permission for it? I've tried looking but I didn't see any.

**Comment by BenCodez** [comment]
Send what you got?

**Comment by Olivires** [comment]
> Send what you got?

what do you mean? like the message in console? I kinda lost it but it says they voted.

**Comment by BenCodez** [comment]
The rewards you set, console message, anything related

**Comment by Olivires** [comment]
https://pastebin.com/htbD3rPB console 

https://pastebin.com/Wswu5vgw vote sites & rewards

**Comment by BenCodez** [comment]
change Console: to Commands:

**Comment by Olivires** [comment]
> change Console: to Commands:

will i need to add console after that? or will it jsut be commands:

**Comment by BenCodez** [comment]
just commands

**Comment by Olivires** [comment]
gosh thank you, you're literally such a great developer
