### ISSUE TITLE
Multiple Keys

### ISSUE THREAD

**Issue by Olivires** [Ben12345rocks/VotingPlugin#1198]
**Versions**
I can't remember but it was recent and on 1,17.1

**Relevant information**
https://pastebin.com/AmXdFGxX

**Context**
I tested the command in the server so I know it isn't goldencrates but whenever there is a vote party, it gives everyone multiple keys. The amount of keys given to each player is the same amount as how many players are online.

**Comment by BenCodez** [comment]
the commands under rewards execute for every player in the vote party

**Comment by Olivires** [comment]
smh oml you a literally amazing, thank you
