### ISSUE TITLE
How do I remove GUI

### ISSUE THREAD

**Issue by VainMC500** [Ben12345rocks/VotingPlugin#1200]
V6.7

Just would like to have a list of vote links instead of gui and all the "total vote features" and other stuff piled on top of the links.

Is there any way to do this?

EDIT: It says you can but I have no clue where to and after searching for a good 2 hours, it's hurting haha

**Comment by BenCodez** [comment]
set CHEST to CHAT in GUI.yml for what you want

**Comment by VainMC500** [comment]
Thank you, for your quick response. Is there specific permission nodes for all basic commands or are they set by default to the player? 

EDIT: Reading through config and this came up, 

 List of disabled commands from /vote
 List the specific permission
 E.g:
 -PERMISSION
DisabledCommands: []

How exactly does this work? Do I need to list in the brackets or create a -(permission) list like it says?

**Comment by BenCodez** [comment]
VotingPlugin.Player is given by default, can be disabled in config.yml
