### ISSUE TITLE
Tied monthly top voter position placeholder.

### ISSUE THREAD

**Issue by hirata-estate** [Ben12345rocks/VotingPlugin#1202]
**Versions**
VotingPlugin 6.6.1 & Purpur 1.17#1415
PlaceholderAPI 2.10.10

**Relevant information**
How to get %VotingPlugin_Top_Month_Position% placeholder with tied voters counting as the same place.

**Context**
Right now the placeholder is using the position from this list.
![image](https://user-images.githubusercontent.com/61897277/139631178-13783101-37ce-4025-b7a6-70780e3a0406.png)
I want the players Camelo, UItraic, and PlanetUrth (they all have 6 votes) to all appear as #1, and the ones with 5 votes appear as #2. How can I do this?

I'm using it for this:
![image](https://user-images.githubusercontent.com/61897277/139631335-6af02f44-78ed-4498-8d0b-587577404e92.png)

Thank you!

**Comment by BenCodez** [comment]
There is no way to do that currently, and to do that would require a lot of work.
