### ISSUE TITLE
GUI Shop Rewards

### ISSUE THREAD

**Issue by Vareska** [Ben12345rocks/VotingPlugin#1203]
**Versions**
Plugin version and spigot version
Latest

MendingBook:
      Identifier_Name: Mending Book
      Material: BOOK
      Amount: 1
      Name: '&cMending Book'
      Cost: 10
      Permission: ''
      CloseGUI: true
      RequireConfirmation: true
      Rewards:
        Items:
          Book:
            Material: BOOK
            Amount: 1
        Enchants:
          mending: 1
        Messages:
          Player: '&2You have successfully purchased a Mending Book'

How would I get this to actually give a mending book?

**Comment by BenCodez** [comment]
Use ENCHANTED_BOOK as the material
