### ISSUE TITLE
How to setup one reward for voting on multiple websites?

### ISSUE THREAD

**Issue by macolabre** [Ben12345rocks/VotingPlugin#1204]
**Versions**
Plugin version and spigot version

**Relevant information**
Configs that relate to the issue in a pastebin.

**Context**
Context about the question/concern

**Comment by macolabre** [comment]
Can anyone tell me who to make single reward for players voting on multiple websites?

**Comment by BenCodez** [comment]
use EverySiteReward?

**Comment by macolabre** [comment]
Hi Ben, i have created a ticket on you discord server "ticket-1155", however this is my config file, i would like to make it so that players get only one reward after they vote on multiple websites, if possible. This is my current config file. So when players vote on three websites they get 3 diamonds, and 3 vote crates that i have made for this. Sometimes they get 4 diamonds, i suppose that is somewhere in config file, but i am too affraid to change it because i had a lot of difficult to make it work due to hosting issues.

Can you help me configure this?
[ddd.txt](https://github.com/BenCodez/VotingPlugin/files/7509472/ddd.txt)

**Comment by BenCodez** [comment]
Then use AllSites reward?
