### ISSUE TITLE
Duplicate voting sites randomly appear over time

### ISSUE THREAD

**Issue by WoodypopDev** [Ben12345rocks/VotingPlugin#1205]
**Versions**
6.7

**Relevant information**
[Configs that relate to the issue in a pastebin.](https://pastebin.com/EqgNNA43)

**Context**
I added 4 sites to the votesites.yml. Then when I reboot the server I have 4 vote sites in the /vote tab, after a few, 3 more vote sites get added to the vote list as well as /vote, and the stuff it adds is duplicates of the sites I already have. (See pastebin for more context)

![Capture](https://user-images.githubusercontent.com/78826972/141650083-e14e3563-297a-479d-accc-58b68f9be1d4.PNG)
![Capture1](https://user-images.githubusercontent.com/78826972/141650101-bf23c665-3280-4ca6-bb29-44cb57edcb4e.PNG)

**Comment by BenCodez** [comment]
your votesites have the wrong service site, so it generates one with the correct one
