### ISSUE TITLE
I'm FearingTheFear, DisplacedSock sent me

### ISSUE THREAD

**Issue by FearingTheFear** [Ben12345rocks/VotingPlugin#1207]
**Versions**
Plugin version and spigot version.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**
DisplacedSocks sent me, I'm here to send a votesites.yml file.

**Comment by BenCodez** [comment]
You plan on sending the file?

**Comment by FearingTheFear** [comment]
Yes I do, I cannot attach a yml file in here though

**Comment by BenCodez** [comment]
Use pastebin.com

**Comment by FearingTheFear** [comment]
# 
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
VoteSites:
  MinecraftServers:
    Enabled: true
    Name: MinecraftServers
    ServiceSite: MinecraftServers
    VoteURL: https://minecraftservers.org/vote/627568
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - say hello
      AdvancedPriority:
        Reward1:
          Chance: 50
          Messages:
            Player: You got first reward
        Reward2:
          Chance: 20
          Messages:
            Player: You got second reward
        Fallback:
          Messages:
            Player: You got unlucky
      Items:
        item1:
          Material: DIAMOND
          Amount: 1
      Messages:
        Player: You voted
    Priority: 10
  MinecraftList:
    Enabled: true
    ServiceSite: MinecraftList
    VoteURL: https://minecraftlist.org/vote/26343
    VoteDelay: 24
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  PlanetMinecraft:
    Enabled: true
    ServiceSite: PlanetMinecraft.com
    VoteURL: https://www.planetminecraft.com/server/the-gaming-group/vote/
    VoteDelay: 24
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
    Priority: 10
  MinecraftServersList:
    Enabled: false
    ServiceSite: MinecraftServersList
    VoteURL: https://minecraftlist.org/vote/26343
    VoteDelay: 24
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
EverySiteReward:
  Commands:
  - crate give to %player% votecrate

**Comment by FearingTheFear** [comment]
???

**Comment by BenCodez** [comment]
That's not pastebin.com, you need to send it with pastebin or use code formatting
