### ISSUE TITLE
Redis bungee support for plugin messaging

### ISSUE THREAD

**Issue by quiquelhappy** [Ben12345rocks/VotingPlugin#1209]
**Is your feature request related to a problem? Please describe.**
It is realted to a problem; my votes are currently being forwarded just to one proxy, making players playing on other proxies not get the rewards

**Describe the solution you'd like**
This could be fixed by ussing redis plugin messaging too, without having to need to create a nuvotifier forwarding setup

**Describe alternatives you've considered**
A way of fixing it would be to forward the votes thru the nuvotifier proxy; but that would result in a more complicated deployment solution for me, since basically all proxies are working under the same configuration, thats why I would like this to natively use the redis plugin messaging

**Additional context**
Players only get the rewards in game when joining thru the proxy that is receiving the votes; even if they are already connected on some other proxy, which wouldnt happen by using redis plugin messaging

**Comment by BenCodez** [comment]
Never use redis, so I have no idea what I'd need to do to add this

**Comment by quiquelhappy** [comment]
It's quite easy, no worries! Basically, the problem right now is; my proxy is set to only deliver votes when a player is connected. Since a proxy can't detect the player is connected if it is connected thru another proxy, it never delivers the votes to the player. 

This can easily be fixed by checking if a player is online by using

- redis uuid to name (since I'm guessing votingplugin can only get names from votifier, if not, you can skip this): https://limework.net/JavaDocs/RedisBungee/com/imaginarycode/minecraft/redisbungee/RedisBungeeAPI.html#getUuidFromName(java.lang.String)
- redis is player online on network check https://limework.net/JavaDocs/RedisBungee/com/imaginarycode/minecraft/redisbungee/RedisBungeeAPI.html#isPlayerOnline(java.util.UUID)

to listen for player connections on other proxies use: https://limework.net/JavaDocs/RedisBungee/com/imaginarycode/minecraft/redisbungee/events/PlayerJoinedNetworkEvent.html

I wanted to do a PR myself but for some reason my IDE is not liking the pom.xml file on the repo, I'll try again later if you want, but it shouldnt take too long to implement.

Cheers

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/ this work? 
https://github.com/BenCodez/VotingPlugin/commit/3ca12f2c91fa85d21362797483df07eb1a66941d

**Comment by quiquelhappy** [comment]
I'll check in about 10h. Thanks for the commit

**Comment by quiquelhappy** [comment]
![image](https://user-images.githubusercontent.com/12534357/145071287-83c79315-11d7-4752-a8a5-b0cc7161b21e.png)
I can't see the log from https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/src/com/bencodez/votingplugin/bungee/RedisBungee.java#L21, perhaps `plugin.getProxy().getPluginManager().getPlugin("RedisBungee")` is returning null? I'm using redis by https://www.spigotmc.org/resources/redisbungee.87700/, which is indeed called "RedisBungee", so I can't see the issue here sadly. Maybe consider adding a softdependency on the bungee.yml/manifest file?

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/

Added soft depend, see if that's enough. I did lookup other plugins using redis and it seems they used this method, worst case I just add an option in the config to enable no matter what.

**Comment by quiquelhappy** [comment]
testing

**Comment by quiquelhappy** [comment]
still just seeing
```
22:50:38 [INFO] [VotingPlugin] VotingPlugin loaded, using method: PLUGINMESSAGING, PluginMessagingVersion: 1
22:50:38 [INFO] [VotingPlugin] Detected using dev build number: 295
22:50:38 [INFO] Enabled plugin VotingPlugin version 6.7.1 by BenCodez
```

redis did load before votingplugin, which is good
```
22:50:34 [INFO] [RedisBungee] Loaded server id pv.
22:50:34 [INFO] [RedisBungee] Successfully connected to Redis.
22:50:34 [INFO] [RedisBungee] 6.0.16 <- redis version
```

can you try sending me a build that has the option force-enabled so I can test it, then we just gotta make sure its related to `plugin.getProxy().getPluginManager().getPlugin("RedisBungee")` and we fix it? cheers

**Comment by quiquelhappy** [comment]
testing https://github.com/BenCodez/VotingPlugin/commit/d12f73d2fa5bc76bda1e8c3311e08345f053f4af

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/

https://github.com/BenCodez/VotingPlugin/commit/d12f73d2fa5bc76bda1e8c3311e08345f053f4af

See if this works

Edit: Guess you beat me to it? :)

**Comment by quiquelhappy** [comment]
`[SEVERE] java.lang.NullPointerException: Cannot invoke "com.bencodez.votingplugin.bungee.Config.getRedisSupport()" because the return value of "com.bencodez.votingplugin.bungee.VotingPluginBungee.getConfig()" is null`

(the option is in the config, I deleted it to let it regen)

**Comment by BenCodez** [comment]
oops, now?

**Comment by quiquelhappy** [comment]
it doesnt show any errors, but the message still doesnt show; are you sure the logger works in that context? or the class is being created?

```
23:10:02 [INFO] [VotingPlugin] VotingPlugin loaded, using method: PLUGINMESSAGING, PluginMessagingVersion: 1
23:10:02 [INFO] [VotingPlugin] Detected using dev build number: 298
23:10:03 [INFO] Enabled plugin VotingPlugin version 6.7.1 by BenCodez
```
