### ISSUE TITLE
Regular players can access other player's GUI

### ISSUE THREAD

**Issue by Rismack** [Ben12345rocks/VotingPlugin#1211]
**Versions**

- Plugin version: 6.7.1
- Spigot version: git-Paper-788 (MC: 1.16.5)

**Relevant information**

My Config.yml file: https://pastebin.com/kU0ZZ8Ad

**Context**

Hello! I installed VotingPlugin a few days ago and I've realized that regular players can access other player's GUI through the "Top" and "Today" menu. When a player clicks on the "Top" icon in the GUI, they can see the top players' heads. If they click on any of the heads, they'll access the main menu of other player's GUI (as if they did "/vote gui otherplayer").

The same happens for the "Today" icon in the GUI. Regular players can click it to see the heads of those players who voted today, but they can also click on any of the heads and they'll access the main menu of other player's GUI.

The thing is that regular players don't have permission to access any information related to other players because I didn't give them permissions. In fact, commands like "/vote GUI otherplayer" or "/vote last otherplayer" don't work at all for regular players.

I think I may be doing something wrong, so that's why I'm not posting this under the "bugs" section but I'm not sure of what's really going on.

Thanks in advance!

**Comment by BenCodez** [comment]
This better? https://bencodez.com/job/VotingPlugin/

**Comment by Rismack** [comment]
Yeah, absolutely! Now it's working perfectly.

Thank you!
