### ISSUE TITLE
How to make vote reward

### ISSUE THREAD

**Issue by Koyorice** [Ben12345rocks/VotingPlugin#1213]
**Versions**
1.18
**Relevant information**
Configs that relate to the issue in a pastebin.

**Context**
How to make vote reward

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Rewards

**Comment by Koyorice** [comment]
I can't understand the management document

**Comment by BenCodez** [comment]
You just define rewards under each votesite in votesites.yml, you can even do it from /av gui
