### ISSUE TITLE
How to make a vote amount reward

### ISSUE THREAD

**Issue by The-Epic** [Ben12345rocks/VotingPlugin#1215]
1.18
Plugin version and spigot version

SpecialRewards.yml
Configs that relate to the issue in a pastebin.

How do i make something happen when a player gets to a certain amount of votes? eg 10 votes and it runs  a command?
Context about the question/concern

**Comment by BenCodez** [comment]
milestones or cumulative

**Comment by The-Epic** [comment]
milestones i think it would be classed as

**Comment by BenCodez** [comment]
so use that?

**Comment by The-Epic** [comment]
ive tried to get it to work but nothing is showing in game

**Comment by BenCodez** [comment]
send what you got

**Comment by The-Epic** [comment]
https://pastebin.com/pK3emtUx

**Comment by BenCodez** [comment]
that looks good

**Comment by The-Epic** [comment]
yea i thought it did but if i run /votereward in game it doesnt show it, is there anything i would need to setup for that to work?

**Comment by BenCodez** [comment]
./votereward is not a valid command

**Comment by The-Epic** [comment]
is there not a command for it? i thought i saw it on another server, sorry if this is me being dumb

**Comment by BenCodez** [comment]
use /av gui

**Comment by The-Epic** [comment]
Ok i found it thanks for the help
