### ISSUE TITLE
Vote party

### ISSUE THREAD

**Issue by triesharder** [Ben12345rocks/VotingPlugin#1216]
**Versions**
VotingPlugin 6.8, git-paper-81, implementing API version 1.18.1-R0.1-SNAPSHOT (git: 8c189d0)

**Describe the bug**
Vote party is giving the same reward many times

**To Reproduce**
1. Start a vote party
2.Note that the reward is being given many times per party.
3. Every party the number of rewards was different. 6 equal rewards 1st, 12 in 2nd and, 8 in 3rd party, i had to disable vote party on my server.

**Expected behavior**
i expected the command to run only 1 time for each party.

**Comment by BenCodez** [comment]
the commands under Rewards are executed for each player

**Comment by triesharder** [comment]
Yes, that is happenning, but occurred more than once per vote party, i was supposed to receive only 2 keys, but in the first vote party the plugin ran the command 3 times for each players, next vp: 6 times each player, 3rd vp: 4 times each player

**Comment by BenCodez** [comment]
send your config

**Comment by triesharder** [comment]
Config.yml - https://justpaste.it/3rrmo
SpecialRewards.yml - https://justpaste.it/8wq90

**Comment by BenCodez** [comment]
VoteParty:
      Enabled: false
      VotesRequired: 70
      GiveAllPlayers: false
      GiveOnlinePlayersOnly: true
      ResetEachDay: false
      ResetWeekly: false
      ResetMonthly: false
      OnlyOncePerDay: false
      ResetExtraVotesMonthly: false
      CountFakeVotes: true
      UserVotesRequired: 0
      CountOfflineVotes: true
      Broadcast: '&aRecompensa Enviada à todos! Obrigado por Votarem!'
      Commands: []
      Rewards:
        Commands:
        - crates givekey * rara 2
        Items: {}

the command execute for every player.. so every player it runs the command to give all players....

**Comment by triesharder** [comment]
But why it happens more than once for each player? We were supposed to receive only 2 keys each, but we received way more

**Comment by BenCodez** [comment]
because the command gives all players rather then just that specific player

**Comment by triesharder** [comment]
Oh i think i understood, it sent 2 keys for every player for each player online, sorry for the all the confusion.
So,

if i use "crates givekey %player% rara 2" it should work how i want?

**Comment by BenCodez** [comment]
yes
