### ISSUE TITLE
VotingPlugin PAPI placeholders cannot be parsed by non-player objects.

### ISSUE THREAD

**Issue by ZepsiZola** [Ben12345rocks/VotingPlugin#1217]
**Versions**
VotingPlugin v6.8
Purpur build 1496 1.18.1

**Describe the bug**
Non-player objects seem to not be able to parse the placeholder `%VotingPlugin_VotePartyVotesRequired%` and other such placeholders like `%VotingPlugin_Top_Month_1%` correctly. Nothing is outputted. However when I do `/papi parse me %VotingPlugin_VotePartyVotesRequired%`, the correct value (3000) is returned.

**To Reproduce**
You could also use the DiscordSRV bot to reproduce the behaviour:
1. Go into config.yml and add `"!voteparty": "VoteParty - %VotingPlugin_VotePartyVotesCurrent%/%VotingPlugin_VotePartyVotesRequired%"` to `DiscordCannedResponses:` section.
2. Go into the Discord bots respective server and type in "!voteparty" and the text, "VoteParty - /", will be returned from the bot.

**Expected behavior**
What is meant to happen is that the Discord bot should properly parse the placeholders and return something like "VoteParty - 1425/3000" when "!voteparty" is sent to it.

**Screenshots/Configs**
https://cdn.discordapp.com/attachments/669916943058468884/930770556431777842/unknown.png
https://cdn.discordapp.com/attachments/669916943058468884/930948935625871370/unknown.png
https://cdn.discordapp.com/attachments/669916943058468884/930949032447201360/unknown.png

**Additional context**
Apparently this issue seems to be because the placeholders unnecessarily require a player object to return a value even though they should be the same no matter what player is looking at them.

I added the canned-response `"!test1": "Test %spark_tickduration_10s%"` to the discord bot and it did actually return the placeholder, showing that it is not the discord bot that is the problem here, it is most likely the VotingPlugin PAPI extension which is the problem.

**Comment by BenCodez** [comment]
Doesn't look like a votingplugin issue, if it works with /papi parse then nothing I can do

**Comment by ZepsiZola** [comment]
It seems to be a VotingPlugin issue. If it's not a VotingPlugin issue then I don't know what else it could be. I will reiterate that the DiscordSRV bot was able to return the `%spark_tickduration_10s%` placeholder correctly but it was not able to return the `%VotingPlugin_VotePartyVotesRequired%` placeholder correctly.

It only works when you do `/papi parse` because it's "target" is a player when you do that and so it is able to return a value.

The man at the bottom of this screenshot also describes what I am saying:
https://cdn.discordapp.com/attachments/669916943058468884/930770556431777842/unknown.png

**Comment by BenCodez** [comment]
Placeholders are based on a player, there is nothing I can do. That plugin needs to handle placeholders differently

**Comment by ZepsiZola** [comment]
If placeholders always have to be based on a player, then why does the `%spark_tickduration_10s%` placeholder work? (it's from Spark PAPI extension)

It looks like your plugin might need to handle placeholders differently if DiscordSRV can handle Spark's placeholders but not VotingPlugin's placeholders. It seems that Spark is able to do placeholders without being based on a player.

I mean no offence when I say this. VotingPlugin is a very good and reliable plugin other than the fact that all the placeholders have to be based on a player.

Wouldn't it make more sense if only the placeholders that depend on a specific player's data, like `%VotingPlugin_Points%`, should be based on a player, while placeholders that are the same no matter what player they are based on, like `%VotingPlugin_top_month_1%`, should not be based on a player?

**Comment by BenCodez** [comment]
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/PlaceholderExpansion

As far as I know placeholderapi always require a player. It appears spark plalceholders are directly added into placeholderapi, no expansion (or atleast handled not like other placeholders). 

I have no control over this.

**Comment by ZepsiZola** [comment]
![image](https://user-images.githubusercontent.com/49735083/149239186-bdafd429-21d4-45cb-8c1b-5fbcabe062c0.png)
https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/hooks/PlaceholderAPIExpansion.java

This other dev is saying and demonstrating that PAPI placeholders do not need to be based on a player.
Perhaps the fact that placeholders don't have to be based on players is new in PlaceholderAPI.

`public @Nullable String onRequest(@Nullable OfflinePlayer player, @NotNull String identifier) {` 
I think that this line of code shows how the player object is Nullable and henceforth not completely required.

**Comment by BenCodez** [comment]
https://www.dropbox.com/t/ed1jzEwRaDqU5XzI

https://bencodez.com/job/VotingPlugin/

Does this work? Guess I added something to prevent no player placeholders not working. Not tested currently

**Comment by ZepsiZola** [comment]
![image](https://user-images.githubusercontent.com/49735083/149243329-2ebbe723-c6ec-4fbc-b285-44d0bbdb7180.png)
That still doesn't work. It's no rush though.

**Comment by BenCodez** [comment]
Do placeholders still work?

**Comment by ZepsiZola** [comment]
![image](https://user-images.githubusercontent.com/49735083/149243962-90eeafaf-da32-4472-91b5-d4d371892a3d.png)
Yeah they work when you do `/papi parse me %placeholder%`

**Comment by BenCodez** [comment]
You did a restart with the expansion I linked? It should be working with that.

**Comment by ZepsiZola** [comment]
Yeah I replaced the extension with the new one that was in the dropbox link.

**Comment by BenCodez** [comment]
Anything in console? I might have to debug this later.

**Comment by ZepsiZola** [comment]
![image](https://user-images.githubusercontent.com/49735083/149245415-6f30ed6d-5d82-4cc4-9363-c831887ab1e8.png)
![image](https://user-images.githubusercontent.com/49735083/149245596-ca1c176c-3542-4ade-b9de-a0ee0518858b.png)

No error messages show up in the console.

**Comment by ZepsiZola** [comment]
What is the status on this issue?

**Comment by BenCodez** [comment]
Latest expansion version 1.5 and latest plugin versions should work

**Comment by ZepsiZola** [comment]
Oh yes it works. Thank you for fixing this.

**Comment by KLUDIII** [comment]
what is the expansion that you sent with dropbox link?

**Comment by BenCodez** [comment]
> what is the expansion that you sent with dropbox link?

I have no idea

**Comment by KLUDIII** [comment]
Can you help me fix this issue? The issue is when i papi parse me %votingplugin_votepartyvotesrequired% it shows, but on my scoreboard it doesn't (scoreboard was made using skript). The error when i reload the script is "Region %votingplugin_votepartyvotesrequired% could not be found". I'm running PAPI version 2.11.6, VotingPlugin 6.18.4 and i downloaded the expansion version 1.5.

**Comment by BenCodez** [comment]
> Can you help me fix this issue? The issue is when i papi parse me %votingplugin_votepartyvotesrequired% it shows, but on my scoreboard it doesn't (scoreboard was made using skript). The error when i reload the script is "Region %votingplugin_votepartyvotesrequired% could not be found". I'm running PAPI version 2.11.6, VotingPlugin 6.18.4 and i downloaded the expansion version 1.5.

If it works with papi parse then there isn't much I can do

**Comment by KLUDIII** [comment]
do you have any idea on how to fix it?

**Comment by BenCodez** [comment]
> do you have any idea on how to fix it?

Based on what I see it looks like the placeholder isn't being parsed

**Comment by KLUDIII** [comment]
so how do i make it appear on scoreboard, cause i've been trying for the past 4 hours and i got no success

**Comment by BenCodez** [comment]
> so how do i make it appear on scoreboard, cause i've been trying for the past 4 hours and i got no success

There isn't much I can do for you here

**Comment by KLUDIII** [comment]
how'd you fix it for the guy above?

**Comment by BenCodez** [comment]
> how'd you fix it for the guy above?

it's been 3 years and your issue is different

**Comment by KLUDIII** [comment]
yeah makes sense, thanks anyways i guess...

**Comment by KLUDIII** [comment]
also which version of VotingPlugin is latest but not dev build?

**Comment by BenCodez** [comment]
> also which version of VotingPlugin is latest but not dev build?

the latest spigot version

**Comment by KLUDIII** [comment]
6.18.4 is dev build and its the latest version

**Comment by BenCodez** [comment]
> 6.18.4 is dev build and its the latest version

6.18.4 isn't the current dev build version number

**Comment by KLUDIII** [comment]
every other placeholder works except for the votingplugin ones, must be votingplugin issue

**Comment by BenCodez** [comment]
> every other placeholder works except for the votingplugin ones, must be votingplugin issue

I need more info on your issue

**Comment by KLUDIII** [comment]
like what? I can give you more info tmrw cause its 3 am im not on my pc rn

**Comment by BenCodez** [comment]
> like what? I can give you more info tmrw cause its 3 am im not on my pc rn

Make a new issue or create a ticket on discord with screenshots or something

**Comment by KLUDIII** [comment]
can you send me the discord link?

**Comment by BenCodez** [comment]
> can you send me the discord link?

you can find it on spigot plugin page
