### ISSUE TITLE
Issue with placeholders not updating correctly (at least for the points)

### ISSUE THREAD

**Issue by banicola** [Ben12345rocks/VotingPlugin#1219]
**Versions**
6.8.1
Placeholder expension: 1.5

**Describe the bug**
When you add or remove points to a player the value of the placeholder %VotingPlugin_Points% is not correct. It makes it impossible to use it as a payment method as it does not decrease when a player use them.

**To Reproduce**
1. Add points to a player
2. Check the value of the placeholder %VotingPlugin_Points%
3. Remove points to a player
4. Check the value of the placeholder %VotingPlugin_Points%

**Expected behavior**
If I add 10 points to a player it should have 10 points in %VotingPlugin_Points% and if I remove points it should instantly update the placeholder

**Screenshots/Configs**
![image](https://user-images.githubusercontent.com/25954399/150505621-f9f00278-64de-497a-8178-feba71f13088.png)

The values in White are the result of %VotingPlugin_Points%

**Additional context**
I already had the issue in a previous update. I'm now on Minecraft 1.18.1 and the issue came back. The previous bug report: https://github.com/BenCodez/VotingPlugin/issues/1188

I'm using MYSQL as the data storage, it might be a reason of the issue too for the desync

**Comment by BenCodez** [comment]
Disable auto placeholder cache?

**Comment by banicola** [comment]
This setting?

AlwaysWaitForCachePlaceholders: false

It's on false already

**Comment by banicola** [comment]
They issue doesn't happen if I'm using SQLITE as my data storage instead of MYSQL.

**Comment by BenCodez** [comment]
# Enable auto caching placeholders
AutoCachePlaceholders: true

Add or disable that.
