### ISSUE TITLE
Im sure its operator error but cant figure it out

### ISSUE THREAD

**Issue by mikediamo** [Ben12345rocks/VotingPlugin#1222]
**Versions**
6.8.1

**Relevant information**
VoteSites:
  # VoteSite key
  # Used for saving data for votesites
  # Use a short name if you can
  MinecraftServers:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true

    # Display name of voting site
    Name: 'MinecraftServers.org'

    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 5

    # If true, voteside will be hidden from some GUI's, similar to being disabled
    Hidden: false

    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'MinecraftServers.org'

    # vote url for /vote
    # Format for this can be set in Config.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
    VoteURL: 'https://minecraftservers.org/server/631337'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24

    # Use to have a minute votedelay
    #VoteDelayMin: 30

    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false

    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false

    #Offset time for /vote next caculations
    #TimeOffSet: 0

    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false

    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    DisplayItem:
      Material: 'DIAMOND'
      Amount: 1

    # Rewards to give
    # https://github.com/BenCodez/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
        Console:
        -economy give %player% 300
        -crates givekey %player% vote 1
      # Send player a message
      Messages:
        Player: '&bYou voted Thanks'
  # Site 2 example
  Site2:
    Enabled: false
    Name: 'Site2'
    ServiceSite: 'PlanetMinecraft.com'
    VoteURL: 'link to vote URL here, used in /vote'
    VoteDelay: 24
    DisplayItem:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
      - 'say hello'
      # Advanced example
      # 50% chance for reward1, if reward1 not given then 20% chance to get reward2, if reward2 not given then fallback
      AdvancedPriority:
        # Similar to priority, but no need to have to use reward files
        # Add requirements under each reward
        # Will go in order from list here and try to run each of the following rewards...
        # This name can be anything, but they need to be different
        Reward1:
          Chance: 50
          # Any other requirement here
          # If any requirement fails, the next reward will be attempted
          # Use permission requirement for rank based rewards
          #RequirePermission: true
          #Permission: 'permhere'
          Messages:
            Player: 'You got first reward'
        Reward2:
          Chance: 20
          Messages:
            Player: 'You got second reward'
        # Fallback, 100% chance, after other rewards fail chances
        Fallback:
          Messages:
            Player: 'You got unlucky'

      # Give 1 diamond
      Items:
        item1:
          Material: DIAMOND
          Amount: 1

      Messages:
        Player: 'You voted'

# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
EverySiteReward: {}

**Context**
So Im totally new to this trying to start a server for the wife and kids. 
In game when starting up "VotingPlugin: Detected yml error, please check console for detail."
Console "27.01 23:26:54 [Server] WARN Detected no voting sites, this may mean something isn't properly setup"
I have tried doing the video tutorial on your site three times so i must be missing something please help. thank you for your time and help

**Comment by BenCodez** [comment]
use pastebin.com to send the file

**Comment by mikediamo** [comment]
ok thank you sorry for my ignorance i didnt know what it was. thanks for the quick response

**Comment by mikediamo** [comment]
https://pastebin.com/E0KSn8f5

**Comment by mikediamo** [comment]
is this what u needed?

**Comment by BenCodez** [comment]
https://pastebin.com/4x06U8DM use this

**Comment by mikediamo** [comment]
Thank you sir it seems to work what did i do wrong?
How do i add 4 more via cut and paste
Thank you very much for the fast help do you have a link for donations

**Comment by BenCodez** [comment]
just let the votesites auto generate. Donation link on plugin page.

**Comment by mikediamo** [comment]
donation sent keep up the great work and again thank you

**Comment by mikediamo** [comment]
ok tried to add a second  site so what am i doing wrong now. I never figured out what i did wrong on 1st site. overall i want to have 5 sites. thanks for your patience and help

https://pastebin.com/gvuT5VMA

**Comment by BenCodez** [comment]
It was the spacing of the commands, that looks good right now.

**Comment by mikediamo** [comment]
maybe its a site issue on number 2
so i just cut and space make sure i call it site 3

**Comment by mikediamo** [comment]
paste not space

**Comment by mikediamo** [comment]
ah yes the video said 3 spaces and i couldnt replicate it

**Comment by BenCodez** [comment]
Just vote on the site and they will auto generate.

**Comment by mikediamo** [comment]
im confused on what you mean im new to this stuff

**Comment by mikediamo** [comment]
if you got time to explain?

**Comment by BenCodez** [comment]
vote on the site, reopen the file, site is created for you.
https://github.com/BenCodez/VotingPlugin/wiki/Adding-VoteSites

**Comment by mikediamo** [comment]
looks like im missing priority on site 2

**Comment by BenCodez** [comment]
you don't really need that
