### ISSUE TITLE
Toggle vote reminding. 

### ISSUE THREAD

**Issue by Castiella** [Ben12345rocks/VotingPlugin#1223]
**Is your feature request related to a problem? Please describe.**
Some players love the vote reminder we have configured, but some do not and it really annoys them. Could there be a way players could toggle this themselves? For example /votingplugin toggle reminder 

While I appreciate we can give them the "noremind" permission, with a large playerbase this can be tiresome.

Thank you & I hope you consider this request!

**Comment by BenCodez** [comment]
/vote ToggleReminders
   VotingPlugin.Commands.Vote.ToggleReminders
   Enable/disable vote reminders

Added recently, doesn't save through restarts

**Comment by Castiella** [comment]
Thank you. Will there be a future update to persist through restarts?

**Comment by BenCodez** [comment]
No plans for that currently, would just use a lot of data to save all that
