### ISSUE TITLE
How do i get votes to count in /votetotal?

### ISSUE THREAD

**Issue by b0mbyy** [Ben12345rocks/VotingPlugin#1224]
**Versions**
Plugin version and spigot version 
Plugin Version:6.8.1 Spigot/Purpur Version: Purpur 1.18.1 Build:1544

**Relevant information**
This is just a question on how i can get votes to count in /votetotal.

**Context**
Trying To Figure out how i can get votes to show up in /votetotal

**Comment by BenCodez** [comment]
You vote and it adds totals.

**Comment by b0mbyy** [comment]
I Know But it is not showing up on the totals.

**Comment by BenCodez** [comment]
Is the server getting the vote? What kind of setup?

**Comment by b0mbyy** [comment]
Here is what my VoteSites YML looks like pls help.

https://pastebin.com/DgZBhhzQ

**Comment by BenCodez** [comment]
https://pastebin.com/5zcfkGR0

use that

**Comment by b0mbyy** [comment]
How Does It Count the votes, Do I need to do a enable a query?

**Comment by BenCodez** [comment]
Unless you messed with stuff, it should do it by default

**Comment by b0mbyy** [comment]
Here Is My Plugin Files If You Need A look at them.
[pebblehost-255374-nwhj1n.zip](https://github.com/BenCodez/VotingPlugin/files/7992724/pebblehost-255374-nwhj1n.zip)
[pebblehost-255374-t2fdo4.zip](https://github.com/BenCodez/VotingPlugin/files/7992725/pebblehost-255374-t2fdo4.zip)

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting check this

**Comment by b0mbyy** [comment]
I did everything it said and it still says invalid service site on the voting sites.

**Comment by BenCodez** [comment]
send what it said

**Comment by b0mbyy** [comment]
[VotingPlugin] No vote has been recieved from minecraftservers.org/server/631630, may be an invalid service site. Please read: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting
05.02 07:26:40 [Server]  [VotingPlugin] No vote has been recieved from minecraft-mp.com/server-s299739, may be an invalid service site. Please read: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting
05.02 07:26:40 [Server]  [VotingPlugin] No vote has been recieved from craftlist.org/glowberrymc, may be an invalid service site. Please read: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting
05.02 07:26:40 [Server]  [VotingPlugin] No vote has been recieved from minecraft.buzz/server/4092, may be an invalid service site. Please read: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting
05.02 07:26:40 [Server]  [VotingPlugin] No vote has been recieved from minecraftsurvivalservers.com/server/218-glowberrymc, may be an invalid service site. Please read: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting
05.02 07:26:40 [Server]  [VotingPlugin] No vote has been recieved from minecraft-server-list.com/server/485430, may be an invalid service site. Please read: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting

It Apparently thinks that the service sites are invalid even though they are known voting lists.

I also tried just the main part of the URLs but that didn't work either.

**Comment by BenCodez** [comment]
Vote on the website, look in console, it will say the service site, if you get no message, votifier isn't working.

**Comment by b0mbyy** [comment]
I already did try to vote on the sites but to no avail.

**Comment by BenCodez** [comment]
Did you get a message in console?

**Comment by b0mbyy** [comment]
Nope

**Comment by BenCodez** [comment]
Then votifier isn't working

**Comment by b0mbyy** [comment]
Ok then how do i fix the problem.

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting
