### ISSUE TITLE
AutoCreateVoteSites bug

### ISSUE THREAD

**Issue by LogGits** [Ben12345rocks/VotingPlugin#1225]
**Versions**
paper 1.18.1 build 186, voting plugin 6.8.1

**Describe the bug**
`AutoCreateVoteSites: true` regenerates the votsites.yml for a vote site even if it's already in there with enabled set to false.

**To Reproduce**
`AutoCreateVoteSites: true`
then in the votesite.yml set the enabled state to false then try voting on that one and it will readd the votesite and set it to true.

**Expected behavior**
It should ignore the votesite if it already exists and is disabled.

**Comment by BenCodez** [comment]
Disable the option?

**Comment by LogGits** [comment]
That's what i did, just wondered if it should readd to the config if it's already there.

**Comment by BenCodez** [comment]
I think I made it check, but it was overly complicated, since disabled votesites aren't loaded. 

Will check this out later when I get a chance.

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/

Better?
