### ISSUE TITLE
Error In Bungee Console 

### ISSUE THREAD

**Issue by SuryaRajgor** [Ben12345rocks/VotingPlugin#1227]
**Versions**
Plugin version 6.8.2 and spigot version: 1.18.1

**Relevant information**
Bungee Config : https://pastebin.com/7QL52qd2
SMP Config : https://pastebin.com/XDszE81Q

**Context**
i used it from 1 month but suddenly i got error in bungee console and vote not forwarded to SMP (other server)
![image](https://user-images.githubusercontent.com/9131487/154812497-3ba95de6-0620-43de-8146-cdac1d4325f5.png)

![image](https://user-images.githubusercontent.com/9131487/154813324-f08ad8f4-974d-432d-a86e-0fb9b5f3e3cc.png)

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/
This better?

**Comment by SuryaRajgor** [comment]
YES ITS WORKED THANK YOU
