### ISSUE TITLE
Console command reward not working

### ISSUE THREAD

**Issue by atomisgray** [Ben12345rocks/VotingPlugin#1228]
**Versions**
latest version

**Relevant information**

  Site2:
    Enabled: true
    Name: MCTools
    ServiceSite: mctools.org
    VoteURL: https://mctools.org/votifier-tester
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
        Console:
        - 'ei give %player% vote_crate_key 1'

**Context**
Reward isnt being given my console isnt even running the command at all
I've already looked at the rewards wiki for guidance but i can't find any help

**Comment by BenCodez** [comment]
send that in pastebin

**Comment by atomisgray** [comment]
not pastebin but i think they're similar?
https://paste.helpch.at/ovoribiqig.cs

**Comment by BenCodez** [comment]
send the full file? Your missing a bit

**Comment by atomisgray** [comment]
https://paste.helpch.at/qeyunawexu.php

this is the whole config

**Comment by BenCodez** [comment]
You can't have two sites with the same key/identifier

      Site2:

**Comment by atomisgray** [comment]
my bad ty

**Comment by atomisgray** [comment]
will that fix the console running the command?

**Comment by BenCodez** [comment]
should

**Comment by atomisgray** [comment]
that worked thank you
