### ISSUE TITLE
Specify rewards inside SpecialRewards.yml

### ISSUE THREAD

**Issue by GTP95** [Ben12345rocks/VotingPlugin#1232]
I'm trying to set up rewards for some of the events inside the file SpecialRewards.yml, but apparently I'm listing the rewards in the wrong place. Take as example the reward for the very first vote of a player. I've created inside the Rewards folder a file called RewardForFirstVote.yml, then inside SpecialRewards.yml I have the following block:
```yml
# First vote rewards
FirstVote: {RewardForFirstVote}
  Messages:
    Player: '&aYou voted for your first time!'
```
But then when reloading the server I get the following error:
```BASH
22:24:55] [Server thread/ERROR]: Cannot load plugins/VotingPlugin/SpecialRewards.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'reader', line 8, column 1:
    FirstVote: {RewardForFirstVote} 
    ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 9, column 3:
      Messages:
      ^
```
Followed by a stack trace. What am I doing wrong?
**Versions**
VotingPlugin 6.8.3 on 442-Spigot-699290c-62d9762 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)

**Relevant information**
[SpecialRewards.yml](https://pastebin.com/Hjy6G2qM), [RewardForFirstVote.yml](https://pastebin.com/sPKkb5A7)

Thank you for your help

**Comment by BenCodez** [comment]
{RewardForFirstVote} - remove this

**Comment by GTP95** [comment]
Ok, but which is the correct way to specify the file containing the reward for the event?

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Rewards

**Comment by GTP95** [comment]
Thank you, somehow I missed that page. But note that to make it work I also had to change the indentation for the message block in the monthly and weekly top voter sections, as they had one too much indentation level. I'm quite sure I didn't change the indentation there, so you may want to check that the files created by the plugin have the correct identation

**Comment by BenCodez** [comment]
You need to remove the message block, otherwise it will yml error

**Comment by GTP95** [comment]
I just fixed the indentation and it seems to work... I'll let you know if I need to delete it
