### ISSUE TITLE
Error by loadup the mariadb.jdbc.Driver and Picojobs

### ISSUE THREAD

**Issue by editon96** [Ben12345rocks/VotingPlugin#1234]
**Versions**
Pupur 1.18.2 Build 1591 (a fork of Paper with extras)
VotingPlugin version 6.8.3

**Describe the bug**
While I let Startup the Server it printes that error:

https://pastebin.com/HnabAv2a - look by youselve

Werard all other Servers dont have a Problem only that one.
And I reinstal the Plugin too.

**Comment by BenCodez** [comment]
Another plugin is shading a mysql driver or something

**Comment by editon96** [comment]
I send that too to the Picojobs Devs. But I thank you that you also think about a posibble Fix for that.

**Comment by Picono435** [comment]
Yeah I am pretty sure it is from my side. I am using slimJar to "shade" mariadb I have to take a look into it.

**Comment by editon96** [comment]
okay under the new Version PicoJobs 6a are the same Bug I thought.

Here the Error on PicoJobs: https://github.com/Picono435/PicoJobs/issues/179

**Comment by editon96** [comment]
looks like its fixed

**Comment by Picono435** [comment]
I was able to fix this by relocating mariadb (there was a typo in jdbc which made it not relocate). Maybe implement this one at your side too to make sure it doesn't happen to other plugins?

**Comment by BenCodez** [comment]
I don't compile mariadb in votingplugin, so relocating is useless. I made a change to not try to use mariadb to avoid this
