### ISSUE TITLE
Supported Websites?

### ISSUE THREAD

**Issue by CodexApple** [Ben12345rocks/VotingPlugin#1235]
**Versions**
VotingPlugin 6.8.3 using Purpur 1.18.2

**Context**
I keep getting a "Possible issue with Service Site, has the server gotten the vote from ServersMinecraft"

I added the proper link and Service Site name inside of the VoteSites.yml am I missing something?

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting
