### ISSUE TITLE
HELPPP

### ISSUE THREAD

**Issue by EnderHacker0** [Ben12345rocks/VotingPlugin#1237]
i installed votingplugin on a velocity server (because my main server cant open ports) and the plugin just cannot connect to the mysql server. i checked the logs and the plugin DO recieve votes pls make the velocity plugin able to connect to the mysql server itself not by letting the spigot server to do it

**Comment by BenCodez** [comment]
send the log

**Comment by yuuichirou0808** [comment]
![Screen Shot 2022-03-24 at 8 54 56 AM](https://user-images.githubusercontent.com/82391008/159820727-5c9012c8-c14e-48b4-ad66-d667ba9beeec.png)
(the log is too long)

**Comment by BenCodez** [comment]
https://bencodez.com/job/MySQLDriver/ you need to put this jar in your plugins folder

**Comment by yuuichirou0808** [comment]
now it shows no error but the plugin still doesn't work

**Comment by BenCodez** [comment]
did you follow the setup here? https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING

**Comment by yuuichirou0808** [comment]
i did but it's still not working
(the spigot server only has the port 25565 open)

**Comment by BenCodez** [comment]
you don't need any port for any server other than velocity

**Comment by yuuichirou0808** [comment]
the plugin is not working it shows no error

**Comment by BenCodez** [comment]
what's not working? Did you try the troubleshooting steps on the wiki?

**Comment by yuuichirou0808** [comment]
yea i tried
the spigot server just doesn't take actions

**Comment by BenCodez** [comment]
send bungeeconfig.yml and bungeesettings.yml, you have votifier on velocity right? Does /votingpluginbungee vote (player) (site) work?

**Comment by EnderHacker0** [comment]
`# --------------------------
# Bungee Setup 
# Only if using votingplugin bungee to send votes
# REQUIRES RESTART FOR CHANGES TO TAKE EFFECT
# --------------------------

# Plugin using bungee, requires plugin on bungee server
UseBungeecord: true

# What type of bungee setup
# Requires restart and set on all servers
# https://github.com/BenCodez/VotingPlugin/wiki/Bungeecord-Setups
# Available:
# SOCKETS
# PLUGINMESSAGING
# MYSQL
BungeeMethod: PLUGINMESSAGING

# Enables more debug messages for communication between servers
# Use /votingpluginbungee status for testing communication
BungeeDebug: false

# Get the plugin to broadcast to all servers
# If false you need to enable 
# Only use for global rewards (one per network), otherwise you will get double broadcasts
BungeeBroadcast: false

# For pluginmessaging method only
# Whether to broadcast on cached votes
BungeeBroadcastAlways: false

# If true, the server won't broadcast votes
# To be used in conjuction with Broadcast setting on bungee
DisableBroadcast: false

# If true, offline rewards will be stored per server, rather than global
# This shouldn't need to be set unless you get alot of cross server rewards issues
# You can also specify the server within the rewards
# Requires server name below to be correct
PerServerRewards: false

# If true, milestones work per server
# Please note totals still sync, but milestones can be claimed on each server
# Needs to be set across all needed servers
PerServerMilestones: false

# If true, points will be given on a per server level
# Points will be added when server gets vote from bungee
PerServerPoints: false

# If true, plugin will trigger VotifierEvent
# Should allow some compability with other plugins
TriggerVotifierEvent: false

# What server this is in bungee (must match)
# Also can be applied to rewards
Server: lobby

# Rewards from bungee vote party
# Gives to only players only
# Use regular voteparty rewards otherwise
# Can edit via /av gui
BungeeVotePartyRewards: {}

# -----------------------------
# For socket setup below only
# -----------------------------
# Options available here:
# https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-SOCKETS
`

**Comment by yuuichirou0808** [comment]
[BungeeSettings.txt](https://github.com/BenCodez/VotingPlugin/files/8346713/BungeeSettings.txt)
[bungeeconfig.txt](https://github.com/BenCodez/VotingPlugin/files/8346717/bungeeconfig.txt)
github doesn't support yml files)

**Comment by BenCodez** [comment]
Does /votingpluginbungee vote (player) (site) work?

**Comment by yuuichirou0808** [comment]
no

**Comment by BenCodez** [comment]
./votingpluginbungee status?

**Comment by yuuichirou0808** [comment]
![Screen Shot 2022-03-26 at 9 53 29 AM](https://user-images.githubusercontent.com/82391008/160220182-8643c4a3-3a28-45ff-8b94-c61828d2c8c2.png)

**Comment by BenCodez** [comment]
login into the server and run the command

**Comment by yuuichirou0808** [comment]
i am already logged in and theres other players on the server

**Comment by BenCodez** [comment]
Are you sure your logged into the server as shown in the message? It says no players online.

**Comment by yuuichirou0808** [comment]
yes i am sure

**Comment by BenCodez** [comment]
Is velocity set right? 

I guess just use each server independent https://github.com/BenCodez/VotingPlugin/wiki/Bungeecord-Setups (shown below)

**Comment by yuuichirou0808** [comment]
i cannot set up votifier on the spigot server only the port 25565 is open

**Comment by BenCodez** [comment]
you can try nuvotifier forwarding with pluginmessaging

**Comment by yuuichirou0808** [comment]
how to set it up??

**Comment by BenCodez** [comment]
look in nuvotifier config

**Comment by yuuichirou0808** [comment]
spigot or velocity?

**Comment by BenCodez** [comment]
velocity

**Comment by yuuichirou0808** [comment]
still does not work

**Comment by BenCodez** [comment]
then nothing I can do for you

**Comment by yuuichirou0808** [comment]
is  there a way i can connect the two servers with discord?

**Comment by BenCodez** [comment]
no

**Comment by yuuichirou0808** [comment]
with discord plugins

**Comment by yuuichirou0808** [comment]
OH ITS WORKING NOW
IT WAS ALWAYS WORKING BUT IM NOT NOTIFIED WHEN I VOTE!!!
