### ISSUE TITLE
Jar File Version Control

### ISSUE THREAD

**Issue by X-Niter** [Ben12345rocks/VotingPlugin#1239]
Your current jar file downloaded by users/clients does not currently have version control identifiers. 

As a someone who manages multiple servers with a loaf of jar applications to manage, having the version control being a part of the jar files name schema is a very helpful QOL improvement as it allows for quickly comparing versions from what's inside the server to the one on the spigot/download page without having to reload the server and read through a whole console log.

IDEA TL;DR; Start to include version control in the jar file name schema, EX: VotingPlugin-6.8.4.jar instead of just VotingPlugin.jar

**Comment by BenCodez** [comment]
Not sure how the majority of people about this, I know I was asked this before but decided to not make the switch at that time. Could see about switching this though.
