### ISSUE TITLE
How can i forward votes from my proxy with nuvotifier?

### ISSUE THREAD

**Issue by xF3d33** [Ben12345rocks/VotingPlugin#1242]
**Versions**
lates

**Context**
i have nuvotifier and voting plugin both in my proxy. how can i forward votes to my backends server? do i need votingplugin also in my proxy?

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING

**Comment by xF3d33** [comment]
i read that but do i need voting plugin also in my proxy in order do send votes in mi spigot servers?

**Comment by xF3d33** [comment]
ok i fixed but now votes will be forwarded only if the player is online when the votifier receive the vote. 

![immagine_2022-04-26_105740252](https://user-images.githubusercontent.com/67204462/165262924-edf2e968-3b15-4cb4-975f-059a0454bed8.png)

**Comment by BenCodez** [comment]
> ok i fixed but now votes will be forwarded only if the player is online when the votifier receive the vote.
> 
> ![immagine_2022-04-26_105740252](https://user-images.githubusercontent.com/67204462/165262924-edf2e968-3b15-4cb4-975f-059a0454bed8.png)

That shouldn't be a problem?
