### ISSUE TITLE
Question about URL

### ISSUE THREAD

**Issue by PhoenixSK1** [Ben12345rocks/VotingPlugin#1243]
Hi! I don't know if I'm writing this in the right place, but I'd like to ask a question about the vote url that appears in the chat after using the /vote command.

Is it possible to do something like "1: Site name - [Click Here]" where "click here" represents the given url? But of course not to be visible but replaced by another text.

I saw that there is a pattern in the "votesites.yml" file how to probably do this, but it absolutely didn't work in my case. That pattern is [Text = "ANY TEXT TO CLICK ON HERE", url = "URLHERE"]

I will be very happy for your help. Well thank you! :)

**Comment by BenCodez** [comment]
You need to disable forcelinks in config.yml to use this: [Text = "ANY TEXT TO CLICK ON HERE", url = "URLHERE"]
