### ISSUE TITLE
Updated to 6.9 now errors when monthly top vote Rewards are sent.

### ISSUE THREAD

**Issue by TomLewis** [Ben12345rocks/VotingPlugin#1244]
**Versions**
6.9

**Describe the bug**
Before I updated to 6.9 my monthly vote rewards would work fine, now they error out.
https://gist.github.com/TomLewis/358d0e93765fd555562b31250f486d50

**To Reproduce**
1. Use PurPur 1.18.2 with Votingplugin 6.9
2. Monthly rewards (attatched)
3. Errors out/does not work.

**Expected behavior**
To work.

**Screenshots/Configs**
From my plugins/VotingPlugin/SpecialRewards.yml
https://gist.github.com/TomLewis/713a1ed3cb776c996e30da7c3f1d9e34

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/ this should prevent the rewards from failing if a particle fails.

Send the error with that build, should provide a lot more details into the exact cause.

**Comment by TomLewis** [comment]
Is there a way to manually trigger a monthly prize so I don't have to wait until next month to test it?

**Comment by BenCodez** [comment]
./av forcetimechanged MONTH
