### ISSUE TITLE
Placeholder returns "...." insteand of "0"

### ISSUE THREAD

**Issue by Kaesor** [Ben12345rocks/VotingPlugin#1245]
**Versions**
Plugin version : 6.9
Spigot version : paper 1.18.2-313

**Describe the bug**
Placeholder returns "...." insteand of "0" 

**To Reproduce**
With the plugin BeautyQuest : 
`[BeautyQuests]: Cannot parse placeholder VotingPlugin_Total_Daily for player XXXXX : got ...., which is not a number. (PlaceholderRequirement, unknown quest)`

**Expected behavior**
Replace the "...." by "0" if there are no votes

**Comment by BenCodez** [comment]
send your config.yml

**Comment by Kaesor** [comment]
The config.yml : https://pastebin.com/NH0eQqnu

**Comment by BenCodez** [comment]
# Always force placeholders to return value if the value isn't cached
    # This should prevent server from crashing when pulling placeholders on main thread
    # Only affects placeholderapi placeholders
    AlwaysWaitForCachePlaceholders: true

    # Enable auto caching placeholders
    # Generally this works well, but if you need to cache placeholders manually set them below
    AutoCachePlaceholders: false

add these to your config.yml

**Comment by Kaesor** [comment]
Well, thank you! I feel like it's good (no more console spam)
