### ISSUE TITLE
Regarding votegivepoints command

### ISSUE THREAD

**Issue by belzaaron** [Ben12345rocks/VotingPlugin#1248]
**Versions**
Paper: 1.19
VotingPlugin: 6.9.2

**Context**
Hi there, awesome plugin - I've noticed votegivepoints. When trying to use this command (/votegivepoints) - it is completely blank, is the intention that a player should be able to give their points to another user? Is this a feature? I think pooling points / giving points is a decent feature personally. Again, executing this `votegivepoints` command results in nothing, no errors, no messages, essentially no feedback. I've also looked through the source and find no references except for the plugin.yml - which is basically useless here. Any feedback on what this is intended to do would be great. Thanks

**Comment by BenCodez** [comment]
you need to enable the command in the config.yml

**Comment by belzaaron** [comment]
My mistake - sorry for the ignorance.

For legacy viewers (in `config.yml`):
```yml
# Allow transfer of vote points between players
AllowVotePointTransfers: false # change to true
```

Closing.
