### ISSUE TITLE
VotingSites.YLM rewards not working

### ISSUE THREAD

**Issue by antiGriefer** [Ben12345rocks/VotingPlugin#1251]
**Versions**
latest

**Relevant information**
[Configs that relate to the issue in a pastebin.](https://pastebin.com/2420DmCL)

**Context**
The only thing that happens when a player votes is the broadcast:''Thanks player for voting on %servicesite%

Instead id like the command /acb %player% 100 to run along with a message.

How do I configure this as a every site reward?

Thanks

**Comment by BenCodez** [comment]
no / on commands

**Comment by antiGriefer** [comment]
> no / on commands

the messages arent working either

**Comment by BenCodez** [comment]
space the messages 2 spaces out (both lines)
