### ISSUE TITLE
EventHandling

### ISSUE THREAD

**Issue by Osamu01** [Ben12345rocks/VotingPlugin#1253]
**Versions**
_Plugin version and spigot version_
Irrelevant

**Relevant information**
_Configs that relate to the issue in a pastebin._
N/A

**Context**
Context about the question/concern
I am trying to use getmessage for the playervoteevent to pass the following to my discord 
![image](https://user-images.githubusercontent.com/35316988/185347105-566cd5c5-010e-4260-93a2-383c9f590eef.png)
but when I try to do this, it returns property or field 'getmessage' cannot be found. How do I go about doing this?

**Comment by BenCodez** [comment]
What are you doing?
