### ISSUE TITLE
Hex Colour Support

### ISSUE THREAD

**Issue by elkoyofficial** [Ben12345rocks/VotingPlugin#1256]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Would love to be able to use hex colours within the vote plugin.

**Describe alternatives you've considered**

**Additional context**

**Comment by BenCodez** [comment]
Hex format: &#FF0000#

**Comment by elkoyofficial** [comment]
Legend, appreciate it. <3 I was trying &# :P
