### ISSUE TITLE
How to run "eco give %player% 100" for offline players when they vote?

### ISSUE THREAD

**Issue by Im-Bob** [Ben12345rocks/VotingPlugin#1257]
**Versions**
VotingPlugin 6.9.4
Spigot 1.19.2

**Relevant information**
Config.yml: https://pastebin.com/BBFAzEyM
VoteSites.yml: https://pastebin.com/ENjtaPS5

**Context**
How can I make it so offline players can get money (eco give %player% 100) for each vote? Online players can get it, but not offline players

**Comment by BenCodez** [comment]
You want rewards to run while offline?
