### ISSUE TITLE
Add an API Event when a vote is available

### ISSUE THREAD

**Issue by emmanuelvlad** [Ben12345rocks/VotingPlugin#1261]
**Is your feature request related to a problem? Please describe.**
There is an event triggered when all vote sites are available, I wish there was an event when one vote is available so I could plug some reminders

**Describe the solution you'd like**
Trigger an event when a site is available (with the site's data)

**Comment by BenCodez** [comment]
I'll look at trying to add this

**Comment by BenCodez** [comment]
This appears to be a little difficult to implement. Not sure how I want to go about this, will leave this open until I find a better way

**Comment by ypdq** [comment]
Damn ! That feature can be gamechanger! Especially to create discord bots. I will definitely use it if there is this feature!

**Comment by BenCodez** [comment]
I'll look at trying to add it when I can, just won't be very efficient as I would like. Probably will make it a config option to enable it

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/commit/a76da52a0a94c98ed47790fa7f757064acc670ab

Add `PerSiteCoolDownEvents: true` in the config.yml

In my testing it worked pretty okay, let me know how it works for you.

Build here: https://bencodez.com/job/VotingPlugin/

**Comment by BenCodez** [comment]
Added per votesite rewards to allow running commands on vote cooldown ending, incase you want it

    # Reward to run when cooldown ends for this votesite
    # Enable PerSiteCoolDownEvents in Config.yml to use this
    #CoolDownEndRewards:
    #  Messages:
    #    Player: '&aTime to go vote on site1'

Build here: https://bencodez.com/job/VotingPlugin/
