### ISSUE TITLE
Add an API Event after new week/month

### ISSUE THREAD

**Issue by emmanuelvlad** [Ben12345rocks/VotingPlugin#1262]
**Describe the solution you'd like**
Trigger an event when a new week/month begins (with the top players data)

**Usecases**

- Give rewards using own methods
- Listen to this event to send a discord message of the top of the week/month

**Comment by BenCodez** [comment]
This already exists, it just doesn't provide any top voter data.

Events:
DateChangedEvent - any time change
DayChangeEvent - day change
MonthChangeEvent - month change
PreDateChangedEvent - before any data change has been prossed - can be used to display top voters
WeekChangeEvent - week change

Don't have much on the wiki on this yet

https://bencodez.github.io/AdvancedCore/com/bencodez/advancedcore/api/time/events/package-summary.html
