### ISSUE TITLE
MC Paper Server asking if Plugin is Up to Date, Won't Start

### ISSUE THREAD

**Issue by BlackWidowTMC** [Ben12345rocks/VotingPlugin#1263]
**Versions**
This server is running Paper version git-Paper-358 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f26e9cc)

Error occurred while enabling VotingPlugin v6.10.0 (Is it up to date?)
25.12 00:21:19 [Server] INFO java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.ConfigurationSection.getConfigurationSection(String)" is null
25.12 00:21:19 [Server] INFO at com.bencodez.votingplugin.advancedcore.api.rewards.RewardHandler$107.subRewards(RewardHandler.java:2319) ~[VotingPlugin.jar:?]
25.12 00:21:19 [Server] INFO at com.bencodez.votingplugin.advancedcore.api.rewards.RewardHandler.checkSubRewards(RewardHandler.java:201) ~[VotingPlugin.jar:?]
25.12 00:21:19 [Server] INFO at com.bencodez.votingplugin.advancedcore.api.rewards.RewardHandler.checkSubRewards(RewardHandler.java:212) ~[VotingPlugin.jar:?]
25.12 00:21:19 [Server] INFO at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:899) ~[VotingPlugin.jar:?]
25.12 00:21:19 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
25.12 00:21:19 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
25.12 00:21:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
25.12 00:21:19 [Server] INFO at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-358]
25.12 00:21:19 [Server] INFO at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-358]
25.12 00:21:19 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-358]
25.12 00:21:19 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-358]
25.12 00:21:19 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-358]
25.12 00:21:19 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-358]
25.12 00:21:19 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-358]
25.12 00:21:19 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
25.12 00:21:19 [Server] INFO Disabling VotingPlugin v6.10.0

**Comment by BenCodez** [comment]
Did you enable choice rewards?

Either way this should solve that (wait 5 minutes before downloading):
https://bencodez.com/job/VotingPlugin/

**Comment by BlackWidowTMC** [comment]
I believe so.

Matthew Gineris
571-428-5838
________________________________

**Comment by BenCodez** [comment]
Then either disable that, add the choice rewards, or use the build above.

**Comment by BlackWidowTMC** [comment]
Fixed it. Thanks for the help!

Matthew Gineris
571-428-5838
________________________________
