### ISSUE TITLE
Rewards not working if voting while offline/off the server. Vote works.

### ISSUE THREAD

**Issue by Tosfoy** [Ben12345rocks/VotingPlugin#1264]
**Versions**
1.19.2 - BungeeCord + Paper (Proxy, Lobby, Survival, etc)
VotingPlugin only on Proxy + Survival
Using PLUGGINMESSAGE
nuVotifier only on Proxy.

**Describe the bug**
Players are not receiving their rewards unless they vote while on the server.
I tested and votes are registering, as I went from 547 to 550 votes) but did not receive rewards upon joining the survival.

**Expected behavior**
Rewards to be given when joining the survival server after voting while being offline
Right now, the following works:
 - Being Online
 - Votinf while veing on the Hub, or any other servers and away from Survival, then getting on Survival
 - Unvanishing (Only applies to admins)
 I assume this is a problem related to the proxy rather than spigot votingplugin

**Screenshots/Configs**
Reward file
![image](https://user-images.githubusercontent.com/58991099/210031644-7b0964c3-e27e-46fb-b659-9d719f252a1f.png)

Bungeeconfig: https://pastebin.com/q3s2M6dA
Spigot bungeesttings: https://pastebin.com/CYBHsZq0
Spigot config: https://pastebin.com/MVBgGCmz

**Comment by BenCodez** [comment]
Try with this set to false: WaitForUserOnline: true

**Comment by Tosfoy** [comment]
It's already set to true, check Bungeeconfig pastebin

**Comment by BenCodez** [comment]
I said set it false, I just coped your config, probably should of changed that

**Comment by Tosfoy** [comment]
Ahh! My bad, very tired rn

This worked!
Will send a donation, this plugin and the support you give for free is unbeatable, thanks a lot!
