### ISSUE TITLE
I Not Find The Vote Port

### ISSUE THREAD

**Issue by LarsiiiiPingu** [Ben12345rocks/VotingPlugin#1267]
**Versions**
Newest, Spigot 1.19.4 Snapshot

**Relevant information**
Not I Have

**Context**
How I Find The Vote Port For The Plugin?

My Votesite Requested A Vote-Port , But I Don't Find It In Your Plugin , Can You Help Please?

**Comment by BenCodez** [comment]
You set the port in votifier

**Comment by LarsiiiiPingu** [comment]
who? i don't know sorry

**Comment by BenCodez** [comment]
It's another plugin

**Comment by LarsiiiiPingu** [comment]
i use your "VotePlugin" it is outdated? and i have it not seen or i false understand it?

**Comment by LarsiiiiPingu** [comment]
sorry i'm germany i'm have middle problems with english

**Comment by BenCodez** [comment]
You need votifier and VotingPlugin

**Comment by LarsiiiiPingu** [comment]
ah ok i'm understand :D

**Comment by LarsiiiiPingu** [comment]
can you help me with the public.key? i cant open the data , i doesnt have an app to open 
and i cant set and votelistener without the key , :c can you help?

**Comment by BenCodez** [comment]
open it with notepad or something

**Comment by LarsiiiiPingu** [comment]
i not have it

**Comment by BenCodez** [comment]
Then get it?

**Comment by LarsiiiiPingu** [comment]
ok thank you
