### ISSUE TITLE
Define a limit of votes per hour for a player

### ISSUE THREAD

**Issue by GabrielChev** [Ben12345rocks/VotingPlugin#1268]
Hello !

**Versions**
Plugin version : 6.10
spigot-paper version : 18.2 and 1.19.2 (multiple server)

How can i define a maximum vote for a player during a time period ?
Some of players use VPN and some sites donn't prevent that.
They can vote multiple times for the same pseudo.

Can i define a number of rewards max for a player pseudonym in 3 hours (for exemple) ?

thanks in advance !
best regards
Gabriel

**Comment by BenCodez** [comment]
Enable this https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/Resources/VoteSites.yml#L45

**Comment by GabrielChev** [comment]
But if i want allow 2 votes with same pseudo for a site, to allow a player to vote once more with his phone, or for autorise a player to vote for a friend 1 more time ?

**Comment by BenCodez** [comment]
That just limits the plugin from giving a reward for the same user a reward more than once

**Comment by GabrielChev** [comment]
so there is no solution to adjust the number of rewards allow per X hours 
?

**Comment by BenCodez** [comment]
Not really

**Comment by GabrielChev** [comment]
Thank you very much for your quick answers

**Comment by abhiyashthakur** [comment]
nice
