### ISSUE TITLE
Help Placeholder 

### ISSUE THREAD

**Issue by Kenshin175** [Ben12345rocks/VotingPlugin#1270]
plugin voting

hey excuse my bad english i am french, i would like to know which Placeholder i have to put to indicate to the players how many votes he has left to vote? example I have 5 sites he has voted on 3 sites he is missing 2 sites

**Comment by BenCodez** [comment]
%votingplugin_canvotesites%

**Comment by Kenshin175** [comment]
merci beaucoup
