### ISSUE TITLE
Can you make a tutorial with it? Because at the Youtube its bad tutorials and alt

### ISSUE THREAD

**Issue by Tolmwn** [Ben12345rocks/VotingPlugin#1276]
Hey, how are you? I want to ask you how can i setup my vote plugin on my server. I have already check a lot tutorials at the youtube but still not working for me ! So i msg you write now and ask for help ! Thanks you :D

**Comment by BenCodez** [comment]
Just follow this: https://github.com/BenCodez/VotingPlugin/wiki/Setting-Up

**Comment by Tolmwn** [comment]
its working now but i had set this code 

 ##All vote rewards
##Reward for voting on all sites in one day
AllSites:
  Messages:
    Player: '&e%player% &fhas voted for all the &e/vote &fsites todey and unlocked
      &e/fly&f command for 3h!'
  Commands:
  - tempfly add %player% 1
 #Rewards: {}

but its not working when ppl vote all vote at one day. So can you help me with that?

**Comment by BenCodez** [comment]
Send that with code tags or pastebin

**Comment by Tolmwn** [comment]
im not sure what you mean but this is my folder
[Vote.zip](https://github.com/BenCodez/VotingPlugin/files/12012808/Vote.zip)

**Comment by Tolmwn** [comment]
Hey @BenCodez, can you help me with this or no ?

**Comment by BenCodez** [comment]
Try this:

    AllSites:
      Messages:
        Player: '&e%player% &fhas voted for all the &e/vote &fsites todey and unlocked &e/fly&f command for 3h!'
      Commands:
      - tempfly add %player% 1

**Comment by Tolmwn** [comment]
Yea its working ! Thanks you :D
