### ISSUE TITLE
cannot get votingplugin to issue crazycrates key

### ISSUE THREAD

**Issue by ViktorXen** [Ben12345rocks/VotingPlugin#1287]
**Versions**
VotingPlugin 6.13.1
Paper 1.20+
Can't find the spigot version
just a .yml

not familiar with pastebin.

Hi. I'm really hoping you can help me.
I bought a new public server and I'm running Bskyblock.
I've got things set up and the test vote is recieved,
messages ARE being sent when the advanced priority is selected
which means the reward is being given. I set temp debug output on 
and I can confirm that the reward is supposedly being given to the player.

I have tried every permutation of the commands part, 
    Reward1:
      Chance: 70
      Messages:
         Player: 'Gold'
      Commands:
        Console:
          - 'cc give p 1 Golden %player%'

but when the command that works ingame ( /cc give p 1 Golden %player%)
is used, the only change is that the console tells me the player Golden is not online.
I have tried every permutation of the command I can think of including putting 
( commands: console: ) above Messages: and I have restarted so much I'm dizzy.

nothing I have tried will give the player a votecrate key. I have watched every tutorial
and read every webpage I can find. It has been a couple of days and I am ready to set my PC on fire.

I am praying you may be able to help, or to suggest who I might ask for help. please.

**Comment by BenCodez** [comment]
send the full file in pastebin.com

**Comment by ViktorXen** [comment]
which file should i send?

**Comment by BenCodez** [comment]
votesites.yml

**Comment by ViktorXen** [comment]
https://pastebin.com/dmZeBhF6

**Comment by BenCodez** [comment]
Have you tried it with /av vote?

**Comment by ViktorXen** [comment]
I've been trying to send a test vote from the site. I haven't 
forgite me, I've been reading docs for a week. what does /av do exactly?

**Comment by BenCodez** [comment]
runs a local test vote.

You might want to check this in your case as well: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting

**Comment by ViktorXen** [comment]
okay. that bit worked. but sending the test vote still doesn't.

**Comment by BenCodez** [comment]
Check this: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting

**Comment by ViktorXen** [comment]
Thanks for the link. I'll step through everything again once I can digest it.
