### ISSUE TITLE
High cpu ussage 

### ISSUE THREAD

**Issue by Paradis4432** [Ben12345rocks/VotingPlugin#1289]
**Versions**
latest on both

**Describe the bug**
after some time i get low tps, made a profile and found in the cpu tree:
54.6% - 8,136 s com.vexsoftware.votifier.io.netty.util.concurrent.FastThreadLocalRunnable.run
13.7% - 2,044 s net.minecraft.server.dedicated.DedicatedServer$1.run
11.4% - 1,709 s net.minecraft.server.MinecraftServer.func_240783_a_
10.6% - 1,591 s io.netty.util.concurrent.SingleThreadEventExecutor$5.run

**To Reproduce**
1. this has been an issue for some time now, but the general details are an arlight server, running 1.16.5, with pixelmon mainly. using nuvotifier and voting plugin. Theres arround 40, 50 players

**Expected behavior**
im hoping i could lower the cpu usage a little bit

**Screenshots/Configs**
![image](https://github.com/BenCodez/VotingPlugin/assets/49301263/707150ac-996a-4dcc-9d67-c97a026896c4)

**Additional context**
at first when the server boots up everything is fine, but after some time tps start to drop, low cpu ussage, low memory ussage, yet low tps. i believe its a memory leak caused by either nuvotifier or votingplugin

**Comment by Paradis4432** [comment]
if you want to talk directly or privately contact me at my discord: Paradis#4432

**Comment by BenCodez** [comment]
Wanna send the timings report?

**Comment by Paradis4432** [comment]
yeah this is the spark profile, i can start a timing report rn https://spark.lucko.me/yO8FymfUfw

**Comment by BenCodez** [comment]
Don't see nothing related to voting right now

**Comment by Paradis4432** [comment]
heres the timings report https://timings.spigotmc.org/?url=palisavube

**Comment by BenCodez** [comment]
Doesn't show any useful info

**Comment by Paradis4432** [comment]
i dont know what else i could provide

**Comment by Paradis4432** [comment]
i have a jprofiler running

**Comment by BenCodez** [comment]
I need that info from the screenshot, you didn't view the source of the issue on it

**Comment by Paradis4432** [comment]
![Screenshot_86](https://github.com/BenCodez/VotingPlugin/assets/49301263/11007d2c-a8d2-44f7-aba8-bd909a0d77d0)
![Screenshot_85](https://github.com/BenCodez/VotingPlugin/assets/49301263/26f8f1fb-df9a-431b-baeb-24688b379dca)
![Screenshot_84](https://github.com/BenCodez/VotingPlugin/assets/49301263/67ab61f1-7b2f-4cb5-b977-8479c0794593)
![Screenshot_87](https://github.com/BenCodez/VotingPlugin/assets/49301263/45a229a4-3a2a-4c9c-96f9-7e96aac5338d)
![Screenshot_88](https://github.com/BenCodez/VotingPlugin/assets/49301263/e3e256c9-7873-45d4-b7b8-e34f19411f87)

**Comment by BenCodez** [comment]
I don't see votingplugin in that at all. Do you wanna try votifierplus and see if there is any difference?

**Comment by Paradis4432** [comment]
maybe this helps too 
![Screenshot_91](https://github.com/BenCodez/VotingPlugin/assets/49301263/7927b77f-4ec7-4685-ae35-271f40836657)
![Screenshot_90](https://github.com/BenCodez/VotingPlugin/assets/49301263/53786446-9726-4f61-95a2-53e4c7f7a51e)
![Screenshot_89](https://github.com/BenCodez/VotingPlugin/assets/49301263/3fd1137f-1e5d-45ee-aa04-73c7de27691e)
![Screenshot_92](https://github.com/BenCodez/VotingPlugin/assets/49301263/c5f7e9c5-627c-4e85-b151-d6c804e6a248)

**Comment by Paradis4432** [comment]
if i cant find the issue here ill try with votifierplus, but i would prefer not to

**Comment by BenCodez** [comment]
I mean that all looks normal. I don't think the issue is votingplugin or votifier right now. The timing report shows something else

**Comment by Paradis4432** [comment]
ill wait for tps to drop and update you, thanks, please dont close this, ill come back with more data
