### ISSUE TITLE
How Do Milestones Work?

### ISSUE THREAD

**Issue by jmancox330** [Ben12345rocks/VotingPlugin#1290]
More specifically, I am trying to make it so every day, 3 days, 1 week, and 1 month, the player who reaches a voting milestone is given a LuckPerms permission. How do I do this? Also, how do I make it so milestones reset every month?

**Comment by BenCodez** [comment]
Milestones give a 1 time reward at x amount of votes. There is an option to enable monthly resets of them

**Comment by jmancox330** [comment]
Yeah, I've mostly figured it out, but the rewards seem to cumulate after every vote, not 3 days, 1 week, 1 month, etc.
This is my config:

Cumulative:
  # Number of votes required
  # Allows multiple cumulative rewards
  # Number be be around ' (E.g. '1')
  # Can have multiple listed here
  '3':
    Enabled: true
    # Whether or not votes must be made in same day/week
    # Useful if you want to require a certain number of voting sites to be voted on
    # for a daily/weekly reward instead of all of them
    # Valid options
    # AllTime
    # Monthly
    # Weekly
    # Daily
    TotalToUse: Monthly
    # Blacklist recurring votes
    #BlackList:
    #- 40
    # Whether or not to gives cumulative reward for every x number of votes, default: true
    Recurring: true
    Rewards:
      Commands:
      - lp user %player% permission set voter.2 true 
  '7':
    Enabled: true
    # Whether or not votes must be made in same day/week
    # Useful if you want to require a certain number of voting sites to be voted on
    # for a daily/weekly reward instead of all of them
    # Valid options
    # AllTime
    # Monthly
    # Weekly
    # Daily
    TotalToUse: Monthly
    # Blacklist recurring votes
    #BlackList:
    #- 40
    # Whether or not to gives cumulative reward for every x number of votes, default: true
    Recurring: true
    Rewards:
      Commands:
      - lp user %player% permission set voter.3 true
  '15':
    Enabled: true
    # Whether or not votes must be made in same day/week
    # Useful if you want to require a certain number of voting sites to be voted on
    # for a daily/weekly reward instead of all of them
    # Valid options
    # AllTime
    # Monthly
    # Weekly
    # Daily
    TotalToUse: Monthly
    # Blacklist recurring votes
    #BlackList:
    #- 40
    # Whether or not to gives cumulative reward for every x number of votes, default: true
    Recurring: true
    Rewards:
      Commands:
      - lp user %player% permission set voter.4 true
  '30':
    Enabled: true
    # Whether or not votes must be made in same day/week
    # Useful if you want to require a certain number of voting sites to be voted on
    # for a daily/weekly reward instead of all of them
    # Valid options
    # AllTime
    # Monthly
    # Weekly
    # Daily
    TotalToUse: Monthly
    # Blacklist recurring votes
    #BlackList:
    #- 40
    # Whether or not to gives cumulative reward for every x number of votes, default: true
    Recurring: true
    Rewards:
      Commands:
      - lp user %player% permission set voter.5 true

**Comment by BenCodez** [comment]
Cumulative rewards are not the same as milestones, cumulative runs every x amount of votes

**Comment by jmancox330** [comment]
Oh, where is the config for milestones? Is there a wiki section for milestones?

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/Resources/SpecialRewards.yml#L117

**Comment by jmancox330** [comment]
Great, works now. Thanks!
