### ISSUE TITLE
Disable Votes Broadcasting

### ISSUE THREAD

**Issue by kajusauz** [Ben12345rocks/VotingPlugin#1293]
**Versions**
Plugin v6.13.1 - git-paper-102 1.20.1

**Context**
How do I disable the Broadcasts shown in the picture?
I've searched Every single YML file in the plugin's folder and I couldn't find where to disable it.

![image](https://github.com/BenCodez/VotingPlugin/assets/92986514/67f81ea1-85ab-4492-9ea6-a4d26d056d94)

**Comment by BenCodez** [comment]
Just set the message to `''`

**Comment by kajusauz** [comment]
That's the problem! I cannot find where the message is! I went thru every single file containing the word "Broadcast" and deleted the line if broadcast was in quotes but it still sends the message.

**Comment by BenCodez** [comment]
It's in config.yml deleting the config line just makes it use the default
message

**Comment by kajusauz** [comment]
Ohh.... Alr. I'll try that tmr cuz I can't rn. Thanks.
