### ISSUE TITLE
ForceOffline doesn't work & floodgate player doesn't get rewards if they are not on the server while voting

### ISSUE THREAD

**Issue by hasankayra04** [Ben12345rocks/VotingPlugin#1295]
**Versions**
Plugin version and spigot version.
6.13.1
**Describe the bug**
floodgate player doesn't get rewards if they are not on the server while voting so i wanted handle it myself using skript but ForceOffline doesn't work either. I get the voting message but the command in the rewards section doesn't execute.

**Expected behavior**
Work?

**Screenshots/Configs**

        # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: true

**Comment by BenCodez** [comment]
Geyser/floodgate support is kinda 50/50. 

Did you enable geyser support? Do players vote with prefix?

**Comment by hasankayra04** [comment]
Yes to both, i could have  workaround the issue if forceoffline worked, sadly it doesn't.

**Comment by BenCodez** [comment]
Disable geyser support if your voting with prefix, send your votesites.yml

**Comment by hasankayra04** [comment]
https://hastebin.com/share/kanuvunoji.yaml

**Comment by BenCodez** [comment]
Try adding ForceOffline: true under Rewards

**Comment by hasankayra04** [comment]
https://paste.hasankayra04.com/paste.php?id=8
Still doesn't work.

**Comment by BenCodez** [comment]
You need it on the votesite and under Rewards

**Comment by hasankayra04** [comment]
If you kindly check the paste i provided it is in file votesites.yml and forceoffline is under rewards.

**Comment by BenCodez** [comment]
Minecraft-MP_com:
      Enabled: true
      ServiceSite: Minecraft-MP.com
      VoteURL: https://frogcraft.com.tr/url/mmp
      VoteDelay: 24.0
      ForceOffline: true
      DisplayItem:
        Material: GRASS
        Amount: 1
      Rewards:
        ForceOffline: true
        Messages:
          Player: '&a%ServiceSite% oyun için teşekkürler!'
        Commands:
       - mmp %player%

You need it on both. Like above.

**Comment by hasankayra04** [comment]
Will try in a few hours. Thanks!

**Comment by hasankayra04** [comment]
Works now, thanks.
