### ISSUE TITLE
Rewards for backend servers

### ISSUE THREAD

**Issue by hiiamken** [Ben12345rocks/VotingPlugin#1297]
**Versions**
Version: 6.14 , Skyblock: Paper 1.19.4, Survival: 1.20.1

**Relevant information**
bungeeconfig: https://controlc.com/5b1b05d4
spigotconfig (skyblock): https://controlc.com/27e0ce91
spigotconfig (survival): https://controlc.com/4c2ab2ff

**Context**
How can I set it up so that players only receive vote rewards on one server? Currently, when a player receives rewards on the Sky server and then goes to the Sur server, they receive rewards again and get a vote notification. I want them to receive rewards only on one specific server. What should I do?

**Comment by BenCodez** [comment]
# Have a reward on each server
    # If false, will send to online server only
    SendVotesToAllServers: false
You already disabled this, so it should do that.

you have votifier on bungee?

**Comment by hiiamken** [comment]
yes i have

**Comment by BenCodez** [comment]
Feel like it should work properly then. Try /votingpluginbungee vote (player) (site)

**Comment by hiiamken** [comment]
I believe I've read all the information in the config and followed the instructions correctly, but it's not working. Could it be because I'm using a shared MYSQL database?

**Comment by BenCodez** [comment]
Shouldn't matter

**Comment by hiiamken** [comment]
<img width="650" alt="Ảnh chụp Màn hình 2023-09-05 lúc 07 39 15" src="https://github.com/BenCodez/VotingPlugin/assets/142149960/7beb0995-e755-475e-9efc-251b4fe76ae8">
Here is skyblock
<img width="660" alt="Ảnh chụp Màn hình 2023-09-05 lúc 07 39 43" src="https://github.com/BenCodez/VotingPlugin/assets/142149960/ccba2d3d-1a61-41b4-aea4-711b361bced8">
here is survival

**Comment by BenCodez** [comment]
Have you done a restart since changing settings? If not try that.

**Comment by hiiamken** [comment]
Do you need me to provide any additional information? I'm willing to share whatever you need

**Comment by hiiamken** [comment]
I restarted it yesterday, and the initial config I sent was set up before the restart. After it didn't work, I came here to ask you.

**Comment by BenCodez** [comment]
Feels like the option isn't working. Try another restart. If not enable debug in bungeeconfig.yml and send the log on a vote.

**Comment by hiiamken** [comment]
Do I need to restart all the backend servers, or is it sufficient to restart the Bungee server?

**Comment by BenCodez** [comment]
bungee should be enough

**Comment by hiiamken** [comment]
<img width="951" alt="Ảnh chụp Màn hình 2023-09-05 lúc 07 50 31" src="https://github.com/BenCodez/VotingPlugin/assets/142149960/361c21f8-bb06-4655-ad2f-3c82f95c026c">

**Comment by BenCodez** [comment]
Disable the globaldata or enable usemainmysql

**Comment by hiiamken** [comment]
<img width="1054" alt="Ảnh chụp Màn hình 2023-09-05 lúc 08 00 41" src="https://github.com/BenCodez/VotingPlugin/assets/142149960/54734ab1-d6db-431d-88e2-35ae3054cee1">
<img width="358" alt="Ảnh chụp Màn hình 2023-09-05 lúc 08 01 09" src="https://github.com/BenCodez/VotingPlugin/assets/142149960/53252447-c3f0-4f48-9b07-d4339473fce9">

**Comment by BenCodez** [comment]
you'll have to restart

**Comment by hiiamken** [comment]
I have already restarted after changing the config

**Comment by BenCodez** [comment]
disable use mainmysql

**Comment by hiiamken** [comment]
<img width="1063" alt="Ảnh chụp Màn hình 2023-09-05 lúc 08 03 24" src="https://github.com/BenCodez/VotingPlugin/assets/142149960/a8f690d9-4bfc-4599-825e-cc99ec95ad30">

**Comment by BenCodez** [comment]
restart and send startup log

**Comment by hiiamken** [comment]
I voted but didn't receive anything on the Sky server, and there was no notification either

**Comment by BenCodez** [comment]
restart and send startup log

**Comment by hiiamken** [comment]
<img width="1045" alt="Ảnh chụp Màn hình 2023-09-05 lúc 08 05 04" src="https://github.com/BenCodez/VotingPlugin/assets/142149960/2f320af1-2325-465c-994f-e2558e6205f0">

**Comment by BenCodez** [comment]
send your startup log in pastebin or something

**Comment by hiiamken** [comment]
https://mclo.gs/wWt3DgO

**Comment by hiiamken** [comment]
<img width="1054" alt="Ảnh chụp Màn hình 2023-09-05 lúc 08 09 53" src="https://github.com/BenCodez/VotingPlugin/assets/142149960/d12feb2a-abca-4a8c-a6a5-b803c771cffd">

**Comment by BenCodez** [comment]
Looks like it's working? Also double check your up to date on bungee

**Comment by hiiamken** [comment]
It seems to be working now. Thank you for your assistance.
