### ISSUE TITLE
I want my voters to get a 'vote token' every vote and also have a 10% chance to receive a vote key with each vote, is this the correct configuartion for that? Thank you 

### ISSUE THREAD

**Issue by Riddimmmm** [Ben12345rocks/VotingPlugin#1300]
![sasasas](https://github.com/BenCodez/VotingPlugin/assets/144453548/acabe820-7c6c-485c-8f6a-4f0c99c01814)

**Comment by BenCodez** [comment]
Rewards:
      Commands:
      - key command here
      Rewards:
        Chance: 10
        Commands:
        - 10percentcommand

Try this

**Comment by Riddimmmm** [comment]
> ```
> Rewards:
>   Commands:
>   - key command here
>   Rewards:
>     Chance: 10
>     Commands:
>     - 10percentcommand
> ```
> 
> Try this

Is this instead of the 'Specialchance:' section? Thank you

**Comment by BenCodez** [comment]
You can put that in the votesites rewards spot

**Comment by Riddimmmm** [comment]
> You can put that in the votesites rewards spot

Sorry, where is the 'votesites rewards spot'? This is my rewards folder configs btw. thanks for the fast response

**Comment by BenCodez** [comment]
VoteSites.yml

**Comment by Riddimmmm** [comment]
> VoteSites.yml

![image](https://github.com/BenCodez/VotingPlugin/assets/144453548/1b524f6c-57ad-4c81-a0df-f0ef153a2adb)

But i have this at the bottom of that file which links to the rewards.yml file where the rewards are listed, so you are saying to replace the 'EverySiteReward: Rewards' line?

**Comment by BenCodez** [comment]
you mean you can just copy/paste what I have in the rewards file, it's easier to avoid that, but that might be easier

**Comment by Riddimmmm** [comment]
> you mean you can just copy/paste what I have in the rewards file, it's easier to avoid that, but that might be easier

Ok, but then how would i add the broastcast message to this? You didnt include that and its a different format to what i have used. Thank you

**Comment by BenCodez** [comment]
Commands:
    - key command here
    Messages:
      Broadcast: 'message'
    Rewards:
      Chance: 10
      Commands:
      - 10percentcommand

**Comment by Riddimmmm** [comment]
> ```
> Commands:
> - key command here
> Messages:
>   Broadcast: 'message'
> Rewards:
>   Chance: 10
>   Commands:
>   - 10percentcommand
> ```

And for the 10% reward? Sorry for all the questions i am still learning. Thank you!

**Comment by BenCodez** [comment]
That's in there, the last part.

**Comment by Riddimmmm** [comment]
I mean the broadcat message for the 10% reward. Sorry

**Comment by BenCodez** [comment]
Commands:
    - key command here
    Messages:
      Broadcast: 'message'
    Rewards:
      Chance: 10
      Messages:
        Broadcast: 'message'
      Commands:
      - 10percentcommand

**Comment by Riddimmmm** [comment]
> ```
> Commands:
> - key command here
> Messages:
>   Broadcast: 'message'
> Rewards:
>   Chance: 10
>   Messages:
>     Broadcast: 'message'
>   Commands:
>   - 10percentcommand
> ```

I thought so. Thank you

**Comment by Riddimmmm** [comment]
> ```
> Commands:
> - key command here
> Messages:
>   Broadcast: 'message'
> Rewards:
>   Chance: 10
>   Messages:
>     Broadcast: 'message'
>   Commands:
>   - 10percentcommand
> ```

One final question. Do the broastcasts support hex codes? Thanks

**Comment by BenCodez** [comment]
I think so
