### ISSUE TITLE
milestones issue

### ISSUE THREAD

**Issue by hiiamken** [Ben12345rocks/VotingPlugin#1305]
**Versions**
VotingPlugin 6.14.1

**Relevant information**
[Configs that relate to the issue in a pastebin.](https://controlc.com/42998727)

**Context**
I have a question about the milestone total votes I configured as in the file I sent. It includes milestones at 50/100/150/200... but when a player reaches 100 votes, they still only receive rewards at the 50-vote milestone instead of the 100-vote milestone. I want them to receive rewards at the 100-vote milestone when they reach 100 votes. How can I do that?

**Comment by BenCodez** [comment]
I don't see any milestones configured

**Comment by hiiamken** [comment]
Sr i meant Cumulative not Milestone

**Comment by hiiamken** [comment]
Fix!

**Comment by hiiamken** [comment]
Fix!

**Comment by BenCodez** [comment]
Did you solve this?

**Comment by hiiamken** [comment]
Yes tks a lots
