### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by hiiamken** [Ben12345rocks/VotingPlugin#1306]
[Configs that relate to the issue in a pastebin.](https://controlc.com/5ea0eb5f)

I want to create vote milestones like 50, 100, 150, but players can only receive rewards once.
For example, when a player reaches 100 votes, they will only receive the reward at the 100-vote milestone.
According to the config I am using, when a player reaches 100 votes, they will also receive the rewards for the 50-vote milestone.

![image](https://github.com/BenCodez/VotingPlugin/assets/142149960/179f4876-92a8-49db-8dd7-e3ea3d28bbfd)

**Comment by BenCodez** [comment]
I think that is set correctly. Does that happen to everybody?

**Comment by hiiamken** [comment]
> I think that is set correctly. Does that happen to everybody?

Yes, how can i fix it

**Comment by BenCodez** [comment]
Are you on the latest version? What are players milestonecount set to? Did you just enable these milestones?

**Comment by hiiamken** [comment]
I only want to receive the singular reward corresponding to the achieved milestone and do not wish to receive rewards already received at previous milestones

**Comment by hiiamken** [comment]
Yes i used lastest

**Comment by BenCodez** [comment]
What are players milestonecount set to? 

Did you just enable these milestones?

**Comment by hiiamken** [comment]
You can check in the config file I've sent. I don't quite understand which part you're referring to

**Comment by BenCodez** [comment]
Milestones work off a milestonecount which can be different that alltimetotal, use /av user (player) viewdata

How long ago did you enable the milestones?

**Comment by hiiamken** [comment]
I've just edited the milestone section, so I think players who had voting data from before (before enabling the milestone feature) can receive their rewards once I enable it."

**Comment by BenCodez** [comment]
that's what I'm thinking

**Comment by hiiamken** [comment]
1 player on my server is reporting that when he reach milestone 150, he still receive rewards for milestones 50 and 100. However, when he reach milestone 200, he still receive rewards for milestones 50, 100, and 150

**Comment by BenCodez** [comment]
set debuglevel to EXTRA and send the logs when you recreate the problem

**Comment by hiiamken** [comment]
Okay

**Comment by hiiamken** [comment]
![image](https://github.com/BenCodez/VotingPlugin/assets/142149960/048b37b8-1d5a-43fa-9329-2faa894ba989)
The issue is that players' milestones do not increase after they vote. How can this issue be fixed?
