### ISSUE TITLE
How offline get reward 

### ISSUE THREAD

**Issue by hiiamken** [Ben12345rocks/VotingPlugin#1309]
**Relevant information**
[Configs that relate to the issue in a pastebin.](https://controlc.com/ac80621b)

**Context**
How can I set up offline players to vote, but they will receive rewards when they enter the game? I've been searching the wiki for hours and haven't been able to do that

**Comment by BenCodez** [comment]
It's enabled by default to do that

**Comment by hiiamken** [comment]
But on my server, I can't do it; I need to find where to turn it on/off

**Comment by BenCodez** [comment]
I need more information on what isn't working exactly

**Comment by hiiamken** [comment]
I vote when I'm offline, and after entering the server, I want to announce the vote in the server lobby instead of the server backend. How can I configure it so that I receive rewards when I enter the server of my choice? For example, I have two servers, 'sur' and 'sky.' Some players want their rewards on 'sur,' and others want their rewards on 'sky.' How can I configure it so that when a player enters the lobby and selects a server, that server will provide rewards to the player?

**Comment by hiiamken** [comment]
https://youtu.be/Jiy8cHueYQA

**Comment by BenCodez** [comment]
send all your configs

**Comment by hiiamken** [comment]
Bungee:
- bungeeconfig.yml: https://controlc.com/af2fadd1

Lobby:
- bungeesettings.yml: https://controlc.com/988b7a81
- config.yml: https://controlc.com/64111189
- votesite.yml: https://controlc.com/e59728a4

Backend Server:
- bungeesettings.yml: https://controlc.com/70024f30
- config.yml: https://controlc.com/91b0f380
- votesite.yml: https://controlc.com/ad176e80

**Comment by hiiamken** [comment]
> I vote when I'm offline, and after entering the server, I want to announce the vote in the server lobby instead of the server backend. How can I configure it so that I receive rewards when I enter the server of my choice? For example, I have two servers, 'sur' and 'sky.' Some players want their rewards on 'sur,' and others want their rewards on 'sky.' How can I configure it so that when a player enters the lobby and selects a server, that server will provide rewards to the player?

I misspoke a bit. What I meant is that I want the players to receive the rewards on the backend server instead of the lobby server

**Comment by BenCodez** [comment]
Add lobby to the blockedservers list

**Comment by hiiamken** [comment]
Is there a way to increase the vote party on different servers when players vote offline?
