### ISSUE TITLE
Seperate data MySQL

### ISSUE THREAD

**Issue by hiiamken** [Ben12345rocks/VotingPlugin#1310]
How to share player data across different servers while still utilizing a single MySQL database? For example, I have 2 servers, A and B, within a Bungee server. However, I want separate data for each server. When a player votes and joins a server, the voting data on that server should be updated accordingly.

If it's not feasible to use a single MySQL database, how should I set up Bungee to utilize 2 MySQL databases?

**Comment by BenCodez** [comment]
Follow this guide: https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING

**Comment by hiiamken** [comment]
I've followed this guide from the beginning, but the vote count on both servers increases when players vote. How can I make the player count only increase in one specific server when they join for the first time (after joining the lobby and selecting that server)?

**Comment by hiiamken** [comment]
Here is my config: 

Bungee:

bungeeconfig.yml: https://controlc.com/af2fadd1
Lobby:

bungeesettings.yml: https://controlc.com/988b7a81
config.yml: https://controlc.com/64111189
votesite.yml: https://controlc.com/e59728a4
Backend Server:

bungeesettings.yml: https://controlc.com/70024f30
config.yml: https://controlc.com/91b0f380
votesite.yml: https://controlc.com/ad176e80

**Comment by hiiamken** [comment]
Survival Server :
![image](https://github.com/BenCodez/VotingPlugin/assets/142149960/5661e0ec-3570-4def-a5f6-8b63da6d9fb1)

![image](https://github.com/BenCodez/VotingPlugin/assets/142149960/9c81dd2f-8e67-4a53-acb6-188044700fd5)

This is my config of deluxemenu

**Comment by hiiamken** [comment]
Skyblock Server:
![image](https://github.com/BenCodez/VotingPlugin/assets/142149960/47861d81-6523-487a-b82e-ca8afe9d554c)

Config deluxemenu same as Survival Server

**Comment by hiiamken** [comment]
How can I make sure that 2 servers have different player vote data? Occasionally, the vote milestones also fail to trigger when a player reaches a milestone that I configured beforehand in the config

My special rewards config: https://controlc.com/428c1764

**Comment by BenCodez** [comment]
That bungee setup keeps the data in sync with all servers. If you want like per server points or something there are options for that

**Comment by hiiamken** [comment]
What option, please tell me

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/Resources/BungeeSettings.yml#L49

**Comment by hiiamken** [comment]
Is there any way to reset all players' milestone data to 0 at the beginning of a new month without deleting the database? I want the milestones to reset to the beginning every month so that players can vote again from the start.

**Comment by hiiamken** [comment]
I am having an issue where players, upon reaching a milestone like 150 votes for instance, are claiming rewards for both the 50 and 100-vote milestones. How can I set it up so that players only receive rewards for one milestone?
![image](https://github.com/BenCodez/VotingPlugin/assets/142149960/2784bd35-d8c3-45c5-982a-09965bfc3edb)

**Comment by BenCodez** [comment]
> Is there any way to reset all players' milestone data to 0 at the beginning of a new month without deleting the database? I want the milestones to reset to the beginning every month so that players can vote again from the start.

Option for that in SpecialRewards.yml



> I am having an issue where players, upon reaching a milestone like 150 votes for instance, are claiming rewards for both the 50 and 100-vote milestones. How can I set it up so that players only receive rewards for one milestone? ![image](https://user-images.githubusercontent.com/142149960/279131020-2784bd35-d8c3-45c5-982a-09965bfc3edb.png)

Should only give once, check that they didn't get it before?

**Comment by hiiamken** [comment]
I just set the PerServerMilestones to false. It was previously set to true. Is that a feature that I need to adjust?

**Comment by hiiamken** [comment]
I have two question
1. Will ResetMonthlyMilestone take place at the end of the current month or at the beginning of the next month? Specifically, what time will this occur?
2. Is there any command to manually reset player data within the game? I have used both /avResetMilestoneCount and /avResetPoints, but none of them worked.

**Comment by hiiamken** [comment]
![image](https://github.com/BenCodez/VotingPlugin/assets/142149960/85c4b42b-2ede-4e6a-82c2-a6524469586b)
Currently, it is 11:00 PM on October 31st in my local time, but I haven't seen any changes in the data. Does the milestone data reset here also require resetting the total vote count, or will the votes remain the same, with the milestones recalculated from the beginning?

**Comment by BenCodez** [comment]
> I just set the PerServerMilestones to false. It was previously set to true. Is that a feature that I need to adjust?

Depends on what you want



> I have two question
> 
> 1. Will ResetMonthlyMilestone take place at the end of the current month or at the beginning of the next month? Specifically, what time will this occur?
> 2. Is there any command to manually reset player data within the game? I have used both /avResetMilestoneCount and /avResetPoints, but none of them worked.

1. Beginning of the month, based on server time
2. What are you trying to reset?

**Comment by hiiamken** [comment]
I want the players to compete for the top votes in each category, and the rewards will be distributed to the top 1, 2, and 3.

**Comment by BenCodez** [comment]
> I want the players to compete for the top votes in each category, and the rewards will be distributed to the top 1, 2, and 3.

What do you mean by that exactly?
