### ISSUE TITLE
Save TopVoters in database instead of local yaml file.

### ISSUE THREAD

**Issue by ChimpGamer** [Ben12345rocks/VotingPlugin#1313]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to access the topvoters list from previous months outside of the servers. I want to be able to display it on a website but with the current situation that is not possible.

**Describe the solution you'd like**
Save the TopVoters in the database instead of local yaml file.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by BenCodez** [comment]
I like the idea, just wondering how the data should be stored exactly. Would a separate table work better?

**Comment by ChimpGamer** [comment]
I guess just a table with the month-year, type ( alltime, monthly ), position, playername/uuid and their votes.

**Comment by BenCodez** [comment]
I'll have to see exactly how I want to do it, but I'll look at adding something

**Comment by BenCodez** [comment]
Are you still interested in something like this?

**Comment by ChimpGamer** [comment]
Absolutely!

**Comment by BenCodez** [comment]
Is one database for all topvoter information good for you? Having columns like MARCH_2024, lastmonth and currentmonth for example a good way to handle it or you got something else in mind?

**Comment by ChimpGamer** [comment]
You sure you mean one database not one table? I don't have a specific idea about how to store it in the database. But I wouldn't add a new column every month.

**Comment by BenCodez** [comment]
Yeah one table, not sure why I put database. I'll look into adding something soon. Feel free to remind me if I don't get back to you soon

**Comment by ChimpGamer** [comment]
Alright Thanks. Also you said storing currentmonth as well but that data is already available using the VotingPlugin_Users table.

**Comment by BenCodez** [comment]
well lastmonth is available as well

**Comment by BenCodez** [comment]
I just don't store current top voter position, so if you really wanted you could just use the current VotingPlugin_Users

**Comment by ChimpGamer** [comment]
Oh damn. I didn't noticed that lol.

**Comment by BenCodez** [comment]
Does that work for your current needs?

**Comment by ChimpGamer** [comment]
It does. Thanks!

**Comment by BenCodez** [comment]
Alright then, I'll close this then since it's not needed.
