### ISSUE TITLE
duplication glitch

### ISSUE THREAD

**Issue by Ogmur** [Ben12345rocks/VotingPlugin#1314]
**Versions**
[6.14.2](https://www.spigotmc.org/resources/votingplugin.15358/update?update=523704)

This server is running Pufferfish+ version git-PufferfishPlus-21 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a9f972b on HEAD)

**Describe the bug**
item duplication

**To Reproduce**
1. Using UI Utils by Coderx-Gamer
2. Desync GUI
3. put item in GUI
4. save GUI
5. close GUI w/o packet
6. reopen saved GUI take item out
7. send packets
8. items duped

**Expected behavior**
item duplication

**Additional context**
the fix would be to make all empty inventory slots within each GUI, /vote, /votetop, /votebest, /voteall, a glass pane, this way there isn't any free slots to put the items into thus preventing the dupe.

**Comment by Ogmur** [comment]
The steps for duping may not match exactly because it was reported to me by a player on my server who has been duping items, but the dupe DEFINITELY works and the fix to prevent the dupe would work to stop it. Maybe add it as an optional config as 

EmptySpaces: air 
EmptySpaces: glass_pane

something like that if possible please

**Comment by BenCodez** [comment]
It's already possible to add extra items to the gui, check gui.yml, you can
do that until I find a good fix for it

**Comment by Ogmur** [comment]
Would you be able to add me on discord at "Ogmur"? I've got more info as to what causes the dupe and if you'd be able to maybe help me with the GUI.yml as I don't see where I can fill in the empty slots in the .yml, would be greatly appreciated! Thank you

**Comment by BenCodez** [comment]
You can join my discord server and create a ticket, won't be able to
respond for a while though

**Comment by Ogmur** [comment]
I've figured it out but it creates a new line

![image](https://github.com/BenCodez/VotingPlugin/assets/88465615/d0a133c7-af7a-43e8-990f-a24cdf4604b9)

there shouldn't seem to be a way to disable it creating new line automatically once its filled up?

**Comment by BenCodez** [comment]
Use the fillemptyslots option, you can see it on the wiki, not on my
computer right now

**Comment by Ogmur** [comment]
![image](https://github.com/BenCodez/VotingPlugin/assets/88465615/7f8d6ad8-5e4d-42d0-bac2-e3f4bdfbace1)


awesome, this has fixed it! this can be closed since the features are already within the plugin to prevent the problem. thanks for your help!
