### ISSUE TITLE
/votetogglereminders not persisting. 

### ISSUE THREAD

**Issue by Castiella** [Ben12345rocks/VotingPlugin#1316]
**Versions**
version 6.14.2
git-Paper-292 (MC: 1.20.2)

**Describe the bug**
/votetogglereminders does not persist.  When the server restarts ect the reminders come back. It is incredibly frustrating for players to need to type this every time they log in.

**To Reproduce**
Type, /votetogglereminders and restart the server.

**Expected behavior**
For reminders to actually toggle.

**Screenshots/Configs**
NA

**Additional context**
Thank you!

**Comment by BenCodez** [comment]
I'll look at making it save the state across restarts when I get a chance.

**Comment by BenCodez** [comment]
Does this work? https://bencodez.com/job/VotingPlugin/
