### ISSUE TITLE
Voteparty Reminder

### ISSUE THREAD

**Issue by SladeHazard** [Ben12345rocks/VotingPlugin#1317]
Hey, would you consider adding a feature where the voteparty broadcasts itself in chat before starting & a message that's also sent to people who did not vote to be able to participate in the voteparty, so they know they have to vote for the next time

Example:
![image](https://github.com/BenCodez/VotingPlugin/assets/45261094/68e603e5-b6f9-47ec-98dc-d45bbae3f816)

**Comment by BenCodez** [comment]
Only problem with that is just the way my voteparty works compared to other plugins. There isn't an easy way to add a warning like that. You can do this though: https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/Resources/SpecialRewards.yml#L99
