### ISSUE TITLE
Milestone issue

### ISSUE THREAD

**Issue by hiiamken** [Ben12345rocks/VotingPlugin#1319]
**Versions**
 6.14.2, Purpur 1.20.1

**Relevant information**
[Configs that relate to the issue in a pastebin.](https://controlc.com/73fdea25)

**Context**
I am encountering an issue with milestones where players do not receive rewards specified in the 'specialrewards.yml' configuration when they reach the milestone. I have set the milestone reset on a monthly basis, and the reset functionality is working fine. However, when players reach the set milestone, nothing happens

**Comment by hiiamken** [comment]
BungeeSetting.yml
https://controlc.com/2a7380d7

**Comment by hiiamken** [comment]
config.yml
https://controlc.com/ecc7af48

**Comment by hiiamken** [comment]
For those who have not received milestone rewards before, they still receive them. However, for those who receive rewards for the second time (from the second month onward), they do not receive anything.

**Comment by BenCodez** [comment]
Did the month data not reset?

**Comment by hiiamken** [comment]
I have reset the milestone data every month

**Comment by hiiamken** [comment]
and the placeholder has also been reset

**Comment by hiiamken** [comment]
The placeholder is currently 0, but when it increases to a level like 25, the player does not receive anything

**Comment by BenCodez** [comment]
What placeholder?

**Comment by hiiamken** [comment]
![image](https://github.com/BenCodez/VotingPlugin/assets/142149960/bf00e712-ff31-45aa-8a18-eb4d7eae4b0b)

**Comment by hiiamken** [comment]
I saw it resets to 0 at the start of a new month so I think I configured it correctly

**Comment by BenCodez** [comment]
Set debuglevel to EXTRA and send the logs when players should be getting the milestone and don't

**Comment by hiiamken** [comment]
okay

**Comment by hiiamken** [comment]
Last month, there were people who received it, but as of this December, I haven't seen anyone say they received a reward from the milestone.

**Comment by hiiamken** [comment]
I have to give them a manual reward, so maybe when someone has an error, I will send you the log

**Comment by hiiamken** [comment]
https://controlc.com/048c6b95
Here is th log, when i reached milestone of 25

**Comment by hiiamken** [comment]
![image](https://github.com/BenCodez/VotingPlugin/assets/142149960/0453a206-4798-45ad-830f-628a637f03ca)

**Comment by hiiamken** [comment]
![image](https://github.com/BenCodez/VotingPlugin/assets/142149960/71ed3d0f-3d26-49be-8fbd-66aa6cf2b0f1)
Here is my data

**Comment by hiiamken** [comment]
![image](https://github.com/BenCodez/VotingPlugin/assets/142149960/5543e81a-0f81-4619-9ed6-f4f532cf78ea)

**Comment by hiiamken** [comment]
https://controlc.com/4102ce9b

This is a player who reached the 50 mark and received a reward

**Comment by BenCodez** [comment]
Not sure what's going on exactly. This is just for everyone that got the milestones last month that are not getting it now? Does the player data show they already got it (before reaching the gotten milestones)?

**Comment by hiiamken** [comment]
It seems that players who have been playing for 2 to 3 months report not receiving milestone votes since the second time. Meanwhile, those who are new this month are still receiving votes as usual

**Comment by BenCodez** [comment]
Think I found the issue, this should fix it for future versions: https://bencodez.com/job/VotingPlugin/

To fix it now you can try: /av ResyncMilestonesAlreadyGiven

Backup your data before running the command just incase. Also will have to do it for each server.

**Comment by hiiamken** [comment]
How to backup, iam using mysql in bungee

**Comment by hiiamken** [comment]
Can you explain more about this comand resync, i dont quite understand of its feature

**Comment by BenCodez** [comment]
> How to backup, iam using mysql in bungee

mysql dump is one way



> Can you explain more about this comand resync, i dont quite understand of its feature

Just sets what milestones a player should and shouldn't have.

**Comment by hiiamken** [comment]
Just use /av ResyncMilestonesAlreadyGiven right?

**Comment by BenCodez** [comment]
yes

**Comment by hiiamken** [comment]
![image](https://github.com/BenCodez/VotingPlugin/assets/142149960/4b72b98f-bc99-4f22-8fec-80ef9cd3108a)
is that corect?

**Comment by BenCodez** [comment]
yes

**Comment by hiiamken** [comment]
When will you release the new version?

**Comment by BenCodez** [comment]
Aiming before new year, but not sure

**Comment by hiiamken** [comment]
Do I need to download the dev version you sent above?

**Comment by hiiamken** [comment]
Maybe I'll wait until the official version comes out, hopefully this month

**Comment by BenCodez** [comment]
Would fix it for now, doesn't matter until end of the month anyway

**Comment by hiiamken** [comment]
Okay then I will close this post. Have a nice day, I will rate 5 stars for the plugin and your support
This must be the 5th or 6th time I've created an issue, sorry for the inconvenience
