### ISSUE TITLE
Vote shop confirm

### ISSUE THREAD

**Issue by Snowmansir** [Ben12345rocks/VotingPlugin#1320]
**Versions**
VotingPlugin 6.14.2
Current: git-Purpur-2087 (MC: 1.20.2)*

**Describe the bug**
"/vote shop" confirm doesn't close when clicking no.

**To Reproduce**
1 /vote shop
2 click default item. (diamond)
3 click no.
4 ???

**Expected behavior**
Expected to either close chest UI or return back to /vote shop

**Screenshots/Configs**
![image](https://github.com/BenCodez/VotingPlugin/assets/108475475/fcfb48de-b460-4df8-8813-41a5d91c6f5e)

Notes:
When spam clicking it does close, but this can't be expected behaviour.

**Comment by BenCodez** [comment]
Wanna send your GUI.yml? Should also be able to add CloseGUI: true within the item config section for voteshop confirm.

**Comment by Snowmansir** [comment]
> Wanna send your GUI.yml? Should also be able to add CloseGUI: true within the item config section for voteshop confirm.

https://pastebin.com/7xfC8vve
I did add closegui true to both instances. Maybe I'm missing something else.

**Comment by BenCodez** [comment]
Try adding it under yes item and no item sections?

**Comment by Snowmansir** [comment]
> Try adding it under yes item and no item sections?>

Yep, that did the trick! 
Thanks!
