### ISSUE TITLE
Votes recognized in logs but did not give rewards for 1 player

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [Ben12345rocks/VotingPlugin#1321]
Firstly, thank you for maintaining this plugin for so long!

**Versions**
git-Paper-318 (MC: 1.20.2)
VotingPlugin: 6.14.1

**Describe the bug**
A player voted on 2 separate accounts ("zapara" & "zaparaa") using 2 separate IPs. According to server logs the votes were recognized on both accounts and Zapara was rewarded but Zapara**a** was not. It didn't even attempt to reward Zapara**a**. 

**To Reproduce**
1. Vote on 2 accounts using 2 separate IPs while offline.
2. Then login to the server.
However, not confident it will be possible to reproduce as I've voted on 2 accounts before and did not encounter this issue. Mind you, I wasn't trying to reproduce the issue. 

**Screenshots/Configs**
For the latest.log below keyword search for the following line then look further down for the other portions where it rewards Zapara with a diamond but not Zaparaa (rewards should occur when logging in):
[13:21:42] [Votifier epoll worker/INFO]: [Votifier] Got a protocol v1 vote record from /54.37.31.166:47742 -> Vote (from:Minecraft-MP.com username:Zaparaa address:87.49.147.179 timeStamp:1702560102 additionalData:null)

latest.log: https://hastebin.skyra.pw/oxugaxovex.yaml

**Comment by BenCodez** [comment]
set debuglevel to EXTRA and send the log with both of those players voting

**Comment by PiggiesGoSqueal** [comment]
Hm I did that and then he tested today and said it worked properly so idk. I'm guessing it was a misunderstanding regarding rewards being given every 3 votes. Thanks for the feedback though.
