### ISSUE TITLE
Testing plugin that hooks into API for events

### ISSUE THREAD

**Issue by mallusrgreatv2** [Ben12345rocks/VotingPlugin#1323]
How can I test my plugin? Is there something like a test vote / fake vote command that I can use? One that triggers PlayerVoteEvent?

**Comment by BenCodez** [comment]
./av vote (player) (site) will trigger it

**Comment by mallusrgreatv2** [comment]
Is there a way in the proxy?

**Comment by mallusrgreatv2** [comment]
Found it - `votingpluginbungee vote`
