### ISSUE TITLE
Conflict on 1.12 of VotingPlugin and NuVotifier

### ISSUE THREAD

**Issue by Skryptio** [Ben12345rocks/VotingPlugin#1326]
**Versions**
1.12 and v2.2 votingplugin, why? Because it looks way nicer and the older versions are absolutely not compatible with my server. Why do I use 1.12 because I do.

**Describe the bug**
When I receive a vote, rewards don't get given out and I get the error down here.

**To Reproduce**
1. Install VotingPlugin
3. Restart the server
5. Vote on a votesite
6. See error

**Expected behavior**
1. Install VotingPlugin
3. Restart the server
5. Vote on a votesite
6. Get rewards

**Screenshots/Configs**
Error:
03.01 14:38:12 [Server] Server thread/[ERROR] Could not pass event VotifierEvent to VotingPlugin 
03.01 14:38:12 [Server] [INFO] org.bukkit.event.EventException: null
03.01 14:38:12 [Server] [INFO] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1620]
03.01 14:38:12 [Server] [INFO] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1620]
03.01 14:38:12 [Server] [INFO] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
03.01 14:38:12 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
03.01 14:38:12 [Server] [INFO] at com.vexsoftware.votifier.NuVotifierBukkit.fireVotifierEvent(NuVotifierBukkit.java:372) ~[?:?]
03.01 14:38:12 [Server] [INFO] at com.vexsoftware.votifier.NuVotifierBukkit.lambda$onVoteReceived$1(NuVotifierBukkit.java:341) ~[?:?]
03.01 14:38:12 [Server] [INFO] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1620]
03.01 14:38:12 [Server] [INFO] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
03.01 14:38:12 [Server] [INFO] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1620]
03.01 14:38:12 [Server] [INFO] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
03.01 14:38:12 [Server] [INFO] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
03.01 14:38:12 [Server] [INFO] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
03.01 14:38:12 [Server] [INFO] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
03.01 14:38:12 [Server] [INFO] Caused by: java.lang.NullPointerException
03.01 14:38:12 [Server] [INFO] at com.Ben12345rocks.VotingPlugin.Config.ConfigVoteSites.getVoteSites(ConfigVoteSites.java:76) ~[?:?]
03.01 14:38:12 [Server] [INFO] at com.Ben12345rocks.VotingPlugin.API.VoteUtils.getVoteSiteName(VoteUtils.java:47) ~[?:?]
03.01 14:38:12 [Server] [INFO] at com.Ben12345rocks.VotingPlugin.API.VoteRecieved.playerVote(VoteRecieved.java:39) ~[?:?]
03.01 14:38:12 [Server] [INFO] at com.Ben12345rocks.VotingPlugin.Events.VotiferEvent.onVotiferEvent(VotiferEvent.java:53) ~[?:?]
03.01 14:38:16 [Server] [INFO] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor126.execute(Unknown Source) ~[?:?]
03.01 14:38:16 [Server] [INFO] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1620]
03.01 14:38:16 [Server] [INFO] ... 12 more

This is my config:

# VoteSites.yml
# Add your voting sites here
# Default:
#VoteSites:
#  # SiteName (Can be anything, just don't have 2 the same name)
#  # name is used in most formating
#  PMC:
#    # The serviceName from the vote, has to be correct to work correctly
#    # Gotten from voting on the site (will be in console/log)
#    Site: 'PlanetMinecraft.com'
#    # vote url for /vote
#    # colors can be set in Format.yml
#    VoteURL: 'link to vote URL here, used in /vote'
#    # Time between votes in hours (used for /vote next)
#    # Most sites are 24 hours
#    votedelay: 24
#    # money given on vote, use 0 for none
#    # Requires Vault
#    Money: 500
#    # items
#    Items:
#      # item (can be anything, just don't have 2 the same)
#      Diamond:
#        id: 264
#        # item data
#        Data: 0
#        # item amount
#        Amount: 1
#        # name
#        # Set to '' (that's 2 ') for no name, e.g Name: ''
#        Name: '&4Example'
#        # lore
#        Lore:
#        - '&4Line 1'
#    # Commands to run on vote (when player is online)
#    # use %player% for the player's name
#    Commands:
#      # Console commands
#      # Set to Console: '' to run no commands
#      Console:
#      - 'say Example command: %player%'
#      # Player commands
#      # Set to Player: '' to run no commands
#      # Player needs permissions to run commands
#      Player:
#      - 'vote total'
      
VoteSites:
  TMS:
    Site: 'TopMinecraftServers'
    VoteURL: 'https://topminecraftservers.org/vote/36257'
    votedelay: 24
    Money: 2000
   Items:
     # item (can be anything, just don't have 2 the same)
     Diamond:
       id: 264
       # item data
       Data: 0
       # item amount
       Amount: 1
       # name
       # Set to '' (that's 2 ') for no name, e.g Name: ''
       Name: '&4Diamond of Honer'
       # lore
       Lore:
       - '&4Selling this will haunt you'
    Commands:
      Console:
      - 'say &a&lThanks to &e&l%player% &a&lfor voting!'
      - 'crate give p VoteCrate 1 %player%'
      Player:
      - 'vote total'

**Additional context**

**Comment by BenCodez** [comment]
Latest version of votingplugin supports 1.12 (unless an update broke it). Why are you using a really old version of VotingPlugin?
