### ISSUE TITLE
inter-server voting milestone

### ISSUE THREAD

**Issue by hiiamken** [Ben12345rocks/VotingPlugin#1329]
**Versions**
Lastest + 1.20.1 Paper

**Relevant information**
Configs that relate to the issue in a pastebin.

**Context**
Currently, my server is having a problem: when a player receives a milestone on one server, when they go to another server, they still receive the reward from that server's milestone. How can players only receive rewards from one server instead of all servers?

**Comment by BenCodez** [comment]
Are you using a votingplugin proxy setup?

**Comment by hiiamken** [comment]
Yes

**Comment by hiiamken** [comment]
Do you need me to provide any config file?

**Comment by BenCodez** [comment]
yep

**Comment by hiiamken** [comment]
which file

**Comment by BenCodez** [comment]
bungeeconfig.yml, bungeesettings.yml

**Comment by hiiamken** [comment]
https://controlc.com/a0925af0
bungeeconfig

**Comment by hiiamken** [comment]
https://controlc.com/478575a7
bungeesetting

**Comment by hiiamken** [comment]
![image](https://github.com/BenCodez/VotingPlugin/assets/142149960/14c07e44-372d-4fc5-a1fc-4bf7ebc976aa)
![image](https://github.com/BenCodez/VotingPlugin/assets/142149960/467b5513-07cb-45b4-b197-dff5aab1cb07)
Can I delete these 2 parts?

**Comment by BenCodez** [comment]
you need the server line at the top, rest you can delete. Disable perserver milstones

**Comment by hiiamken** [comment]
"Disable perserver milstones" in where

**Comment by hiiamken** [comment]
Can you edit those 2 config files for me, I don't know how to delete them

**Comment by BenCodez** [comment]
> "Disable perserver milstones" in where

BungeeSettings.yml



> Can you edit those 2 config files for me, I don't know how to delete them

I'd just leave it then, no hard to have it there right now

**Comment by hiiamken** [comment]
That means I don't need to delete it, it won't affect anything, right?

**Comment by BenCodez** [comment]
yes
