### ISSUE TITLE
possible to execute the commands in both worlds?

### ISSUE THREAD

**Issue by Razorxd1993** [Ben12345rocks/VotingPlugin#1331]
Hi, is it possible to execute the commands in both worlds?

If I use this example, you can only get the rewards in world1, but not in world2 afterwards

      Worlds:
      - world1
      - world2

E.g. world1 is Skyblock and world2 is Factions, you should be able to get the rewards in both worlds and not have to choose in which of the two you can get the reward. (Separate inventories in the worlds)

Kind regards

Translated with DeepL.com (free version)

**Comment by BenCodez** [comment]
Either use 2 different rewards or use this: 

    AdvancedWorld:
      world:
        Commands:
        - say %player% in world
      world_nether:
        Commands:
        - say %player% in nether

**Comment by Razorxd1993** [comment]
Okay, thank you very much.
Can I just add this to the votesites.yml for each page?

**Comment by BenCodez** [comment]
yep

**Comment by Razorxd1993** [comment]
Okay, I have now tried this out:

https://pastebin.com/hrjjbNm5

Unfortunately, you only get one reward.
For example, if you first go to world1 you get the reward there and if you go to world2 you get none.

**Comment by BenCodez** [comment]
That should work, have you done restart since adding that?
