### ISSUE TITLE
PerWorldCheck?

### ISSUE THREAD

**Issue by Jende6** [Ben12345rocks/VotingPlugin#1333]
I have 2 worlds set where it should give the players the keys, but when i join the server and iam in the lobby world and go to the survival world it doesnt give me anything, and when i join the server into the survival world it gives me the keys

Is there some PerWorldCheck setting or something? if yes then where is it in the config.

**Comment by BenCodez** [comment]
Wanna try this build? https://bencodez.com/job/VotingPlugin/
