### ISSUE TITLE
Voting Sites dont show

### ISSUE THREAD

**Issue by vxkShelby** [Ben12345rocks/VotingPlugin#1334]
**Versions**
6.15

**Describe the bug**
i havent been on my server like 2 weeks .... now when am back voting sites dont show... i got his error : 
 ERROR] [VotingPlugin] Failed to load a file, check startup log
 i even downloaded newer plugin but nothings changed 

**Screenshots/Configs**
VoteSites:
  # VoteSite key
  # Used for saving data for votesites
  # Use a short name if you can
  # No spaces or dots
  MinecraftServers:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
    
    # Display name of voting site
    Name: MinecraftServers.org
    
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 1
    
    # If true, voteside will be hidden from some GUI's, similar to being disabled
    Hidden: false
    
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: minecraftservers.org
    
    # vote url for /vote
    # Format for this can be set in Config.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
    VoteURL: https://minecraftservers.org/vote/657805
    
    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 12
    
    # Use to have a minute votedelay
    # VoteDelayMin: 30

        # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    # Replaces offset, set the exact hour based on server time
    # Include server time offset when setting this
    # 2 = 2 am server time
    # Use 1-24
    # VoteDelayDailyHour: 14

        # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    
    # Reward to run when cooldown ends for this votesite
    # Enable PerSiteCoolDownEvents in Config.yml to use this
     CoolDownEndRewards:
      Messages:
        Player: '&aTime to go vote on site1'

        # Rewards to give
    # https://github.com/BenCodez/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
        Console:
        - lootcrate give %player% 749 1
      # Send player a message
      Messages:
        Player: You voted
  
  BestMinecraftServers:
    Enabled: true
    Name: BestMinecraftServers.com
    Priority: 2
    Hidden: false
    ServiceSite: best-minecraft-servers.co
    VoteURL: https://best-minecraft-servers.co/server-purecraft-smp.20812/vote
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      CoolDownEndRewards:
      Messages:
        Player: '&aTime to go vote on site2'
      Commands:
        Console:
        - lootcrate give %player% 749 1
      Messages:
        Player: You voted
  
  SKMinecraftServer:
    Enabled: true
    Name: MinecraftServer.SK
    Priority: 3
    Hidden: false
    ServiceSite: minecraftserver.sk
    VoteURL: https://www.minecraftserver.sk/server/purecraft-smp-862/
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      CoolDownEndRewards:
      Messages:
        Player: '&aTime to go vote on site3'
      Commands:
        Console:
        - lootcrate give %player% 749 1
      Messages:
        Player: You voted
  
  MinecraftServerList:
    Enabled: true
    Name: MinecraftServerList.com
    Priority: 4
    Hidden: false
    ServiceSite: minecraft-server-list.com
    VoteURL: https://minecraft-server-list.com/server/501190/vote/
    VoteDelay: 1
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      CoolDownEndRewards:
      Messages:
        Player: '&aTime to go vote on site4'
      Commands:
        Console:
        - lootcrate give %player% 749 1
      Messages:
        Player: You voted
  
  CraftList:
    Enabled: true
    Name: CraftList
    Priority: 5
    Hidden: false
    ServiceSite: craftlist.org
    VoteURL: https://craftlist.org/purecraft-smp
    VoteDelay: 2
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      CoolDownEndRewards:
      Messages:
        Player: '&aTime to go vote on site5'
      Commands:
        Console:
        - lootcrate give %player% 749 1
      Messages:
        Player: You voted
  
  PlanetMinecraft:
    Enabled: true
    Name: PlanetMinecraft
    Priority: 6
    Hidden: false
    ServiceSite: planetminecraft.com
    VoteURL: https://www.planetminecraft.com/server/purecraft-smp/vote/
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      CoolDownEndRewards:
      Messages:
        Player: '&aTime to go vote on site6'
      Commands:
        Console:
        - lootcrate give %player% 749 1
      Messages:
        Player: You voted
  
  CurseForge:
    Enabled: true
    Name: CurseForge
    Priority: 7
    Hidden: false
    ServiceSite: www.curseforge.com
    VoteURL: https://www.curseforge.com/servers/minecraft/game/purecraft-smp/vote
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      CoolDownEndRewards:
      Messages:
        Player: '&aTime to go vote on site7'
      Commands:
        Console:
        - lootcrate give %player% 749 1
      Messages:
        Player: You voted
        
    
    
    
    
    
    
    
    
    
        
  Best Minecraft Servers:
    Enabled: false
    ServiceSite: Best Minecraft Servers
    VoteURL: VoteURL
    VoteDelay: 24.0
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
    
  MinecraftServersList:
    Enabled: false
    ServiceSite: MinecraftServersList
    VoteURL: VoteURL
    VoteDelay: 24.0
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  MCSL:
    Enabled: false
    ServiceSite: MCSL
    VoteURL: VoteURL
    VoteDelay: 24.0
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'

# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
EverySiteReward: {}

**Comment by vxkShelby** [comment]
[16:28:19 INFO] [VotingPlugin] Loading server plugin VotingPlugin v6.15
[16:28:19 INFO] [VotingPlugin] Enabling VotingPlugin v6.15
[16:28:19 ERROR] [Minecraft] Cannot load plugins/VotingPlugin/VoteSites.yml
[16:28:19 ERROR] [Minecraft] Cannot load plugins/VotingPlugin/VoteSites.yml
[16:28:19 WARN] [VotingPlugin] Detected no voting sites, this may mean something isn't properly setup
[16:28:19 INFO] [VotingPlugin] Loaded LuckPerms hook!
[16:28:20 INFO] [PlaceholderAPI] Successfully registered internal expansion: votingplugin [1.6]
[16:28:20 INFO] [VotingPlugin] Loading PlaceholderAPI expansion
[16:28:21 INFO] [VotingPlugin] Giving VotingPlugin.Player permission by default, can be disabled in the config
[16:28:21 INFO] [VotingPlugin] Enabled VotingPlugin 6.15
[16:28:21 ERROR] [VotingPlugin] Failed to load a file, check startup log
[16:28:24 INFO] [VotingPlugin] Successfully hooked into vault economy!
[16:28:24 INFO] [VotingPlugin] Hooked into vault permissions
[16:28:29 INFO] [VotingPlugin] VotingPlugin is up to date! Version: 6.15

**Comment by BenCodez** [comment]
Send your file in pastebin.com

**Comment by vxkShelby** [comment]
https://pastebin.com/Pmwwd9n7

**Comment by BenCodez** [comment]
https://pastebin.com/JdUqiYXX try that

**Comment by vxkShelby** [comment]
working ... tnx .... where was a problem ?

**Comment by BenCodez** [comment]
One extra space in one spot, can always copy the file to https://yaml-online-parser.appspot.com/?url=http%3A%2F%2F and it will show you if the file will read properly

**Comment by vxkShelby** [comment]
Nice tnx ..
