### ISSUE TITLE
Bedrock offline voting

### ISSUE THREAD

**Issue by daniel-skopek** [Ben12345rocks/VotingPlugin#1337]
**Versions**
VotingPlugin: 6.15.1
Spigot: UniverseSpigot 1.20.1

**Describe the bug**
Bedrock player will not receive a reward if he is not online.

**To Reproduce**
1. Vote for server (username: *Heroify9936)
2. Join to the server with Bedrock client
3. The player will not receive any reward.

I think it it's caused by different UUIDs. Bedrock player UUID when joining to the server: 00000000-0000-0000-0009-01fa1bfc15e5
UUID found in VotingPlugin_Users after voting: 01c0a455-2185-3506-a3b8-7c822b7a88c1

There is wrong UUID only for Bedrock players.

Of course, I've changed BedrockPlayerPrefix to '*' in the configuration file.

I don't have Geyser or Floodage installed on the Spigot (backend) server, I have installed it only on Velocity (proxy).

**Expected behavior**
Bedrock players should receive rewards even when they are not online.

**Comment by BenCodez** [comment]
Bedrock support is a bit tricky, it generally works okay but some cases it fails. There isn't too much I can do to help. You have the bedrock prefix set on all servers?

**Comment by daniel-skopek** [comment]
Yeah, I have set Bedrock prefix on all servers where I have VotingPlugin.

**Comment by BenCodez** [comment]
Was that all set before the bedrock player voted once? If not that might explain it. You could try manually removing the invalid uuid.

**Comment by daniel-skopek** [comment]
It was set before voting. Also, I've tried removing the player's UUID (SQL row) from the database.

**Comment by BenCodez** [comment]
Send your configs

**Comment by daniel-skopek** [comment]
https://pastebin.com/raw/xdLvHB5p

**Comment by BenCodez** [comment]
OnlineMode: false This would do it, since in online mode it will ignore the vote from a bedrock player if it can't get the uuid

**Comment by daniel-skopek** [comment]
Should I set it to true even if I have online-mode to false?

**Comment by BenCodez** [comment]
Well no, just bedrock support isn't really going to work

**Comment by daniel-skopek** [comment]
Worked, after setting OnlineMode to true it gets the correct UUID for the Bedrock player.

The issue is solved, thanks for the help!
