### ISSUE TITLE
Monthly Keys

### ISSUE THREAD

**Issue by Mousycritter** [Ben12345rocks/VotingPlugin#1340]
Not positive on the versions, my only info is that monthly keys will not stack when acquired at different times. 

https://cdn.discordapp.com/attachments/1218713692900818974/1218713768372994108/image.png?ex=6608aaa4&is=65f635a4&hm=da083fd0498f823b2e70d124d91361185e5ab453d9b27c20186b27afd957169d& 
https://cdn.discordapp.com/attachments/1218713692900818974/1218713768889024613/image.png?ex=6608aaa5&is=65f635a5&hm=5bc6d47d9ac186efcb69b516f2488114c3d31859e1f59664af60ac797c82f2a6&
two discord image links

It's not only monthly keys, but all keys as well. Thought that'd be a worth note.

**Comment by BenCodez** [comment]
How are you giving keys?

**Comment by Mousycritter** [comment]
> How are you giving keys?

I'm new to GitHub so sorry if I'm not quite sure how to function everything properly.
Anyways, I'm doing it through vote crates/other crates with a 4.5% chance of getting 2. I also do rare key drops for reaching a certain criteria of mainly players online at once. We like to keep activity.

**Comment by BenCodez** [comment]
But how does votingplugin give it? A command?

**Comment by Mousycritter** [comment]
A command

**Comment by BenCodez** [comment]
And the issue is that the items all don't stack? Votingplugin isn't responsible about that

**Comment by Mousycritter** [comment]
Alright, I wasn't positive on the situation. Do you have an idea of what may be responsible for this?

**Comment by BenCodez** [comment]
Check with whatever plugin your using the keys from

**Comment by Mousycritter** [comment]
Alright thanks! Appreciate your quick response.
