### ISSUE TITLE
Online and offline votes are separating for bedrock players.

### ISSUE THREAD

**Issue by Dawlnken** [Ben12345rocks/VotingPlugin#1342]
**Versions**
Server: git-Purpur-2160 (MC: 1.20.4)*
Plugin: 6.15.1

**Description**
When bedrock users vote offline or online, their votes counts but only online or offline, the votes separate. If a offline player votes, then join the server and type /vote total, their votes won't show up. But if the player logs out and other player type /vote total (player that logout), it will see the vote. 

**To Reproduce**
1. Go vote offline for a bedrock account
2. Join server with that account and type /vote total.
3. You will see no votes registered for the player / incorrect amount of votes.

**Expected behavior**
Votes counting correctly regardless if the bedrock player is online or not.

**Screenshots/Configs**
![image](https://github.com/BenCodez/VotingPlugin/assets/138241627/e1f09d8c-eb24-4935-892c-264df2c05fef)
Config for plugin, votesites, rewards and special rewards: https://drive.google.com/drive/folders/1JPapwFQG_X8661sP9Ru6mxwbp7pckRZd?usp=sharing

**Additional context**
This doesn't happen for java players.
I'm using ' . ' as a prefix for bedrock players.
The server is running behind a velocity proxy.
NuVotifier is properly configured and accepting votes normally.

**Comment by BenCodez** [comment]
Is your entire network in offline mode? `OnlineMode: false`

**Comment by Dawlnken** [comment]
> Is your entire network in offline mode? `OnlineMode: false`

VotingPlugin is installed only on the survival server. It's the only server that accept votes.
OnlineMode is false for the plugin config.

**Comment by BenCodez** [comment]
Is your server and proxy in online mode or offline mode? I already looked at your config.

**Comment by Dawlnken** [comment]
> Is your server and proxy in online mode or offline mode? I already looked at your config.

both offline mode

**Comment by BenCodez** [comment]
Not really sure if it will work for you in offline mode. Even in online mode bedrock support is kinda 50/50.

**Comment by Dawlnken** [comment]
> Not really sure if it will work for you in offline mode. Even in online mode bedrock support is kinda 50/50.

my players are receiving the rewards normally (crate keys). the only problem is the Milestones thing

**Comment by BenCodez** [comment]
There probably isn't much I can do about it

**Comment by Dawlnken** [comment]
i'm not sure if the milestones will work for bedrock players with this vote counting problem

**Comment by Dawlnken** [comment]
> There probably isn't much I can do about it

so i might switch to another vote listener. do you know any good ones that both have milestones, support for bedrock players and offline votes?

**Comment by BenCodez** [comment]
No idea, offline mode isn't really supported in VotingPlugin.
