### ISSUE TITLE
Rewards in Conditional

### ISSUE THREAD

**Issue by Anthony01M** [Ben12345rocks/VotingPlugin#1343]
**Versions**
 6.15.1

**Relevant information**
https://paste.ee/p/LEB2f

**Context**
Conditional seems to be missing Rewards & related, is this intentional?

**Comment by BenCodez** [comment]
Is that for the voteshop?

**Comment by Anthony01M** [comment]
No, VoteURL.

**Comment by BenCodez** [comment]
What exactly are you trying todo?

**Comment by Anthony01M** [comment]
> What exactly are you trying todo?

Simply put, I'm trying to make it so that it allows my players to randomly reward my players once ALL sites have been voted when they click on that diamond; I know I could probably automate it so that it automatically gives them a random reward (which is basically a command to add custom economy)

**Comment by BenCodez** [comment]
why not just use AllSites reward?

**Comment by Anthony01M** [comment]
> why not just use AllSites reward?

Will try it once I'm back home.

**Comment by Anthony01M** [comment]
> why not just use AllSites reward?

by AllSites do you mean like this? https://paste.ee/p/obRsZ

Cause if yes this will break my whole ExtraItems;

with AllSites:
![image](https://github.com/BenCodez/VotingPlugin/assets/33878954/cafef50c-60d7-45f5-b60f-032fe517c907)

without AllSites:
![image](https://github.com/BenCodez/VotingPlugin/assets/33878954/8cfa6375-1867-4437-9e3b-69043dcd1e0b)

EDIT: Forgot to mention, I use AllSites here:
![image](https://github.com/BenCodez/VotingPlugin/assets/33878954/b603ef27-c1fc-4bfe-b41a-b398f83af147)

Part of AllSites: https://paste.ee/p/o2L72

**Comment by BenCodez** [comment]
I mean this: https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/Resources/SpecialRewards.yml#L18

**Comment by Anthony01M** [comment]
> > What exactly are you trying todo?
> 
> Simply put, I'm trying to make it so that it allows my players to randomly reward my players once ALL sites have been voted when they click on that diamond; I know I could probably automate it so that it automatically gives them a random reward (which is basically a command to add custom economy)

ahh so basically what I said to automate it with SpecialRewards; but don't know if it's a good idea to just give out the special rewards to everyone like that and rather require another step such as going to the menu and claiming it but alright will do.

**Comment by BenCodez** [comment]
This is an option:

    # Let the user pick a reward file to get
    # User can only pick one
    EnableChoices: false
    Choices:
      Diamond:
        DisplayItem:
          Name: '&c3 Diamonds'
          Material: DIAMOND
          Amount: 3
        Rewards:
          Items:
            Diamond:
              Material: 'DIAMOND'
              Amount: 3
          Messages:
            Player: '&aYou picked %choice%'
      Iron:
        DisplayItem:
          Name: '&c15 Iron Ingots'
          Material: IRON_INGOT
          Amount: 15
        Rewards:
          Items:
            Iron:
              Material: 'IRON_INGOT'
              Amount: 15
          Messages:
            Player: '&aYou picked %choice%'

**Comment by Anthony01M** [comment]
> This is an option:
> 
> ```
> # Let the user pick a reward file to get
> # User can only pick one
> EnableChoices: false
> Choices:
>   Diamond:
>     DisplayItem:
>       Name: '&c3 Diamonds'
>       Material: DIAMOND
>       Amount: 3
>     Rewards:
>       Items:
>         Diamond:
>           Material: 'DIAMOND'
>           Amount: 3
>       Messages:
>         Player: '&aYou picked %choice%'
>   Iron:
>     DisplayItem:
>       Name: '&c15 Iron Ingots'
>       Material: IRON_INGOT
>       Amount: 15
>     Rewards:
>       Items:
>         Iron:
>           Material: 'IRON_INGOT'
>           Amount: 15
>       Messages:
>         Player: '&aYou picked %choice%'
> ```

uh huh? Would that work in VoteURL?

This is basically the user deciding what he wants, I want it randomized when he has voted on ALL sites ONCE in a day. Guess I'll use SpecialRewards, no choice here then.

**Comment by BenCodez** [comment]
Where exactly are you adding the extra buttons item in the GUI.yml? I think it should work

**Comment by Anthony01M** [comment]
> Where exactly are you adding the extra buttons item in the GUI.yml? I think it should work

in VoteURL, everything I do is in VoteURL as I wasn't able to use CanVoteItem and AlreadyVoteItem in any other GUI

**Comment by BenCodez** [comment]
Was it under the ExtraItems section? Send the full file?

**Comment by Anthony01M** [comment]
> Was it under the ExtraItems section? Send the full file?

Only available for an hour: https://paste.ee/p/S8oZE

**Comment by BenCodez** [comment]
Give it a few minutes to build but this might fix it: https://bencodez.com/job/VotingPlugin/

**Comment by Anthony01M** [comment]
> Give it a few minutes to build but this might fix it: https://bencodez.com/job/VotingPlugin/

what exactly did you fix?

**Comment by BenCodez** [comment]
the rewards on the conditional items hopefully

**Comment by Anthony01M** [comment]
> the rewards on the conditional items hopefully

tested in latest build, it doesn't send rewards back (message) for false, let me check for true

**Comment by Anthony01M** [comment]
> > the rewards on the conditional items hopefully
> 
> tested in latest build, it doesn't send rewards back (message) for false, let me check for true

doesn't work for true as well

**Comment by BenCodez** [comment]
Add 2 spaces to your rewards line, then it should work

**Comment by Anthony01M** [comment]
> Add 2 spaces to your rewards line, then it should work

tried everything but still no rewards; where am I supposed to have it?
https://paste.ee/p/u9dEi

**Comment by BenCodez** [comment]
I tested it with this and it worked for me. Your using the latest dev build right?

    ExtraItems:
      Item1:
        # Javacript for conditional
        # Uses return value to get item info (can be anything, like numbers)
        ConditionalJavascript: 'User.canVoteAll()'
        Conditional:
          false:
            Material: 'REDSTONE_BLOCK'
            Amount: 1
            Rewards:
              Messages:
                Player: test true
          true:
            Material: 'EMERALD_BLOCK'
            Amount: 1
            Rewards:
              Messages:
                Player: test false

**Comment by Anthony01M** [comment]
> I tested it with this and it worked for me. Your using the latest dev build right?
> 
> ```
> ExtraItems:
>   Item1:
>     # Javacript for conditional
>     # Uses return value to get item info (can be anything, like numbers)
>     ConditionalJavascript: 'User.canVoteAll()'
>     Conditional:
>       false:
>         Material: 'REDSTONE_BLOCK'
>         Amount: 1
>         Rewards:
>           Messages:
>             Player: test true
>       true:
>         Material: 'EMERALD_BLOCK'
>         Amount: 1
>         Rewards:
>           Messages:
>             Player: test false
> ```

yes I am using the latest dev build

**Comment by BenCodez** [comment]
What does /av version say?

Could you try my example out?

**Comment by Anthony01M** [comment]
> What does /av version say?
> 
> Could you try my example out?

![image](https://github.com/BenCodez/VotingPlugin/assets/33878954/5e6a9dbd-7320-4ca6-a186-c95db33c8758)

sure trying your example out a minute.

**Comment by Anthony01M** [comment]
The issue was that I was missing an "s" in Messages now it works but I'm unable to make it one time only
working:
![image](https://github.com/BenCodez/VotingPlugin/assets/33878954/3602f403-39a6-4fbd-9c26-d1ee96a1ed46)

more than 1 time able to claim:
![image](https://github.com/BenCodez/VotingPlugin/assets/33878954/6c1828ba-c7a8-4468-ac4e-829deed10836)

can't find anything related to only 1 time claiming just noticed.

**Comment by BenCodez** [comment]
Could have it require a permission that you give on AllSites reward and then remove on the bonus reward

**Comment by Anthony01M** [comment]
> Could have it require a permission that you give on AllSites reward and then remove on the bonus reward

Will do that actually, thank you very much.
Closing this issue as it has been solved.
