### ISSUE TITLE
%SiteName% and %SiteVotedMonthlyCount% or something like it feature

### ISSUE THREAD

**Issue by Anthony01M** [Ben12345rocks/VotingPlugin#1344]
**Is your feature request related to a problem? Please describe.**
A bit disappointing that these features aren't added especially that seem more of an essential to have on a voting plugin.

**Describe the solution you'd like**
PlaceHolder to be available such as %SiteName% and %SiteVotedMonthlyCount% (to directly use in AlreadyVotedItem) or something like %votingplugin_total_monthly_topg_gg% (PlaceholderAPI)

**Describe alternatives you've considered**
The alternative solution right now I'm using is that it shows monthly votes for all of them and had to edit the %Name% as it cannot include dots (.) so removed everything else with it..

**Additional context**
I think the picture & the paste can explain a bit:

![image](https://github.com/BenCodez/VotingPlugin/assets/33878954/b319c86c-30fe-4336-8028-ee0e6fce1702)
As you can see here, I've edited the Name in config instead of SiteName to match my needs but it still doesn't have the .TLD which is not what I'm looking for;
Second is monthly total (overall) votes the player made instead of just the site.
GUI.yml (with removed parts for obvious reasons): https://paste.ee/p/tGGuP

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/PlaceHolderAPI-Expansion

Every placeholder is listed there.

**Comment by Anthony01M** [comment]
> https://github.com/BenCodez/VotingPlugin/wiki/PlaceHolderAPI-Expansion
> 
> Every placeholder is listed there.

this is a feature request to add one more which allows to have a specific site amount of votes AND a %SiteName% for VoteURL SiteName and SiteNameCanVote

    SiteName: '&c%Name%'
    SiteNameCanVote: '&a&l%Name%'

**Comment by BenCodez** [comment]
There is no tracking of votes per votesite. Which is what I understand you want?

**Comment by Anthony01M** [comment]
> There is no tracking of votes per votesite. Which is what I understand you want?

yes for the other half. As I'd like to use it in VoteURL (CanVoteItem & AlreadyVotedItem).

**Comment by BenCodez** [comment]
It's not possible to track amount of votes for site, there is no tracking for it. There is only daily, weekly, monthly, and all time total.

Not exactly sure what you want here right now

**Comment by Anthony01M** [comment]
> It's not possible to track amount of votes for site, there is no tracking for it. There is only daily, weekly, monthly, and all time total.
> 
> Not exactly sure what you want here right now

wanted the ability to track per votes for a specific site if possible to VotingPlugin. Like here:

I voted in Topg:
![image](https://github.com/BenCodez/VotingPlugin/assets/33878954/74d761b2-6637-4e23-a84b-bdff1da9e2e7)

I didn't vote in MinecraftServers:
![image](https://github.com/BenCodez/VotingPlugin/assets/33878954/dc936345-f76c-4d65-bfed-5f6f0826a951)

basically when I vote on a specific site it adds 1 (2,3 or whatever the amount I've voted on it) to that, if I don't it's still 0 ( I didn't vote at all on that site)

**Comment by BenCodez** [comment]
> > It's not possible to track amount of votes for site, there is no tracking for it. There is only daily, weekly, monthly, and all time total.
> > Not exactly sure what you want here right now
> 
> wanted the ability to track per votes for a specific site if possible to VotingPlugin. Like here:
> 
> I voted in Topg: ![image](https://private-user-images.githubusercontent.com/33878954/320241084-74d761b2-6637-4e23-a84b-bdff1da9e2e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NDY1MDMsIm5iZiI6MTcxMjQ0NjIwMywicGF0aCI6Ii8zMzg3ODk1NC8zMjAyNDEwODQtNzRkNzYxYjItNjYzNy00ZTIzLWE4NGItYmRmZjFkYTllMmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDIzMzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZDUyYWZkZWQwYzJhNDFhYmZhODI1MmRhYzA5MmVjZTI5ZjRkODkyNTgzMjE5NjQzNTNlMTg4YTRhZjVlMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5AZnCaWxBpv3u8eedcbqAr35zK8EMH3l9TUvstkngUo)
> 
> I didn't vote in MinecraftServers: ![image](https://private-user-images.githubusercontent.com/33878954/320241212-dc936345-f76c-4d65-bfed-5f6f0826a951.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NDY1MDMsIm5iZiI6MTcxMjQ0NjIwMywicGF0aCI6Ii8zMzg3ODk1NC8zMjAyNDEyMTItZGM5MzYzNDUtZjc2Yy00ZDY1LWJmZWQtNWY2ZjA4MjZhOTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDIzMzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZDM4NDY3ZGI1OWVjNTM0MzA2ZjQxNjJiN2Q0NWQ0NzFiNjQxYzJiZTNkNGM1ZjQwYjEyMTgzOGMyMDhmMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b9-9-H8_Ts2yPLKMbc3uzQrM7Ys9g8dlC-m6iqwNBXY)
> 
> basically when I vote on a specific site it adds 1 (2,3 or whatever the amount I've voted on it) to that, if I don't it's still 0 ( I didn't vote at all on that site)

That's currently not possible and I don't plan on adding it anytime soon or if I ever will.

**Comment by Anthony01M** [comment]
> > > It's not possible to track amount of votes for site, there is no tracking for it. There is only daily, weekly, monthly, and all time total.
> > > Not exactly sure what you want here right now
> > 
> > 
> > wanted the ability to track per votes for a specific site if possible to VotingPlugin. Like here:
> > I voted in Topg: ![image](https://private-user-images.githubusercontent.com/33878954/320241084-74d761b2-6637-4e23-a84b-bdff1da9e2e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NDY1MDMsIm5iZiI6MTcxMjQ0NjIwMywicGF0aCI6Ii8zMzg3ODk1NC8zMjAyNDEwODQtNzRkNzYxYjItNjYzNy00ZTIzLWE4NGItYmRmZjFkYTllMmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDIzMzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZDUyYWZkZWQwYzJhNDFhYmZhODI1MmRhYzA5MmVjZTI5ZjRkODkyNTgzMjE5NjQzNTNlMTg4YTRhZjVlMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5AZnCaWxBpv3u8eedcbqAr35zK8EMH3l9TUvstkngUo)
> > I didn't vote in MinecraftServers: ![image](https://private-user-images.githubusercontent.com/33878954/320241212-dc936345-f76c-4d65-bfed-5f6f0826a951.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NDY1MDMsIm5iZiI6MTcxMjQ0NjIwMywicGF0aCI6Ii8zMzg3ODk1NC8zMjAyNDEyMTItZGM5MzYzNDUtZjc2Yy00ZDY1LWJmZWQtNWY2ZjA4MjZhOTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDIzMzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZDM4NDY3ZGI1OWVjNTM0MzA2ZjQxNjJiN2Q0NWQ0NzFiNjQxYzJiZTNkNGM1ZjQwYjEyMTgzOGMyMDhmMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b9-9-H8_Ts2yPLKMbc3uzQrM7Ys9g8dlC-m6iqwNBXY)
> > basically when I vote on a specific site it adds 1 (2,3 or whatever the amount I've voted on it) to that, if I don't it's still 0 ( I didn't vote at all on that site)
> 
> That's currently not possible and I don't plan on adding it anytime soon or if I ever will.

hmm alright, what about the %SiteName% placeholder for server sites instead of using only %Name%?

**Comment by BenCodez** [comment]
There is %ServiceSite% but you need this build until the next release: https://bencodez.com/job/VotingPlugin/

**Comment by Anthony01M** [comment]
> ServiceSite

![image](https://github.com/BenCodez/VotingPlugin/assets/33878954/a58f0e57-dd5e-4d89-a94d-a9ac6b448106)

latest build was what I downloaded unless I made a mistake

**Comment by Anthony01M** [comment]
testing on the new build that was released 3minutes ago

**Comment by BenCodez** [comment]
Should be fixed in the next build 1212

**Comment by Anthony01M** [comment]
> Should be fixed in the next build 1212

![image](https://github.com/BenCodez/VotingPlugin/assets/33878954/a9147dd5-2dc8-40f1-9ad9-cec979db39f3)
same thing

**Comment by BenCodez** [comment]
Where exactly is that set?

**Comment by Anthony01M** [comment]
> Where exactly is that set?

  VoteURL:
    # GUI Name
    Name: '&4Vote for reward'
    BackButton: false
    SiteName: '&c%ServiceSite%'
    SiteNameCanVote: '&a&l%ServiceSite%'
    SeeURL: '&cClick to see URL'
    
    EDIT: for some reason github removed the spaces, please be aware of that.

**Comment by BenCodez** [comment]
Next build work?

**Comment by Anthony01M** [comment]
Thank you!

%ServiceSite% now works!
Will be closing this issue now since the other feature was denied.
![image](https://github.com/BenCodez/VotingPlugin/assets/33878954/95a6ffec-1bdf-4eed-b0d4-0d55ff49d35e)
