### ISSUE TITLE
More than 1 Vote Shop

### ISSUE THREAD

**Issue by Anthony01M** [Ben12345rocks/VotingPlugin#1345]
**Is your feature request related to a problem? Please describe.**
Having only 1 shop limits our ability to do a lot of stuff and require us to use external plugins, which in my opinion is not ideal in a bungeecord server and would rather keep them all in one place.

**Describe the solution you'd like**
Ability to have more than just 1 shop - /vote shop 
And set which one would be the main shop, for example in survival I'd like `/vote shop GUI main` to be the main shop while `/vote shop GUI lobby`, `/vote shop GUI (shop_name)` are additions.

**Describe alternatives you've considered**
Using another plugin on each server.

**Additional context**
One VoteShop is not enough for me to have all my bungeecord servers on, and yes, I'd like people to PURCHASE for example lobby fly for 30days in survival through points.

Current temporarily vote shop is 1 and only 1 unable to have one for:
- ability to purchase commands.
- ability to purchase ranks (per server ranks/global ranks).
- ability to purchase suffixes/keys.

![image](https://github.com/BenCodez/VotingPlugin/assets/33878954/f0f1ccfd-43fb-41dd-a862-7b664b7decd0)

**Comment by BenCodez** [comment]
It should support pages if you have enough items.

I can see what I can do about more than one voteshop, but I'd have to change how the files are laid out to do that
