### ISSUE TITLE
Placeholder %VotingPlugin_BungeeVotePartyVotesNeeded% not working

### ISSUE THREAD

**Issue by TomHo41** [Ben12345rocks/VotingPlugin#1346]
**Versions**
This server is running Paper version git-Paper-167 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 0c0a480)
Previous version: git-Paper-17 (MC: 1.20)

VotingPlugin version 6.15
PlaceholderAPI 2.11.5

**Describe the bug**
When using placeholder %VotingPlugin_BungeeVotePartyVotesNeeded% it has always value -1 

**To Reproduce**
Using Placeholder in Chat / Scoreboard

**Expected behavior**
Display true value

**Comment by BenCodez** [comment]
Have you triggered atleast one bungee vote?

**Comment by TomHo41** [comment]
Server is not connected though bungeecord

**Comment by BenCodez** [comment]
Then why are you using a bungee vote party placeholder?
