### ISSUE TITLE
Itemadder idem doesnt change the name defined in voting plugin

### ISSUE THREAD

**Issue by pjindras** [Ben12345rocks/VotingPlugin#1351]
**Versions**
6.15.1 and 1.20.4

**Describe the bug**

![image](https://github.com/BenCodez/VotingPlugin/assets/45400186/3203d4e6-0100-4825-ac70-0ebbc6a016aa)
![image2](https://github.com/BenCodez/VotingPlugin/assets/45400186/b6fb9b6c-9ff7-4c7e-8df6-9a75d7ad213b)

I defined Name: '&aMy name' in voting plugin in case of #ItemsAdder: item, but it uses only the name  which is defined directly in the itemsadder (for example icon back red instead of &aMy name which is defined in voting pl)

**Comment by BenCodez** [comment]
This work? https://bencodez.com/job/VotingPlugin/

**Comment by pjindras** [comment]
Yes it works, thank you!
