### ISSUE TITLE
Not counting vote correctly in the "sites voted on today" stat 

### ISSUE THREAD

**Issue by trent304** [Ben12345rocks/VotingPlugin#1355]
**Versions**
6.15.1 - Paper 1.20.1

**Describe the bug**
When I vote on the site https://www.minecraft-servers-list.org the in-game message is executed and a vote is counted in the database, however, it still says "You have 1 sites to vote on still" even though I voted on all of them (I have 7). When I do /votenext it shows that I still have to vote on https://www.minecraft-servers-list.org. 

**To Reproduce**
1. Maybe try https://www.minecraft-servers-list.org as a voting site and see if it executes the messages, but doesn't count the vote in the "sites voted on today" (or whatever you'd call it)

**Expected behavior**
The message is sent, Vote is counted, and the site is marked as voted on today

**Screenshots/Configs**
https://pastebin.com/vUAD5RLi Here is the config for the site in votesites.yml. This is after I deleted it from this file, Serverdata.yml, and revoted so the site would show up again.

**Additional context**
I feel it might be related to the servicesite name containing https:// but I obviously don't have the ability to change this

**Comment by BenCodez** [comment]
a votesite generates if there is no matching service site, you'll need to correct that. https://github.com/BenCodez/VotingPlugin/wiki/Service-sites

**Comment by trent304** [comment]
What do I need to correct?

This is the console output I am getting and Voting Plugin seems to recognize it, but when I hover in the votenext menu it still says "Go Vote!"

https://pastebin.com/sgBZmchr

**Comment by BenCodez** [comment]
ServiceSite: `https://www.minecraft-servers-list.org`

What's it do with this?

**Comment by trent304** [comment]
Same thing. In game it says "'Thanks for voting on https://www.minecraft-servers-list.org!" which is the only site that has the default message, but it still says "Go vote" in the menu and doesn't remove one from the "You have x more sites to vote on" message

**Comment by BenCodez** [comment]
Send your votesites.yml after it generates a votesite
