### ISSUE TITLE
1.16.1 breaks Glow: true

### ISSUE THREAD

**Issue by Anthony01M** [Ben12345rocks/VotingPlugin#1356]
**Versions**
Plugin: 1.16.1
Server: 1.20.4

**Describe the bug**
Glow: true no longer works

**To Reproduce**
1. Slowly switch from old version to new version while making sure everything is up to date.
2. Try use Glow: true on a "item"
3. /av reload in game
4. Error

**Expected behavior**
No errors on console, item glows.

**Screenshots/Configs**
My paste.ee contains one "broken.yml" and "works.yml" (with console error at the end); please read additional context.
https://paste.ee/p/LoITN

**Additional context**
In the broken.yml (which is the VotingPlugin old version) Glow: true/ Glow: false works without any issues.
In the works.yml (which is the VotingPlugin new version) Glow: true/false is not there, which is why it's not sending the error in the console.
This should not happen, especially that wiki says there is Glow: true/false here: https://github.com/BenCodez/VotingPlugin/wiki/Item-Configuration

**Comment by Anthony01M** [comment]
just a note, Glow: true works in ExtraItems just not CanVoteItem/AlreadyVotedItem.
Glow does not work in "Shop" items. ( https://paste.ee/p/jC9os )

**Comment by BenCodez** [comment]
Think this is already fix here: https://bencodez.com/job/VotingPlugin/
