### ISSUE TITLE
Problem with vote forwarding on Velocity server

### ISSUE THREAD

**Issue by pjindras** [Ben12345rocks/VotingPlugin#1357]
**Versions**
Spigot 1.20.4

21:34:41[INFO] Using AdvancedCore 3.7.6' built on '2024-05-07 23:09
21:34:41[INFO] VotingPlugin version 6.16.1

**Describe the bug**

I have a Velocity (Velocity 3.3.0-SNAPSHOT (git-71bb0246-b392)) server + Voting plugin vote forwarding using plugin messaging.

The problem is the offline votes. When player votes offline, for some of the players, they dont get the reward after login.
Config Velocity:

https://paste.gg/p/anonymous/a9ffaf75cd994d7888e37ed1ae32d75e

Config survival and skyblock server bungee file:
https://paste.gg/p/anonymous/389e6c77b2f64745802a84bfa65a5d56

Config survival and skyblock server config file:
https://paste.gg/p/anonymous/3499ed65663f48ceb84950f5e65a4a9a

Lobby server doesnt have voting plugin installed.

I made a debug, the vote arrives succesfully:
https://paste.gg/p/anonymous/25ba0e1392164e8b85dbd63f654e0c36

Player uuid is correct (compared with luckperms)

but the survival server doesnt received the vote and doesnt give the reward to the player:
https://paste.gg/p/anonymous/f9288722b0c04073bb9b29feec5b0b76

Player name: Glatius, UUID 85acd914-d27f-4682-9ceb-01f35b84225b

**To Reproduce**
I really dont know, it happens in case of many players, but for many players it works fine, I have server with 100+ online players in peak, for some of them, maybe 20% offline rewards doesnt work, there are warez players and original mc players too, for who the problem occures. 

I can provide any details, I have debug enabled everywhere.

What I want to achieve is, that when the player votes offline, first game server (not lobby) will give the player the reward  for voting.

**Comment by BenCodez** [comment]
What's on proxy when a player that voted offline joins?

Only other thing I notice is your backend server has online mode disabled: `OnlineMode: false` in config.yml. This is probably where the issue lies

**Comment by pjindras** [comment]
This happens on proxy side, when the player joined: https://paste.gg/p/anonymous/0c98f8dae9444cf28373d7ef85929f03

I also tried to set the bungee to offline mod, but there it was causing me problems, then I was afraid that if I change the settings on the backend server to online mod, I might lose data.

Previously I had only one server, the proxy and the other came after a while, that's why this setup happened.

**Comment by BenCodez** [comment]
Backup your mysql data just incase and enable online mode (in votingplugin config.yml only), when the player is offline it will attempt to get offline mode uuid instead (as a shortcut since offline mode uuids are easy to get from a playername). Sometimes the names/uuids are cached enough that it won't do that. That's my current guess. Might have to restart as well once you do that to clear the name/uuid cache.

**Comment by pjindras** [comment]
ok thank you, I will try it and let you know

**Comment by pjindras** [comment]
I think the problem is fixed, but I will wait one more day, because maybe some more rare problem or case could occure.

**Comment by pjindras** [comment]
I also tried a clean reinstallation running outside the proxy and without proxy mode, in some cases, even though I have online mode true everywhere (in voting plugin, server is still offline mode), there is a problem with some players with UUIDs that are different than they actually have (in luckperms, etc.) and they are duplicated in the database, but I'm not sure what it could be, now I've tried a pure clean DB and a clean install without bungee with this config: https://mclo.gs/RIGNtzg

**Comment by BenCodez** [comment]
Can you send a player name with their respective uuid (the correct one) on your server?
