### ISSUE TITLE
Pause Votes/Vote Party Rewards

### ISSUE THREAD

**Issue by baailey** [Ben12345rocks/VotingPlugin#1359]
**Is your feature request related to a problem? Please describe.**
When hosting fun little events for players in a controlled environment where standard inventory items cannot be brought in, there'll be situations where players may vote and receive rewards in the event, or a vote party will happen during the event so countless people receive rewards that they'll more than likely lose. It can be a very upsetting situation for them. 

**Describe the solution you'd like**
I would like to suggest introducing a command that will pause players receiving rewards from both voting and vote parties until this pause is undone. Or, allowing the pause to only happen in specific worlds for example if looking for further customisation. 

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by BenCodez** [comment]
You could add a list of worlds to give or not give to each reward and it will give when the player returns to that world.

Otherwise I can see about implementing some sort of pause feature

**Comment by baailey** [comment]
That sounds ideal, I'll probably do that. Though if an event is held in the overworld then unfortunately that sort of configuration option wouldn't be as beneficial in comparison to the event being held elsewhere. A pause function would definitely be appreciated either way.

**Comment by BenCodez** [comment]
You want a global pause function right? All players at once?

**Comment by BenCodez** [comment]
Could you try disabling ProcessRewards during an event and use /av reload and enabled it afterword and see if that works? If so I can make a pause command do that.

**Comment by baailey** [comment]
Disabling, reloading, voting, enabling and then reloading reloading does not grant the rewards.

**Comment by BenCodez** [comment]
Probably have to relog/restart at the moment for it to give rewards, as disabling processrewards will just force everything to save as an offline reward

**Comment by baailey** [comment]
After restarting the rewards are given

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/

https://github.com/BenCodez/VotingPlugin/commit/56e6a659fe1bc3c72402281380b1c6183e3aa2f5

/av pauserewards
/av resumerewards

Not tested, but I think it should work (works similarity to processrewards)
