### ISSUE TITLE
Milestones issue

### ISSUE THREAD

**Issue by pjindras** [Ben12345rocks/VotingPlugin#1363]
**Versions**

13:12:07[INFO] Highly Customizable Voting Listener!
13:12:07[INFO] Website: https://www.spigotmc.org/resources/votingplugin.15358/

Server: Purpur 1.20.4

**Describe the bug**
When player reachs milestone and is offline, player doesnt get the milestone reward, in db milestone is "90//true" but the reward is not given.

Milestones config:
https://paste.gg/p/anonymous/d2e2c07ea89648a3863ebdf5ce4b1558

I dont use bungee, only spigot (i used in past, but dropped it and disabled it + made a new clean db after doing that)

**Additional context**

**Comment by pjindras** [comment]
+ here is my config: https://paste.gg/p/anonymous/9965cea2414d40308c7b6ac925d32337

+ degub: https://paste.gg/p/anonymous/b6362ca6aec444e78da00e926975bca1
and: https://paste.gg/p/anonymous/4750fcdefe36484a90aa46b440f487d4


name of player pjindras (but its broken for all players)

**Comment by BenCodez** [comment]
It should be running when you log in, does it not run anything?

**Comment by pjindras** [comment]
no it doesnt run the reward command unfortunately

**Comment by BenCodez** [comment]
Does it work while online?

**Comment by pjindras** [comment]
yes, but when i reach milestone offline and log-in than it doesnt give the reward

**Comment by BenCodez** [comment]
What's in VotingPlugin/Rewards?

**Comment by pjindras** [comment]
I mean rewards defined in milestones, I receive vote rewards even if I am online

**Comment by pjindras** [comment]
![image](https://github.com/BenCodez/VotingPlugin/assets/45400186/3eb2dc9f-8963-44bb-8aa5-be75e5f7a2f1)

**Comment by pjindras** [comment]
those rewards I receive, there is no problem, only the milestones have issue

**Comment by BenCodez** [comment]
What's in DirectlyDefined right now?

**Comment by pjindras** [comment]
nothing is there, empty file

**Comment by BenCodez** [comment]
Wanna try a server restart and see what happens?

**Comment by pjindras** [comment]
Ok, I can try, but the problem occures a few days, so I restarted the server many times

**Comment by BenCodez** [comment]
If it doesn't work after a restart could you send the log with debug of the milestone being given while online?

**Comment by pjindras** [comment]
> If it doesn't work after a restart could you send the log with debug of the milestone being given while online?

It doesnt work after restart, I am sending debug what happens, when the player is online:
https://paste.gg/p/anonymous/a4ad98de760741a79967be20cd75f492

player name pjindras

**Comment by BenCodez** [comment]
Does this build change anything? https://bencodez.com/job/VotingPlugin/

**Comment by pjindras** [comment]
Yes, now it works fine, but I also changed some settings etc.

**Comment by BenCodez** [comment]
So all good?

**Comment by pjindras** [comment]
Yes, it should be good now.
