### ISSUE TITLE
No reward voteparty

### ISSUE THREAD

**Issue by ElEspix** [Ben12345rocks/VotingPlugin#1364]
**Versions**
I used version 6.16.2 and it didn't work, then I changed to 6.15.1 and it didn't work either

Hello, I have a problem with the vote party section, it does not give the rewards to the players and it does not execute the commands that are added, even when I do /av voteparty force. If you could help me I would appreciate it, what information do you need from the config? (but if the rewards for normal votes work)
excuse my bad English

# To disable reward set value to {}
# or remove entirely
# Eg:
# FirstVote: {} (All in one line)
# Rewards will be given if there is a reward to give, otherwise they will be ignored

# First vote rewards
FirstVote: 
  Messages:
    Player: '&aYou voted for your first time!'
    
# First vote of the day reward
FirstVoteToday: {}

# All vote rewards
# One time reward for voting on all sites in one day
# Enable ExtraAllSitesCheck if you get double rewards
AllSites: 
  Messages:
    Player: '&aYou voted on all sites in 1 day!'
    
# Give a reward for voting on all sites minus 1
# Similar to allsites
#AlmostAllSites:
#  Messages:
#    Player: '&aYou almost voted on all sites in 1 day!'

# If true only cumulative reward at a time can be given
# The cumulative rewards will go in order as listed under Cumulative, so if true
# the first cumulative (in the order as listed) that can be given will, then will ignore the rest
OnlyOneCumulative: false
# NOTE: This is not a 1 time reward, that's what milestones are for!
# If total votes (Can be changed) divided by cumulative amount 
# and with no remainder (So divides perfectly) then a reward is given
Cumulative:
  # Number of votes required
  # Allows multiple cumulative rewards
  # Number be be around ' (E.g. '1')
  # Can have multiple listed here
  '20':
    Enabled: false
    # Whether or not votes must be made in same day/week
    # Useful if you want to require a certain number of voting sites to be voted on
    # for a daily/weekly reward instead of all of them
    # Valid options
    # AllTime
    # Monthly
    # Weekly
    # Daily
    TotalToUse: AllTime
    # Blacklist recurring votes
    #BlackList:
    #- 40
    # Whether or not to gives cumulative reward for every x number of votes, default: true
    #Recurring: true
    Rewards: 
      Messages:
        Player: '&aYou got %cumulative% cumulative votes!'

# Vote party configuration
VoteParty:
  # Wether or not vote party is enabled
  Enabled: true
  # Number of votes required to give rewards
  VotesRequired: 10
  # Increase the amount of votes required on each vote party reached
  #IncreaseVotesRquired: 10
  # If true, players who did not vote to reach the votes required will 
  # recieve the reward
  # If false, only players who voted get rewards
  GiveAllPlayers: false
  # If true, give online players the vote party reward
  # Can also use RewardType: ONLINE if you wanted
  GiveOnlinePlayersOnly: true
  # If true, the vote count will reset each day
  ResetEachDay: false
  # If true, the vote count will reset each week
  ResetWeekly: false
  # Reset at the end of the month
  ResetMonthly: false
  # If true, will give voteparty only once per day
  OnlyOncePerDay: false
  # If true, will give voteparty once per week only
  OnlyOncePerWeek: false
  # Reset extra votes weekly
  ResetExtraVotesWeekly: false
  # Reset extra votes monthly
  ResetExtraVotesMonthly: false
  # Count votes from /av vote?
  CountFakeVotes: true
  # Number of user votes that apply to vote party total the user needs to get rewards
  UserVotesRequired: 0
  # Count offline votes
  CountOfflineVotes: true
  # Broadcast when vote party reached
  Broadcast: '&cReached the vote party amount!'
  # Send a broadcast at a certain number of votes left and send a vote reminder
  VoteReminderBroadcast: '%votesrequired% left to go, go vote!'
  # List of votes required amounts for when to send vote party reminders
  VoteReminderAtVotes: []
  # List of commands to execute, these only execute once.
  # %player% does not work here
  GlobalCommands: []
  # List of commands to execute once
  # Only run will run
  GlobalRandomCommand: []
  # Rewards to give per player
  Rewards: 
    RewardType: ONLINE
    Rewards:
    # Uncomment below for online players to be rewarded only
    #RewardType: ONLINE
      Items:
        TRIPWIRE_HOOK:
            ItemStack:
              v: 3700
              type: TRIPWIRE_HOOK
              meta:
                ==: ItemMeta
                meta-type: UNSPECIFIC
                display-name: '{"text":"","extra":[{"text":";;","obfuscated":true,"italic":false,"color":"gold"},{"text":"Llave
                  Caja Vote","obfuscated":false,"italic":false,"color":"gold"},{"text":";;","obfuscated":true,"italic":false,"color":"gold"}]}'
                lore:
                - '{"text":"","extra":[{"text":"Cajeala en el spawn","italic":false,"color":"dark_purple"}]}'
                PublicBukkitValues: |-
                  {
                      "excellentcrates:crate_key.id": "vote"
                  }
  
# Reset milestones at end of the month
ResetMilestonesMonthly: false
  
# One time reward to be given (unless you reset it somehow)
MileStones:
  # Number of votes required
  # Allows multiple milestones
  # Number be around ' (E.g. '1')
  # Can have multiple listed here
  '20':
    Enabled: false
    Rewards: 
      Messages:
        Player: '&aYou got %milestone% milestone votes!'
   
VoteStreak:
  # Valid options: Day, Week, Month
  Day:
    # Number of days in a row
    # Each day requires one vote
    # Add a - to give a reward for every multiple (e.g. 2- = 2,4,6,8, and so on)
    # This may not work perfectly on bungee setups at this time
    '2':
      # Enabled or not
      Enabled: false
      # Rewards to give
      Rewards:
        Messages:
          Player: "&aYou voted for %Streak% %Type%'s in a row!"
  Week:
    # Number of weeks in a row
    # Requires atleast one vote per week
    '2':
      # Enabled or not
      Enabled: false
      # Rewards to give
      Rewards:
        Messages:
          Player: "&aYou voted for %Streak% %Type%'s in a row!"
  Month:
    # Number of months in a row
    # Requires atleast 1 vote per month
    '2':
      # Enabled or not
      Enabled: false
      # Rewards to give
      Rewards:
        Messages:
          Player: "&aYou voted for %Streak% %Type%'s in a row!"
  Requirement:
    # Require certain percentage of votes
    UsePercentage: false
    # Percentage requirements of votes
    # 50 = %50
    Day: 50
    Week: 50
    Month: 50
    
# Reward given when all votesites are available to vote on
# Don't use this unless you really need it
# Little performance intensive
# Recommend add RewardType: ONLINE for it to only work online
VoteCoolDownEndedReward: []

# ONLY USE THIS FOR TITLES/SOUNDS AND OTHER EFFECTS
# IT WILL ONLY RUN ONE TIME FOR ANY NUMBER OF OFFLINE VOTES (3 offline votes = 1 AnySiteReward)
# Any reward files listed here are ran on vote of any site
# It is recommended to add rewards to each site instead of here
# Using forceoffline won't work here
# Use EverySiteReward in VoteSites.yml for a global reward for each site
AnySiteRewards: {}

# Rewards to run when player logs in
LoginRewards: {}

# Rewards to run when player logs off
# Will queue until player logs in unless forceoffline is enabled
LogoutRewards: {}

EnableMonthlyAwards: true

# TopVoter Placeholders:
#%place% - place in topvoter
#%topvoter% - topvoter type
#%votes% - current total votes related to top voter

# Rewards to give
MonthlyAwards:
  # Position. 1 is first in top voter, 2 is second, etc...
  # Using 1-10 will reward players in first to tenth place with the same reward
  1:
    Rewards:
      Messages:
        Player: '&aYou came in first place in %TopVoter%!'
  2:
    Rewards:
      Messages:
        Player: '&aYou came in second place in %TopVoter%!'
    
EnableWeeklyAwards: false
# Rewards to give on weekly top voter
WeeklyAwards:
  # Position. 1 is first in top voter, 2 is second, etc...
  1:
    Rewards:
      Messages:
        Player: '&aYou came in first place in %TopVoter%!'
  2:
    Rewards:
      Messages:
        Player: '&aYou came in second place in %TopVoter%!'
    
EnableDailyRewards: false
# Rewards to give on daily top voter
DailyAwards:
  # Position. 1 is first in top voter, 2 is second, etc...
  1:
    # Reward files to give
    Rewards:
      Messages:
        Player: '&aYou came in first place in %TopVoter%!'
  2:
    Rewards:
      Messages:
        Player: '&aYou came in second place in %TopVoter%!'

**Comment by BenCodez** [comment]
Use pastebin to send your specialrewards.yml

**Comment by ElEspix** [comment]
Excuse me, what do you mean by pastebin?

**Comment by BenCodez** [comment]
pastebin.com

**Comment by ElEspix** [comment]
Great, is there a tutorial on how to use pastebin to deliver keys to the voteparty?

**Comment by BenCodez** [comment]
pastebin.com is a website used to send the files, not sure what your talking about

**Comment by ElEspix** [comment]
Sorry, I understand, there is the link with the code, thanks for your patience https://pastebin.com/DzR1nLN3

**Comment by BenCodez** [comment]
I'd use a command to give the reward if your trying to give a crate key, you voted before you tested it right? (You have it set to require atleast one vote to give the reward right now)
