### ISSUE TITLE
Does not detect bedrock players

### ISSUE THREAD

**Issue by LordYarkan** [Ben12345rocks/VotingPlugin#1365]
Hello, I am using the latest versions of VotingPlugin, floodgate proxy and floodgate spigot. the votes do not recognize Bedrock players.
and that's what I have configured.
BedrockPlayerPrefix: '.'
my server is: 1.20.4

What is the problem due to?

**Comment by BenCodez** [comment]
Is online mode enabled?

**Comment by LordYarkan** [comment]
> Is online mode enabled?
No, it's for pirates too.
online-mode: false

**Comment by BenCodez** [comment]
Enable online mode in votingplugin

**Comment by LordYarkan** [comment]
> Enable online mode in votingplugin

Config.yml
OnlineMode: true

It was already in this configured mode, I thought it refers to the server configuration.
then the problem persists

**Comment by BenCodez** [comment]
Is votingplugin on proxy?

**Comment by LordYarkan** [comment]
> Is votingplugin on proxy?

Yes I have a proxy but I haven't put VotingPlugin there´
If I add in the proxy I must also install in each mode, right?

**Comment by LordYarkan** [comment]
Well, I installed on the proxy and went to vote with a bedrock account. and no vote came, it comes out as if I never voted. but in the proxy console it does show that the vote arrived.
What should I configure in the proxy for the Bedrock players theme to work well?

**Comment by BenCodez** [comment]
Give this a try: https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING

Might work better

**Comment by LordYarkan** [comment]
> Give this a try: https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING
> 
> Might work better

Is it mandatory to use MySql?
In the proxy there are 2 zones to add mysql information which one do I use the normal one or GlobalData?

In the Spigot server activate the option:
DataStorage: MYSQL
and I put the same data as in the proxy.

The bedrocks issue is still not working for me.
I have followed all the steps in the wiki.
I have to put your default prefix when voting for Bedorck.
because it only works on a couple of pages where it accepts names with a dot "." but the rest of the pages the "." does not work.

**Comment by BenCodez** [comment]
Yes you need mysql, just set everything (you can ignore the globaldata one, it's not required)

There isn't much I can do if the voting sites doesn't accept the dot.

**Comment by LordYarkan** [comment]
> Sí, necesitas mysql, simplemente configura todo (puedes ignorar el de datos globales, no es necesario)
> 
> No puedo hacer mucho si los sitios de votación no aceptan el punto.

I have MySql configured and it does not recognize bedrock players, only when they put a dot on the voting page.

Do bedrock users have to put a dot "." in the voting page when voting?
or does VotingPlugin recognize them if they type their name without dot "."?

Is it a problem with the Floodgate plugin?
because I'm using the latest versions and before I updated Votinplugin and Floodgate I didn't have these problems, well it rarely happened before.

**Comment by BenCodez** [comment]
Need to vote with the dot.

Version of floodgate shouldn't matter

**Comment by LordYarkan** [comment]
> Need to vote with the dot.
> 
> Version of floodgate shouldn't matter

Ok add dot, 
for example on the Topg website a bedrock player votes and in the proxy console the message arrives that the player has voted but his name arrives without a dot. So the problem is of the web, it means that the voting pages are limited for Bedrocks players.

What is BedrockPlayerPrefix: '.' used for in the VotingPlugin configuration?

**Comment by BenCodez** [comment]
> > Need to vote with the dot.
> > Version of floodgate shouldn't matter
> 
> Ok add dot, for example on the Topg website a bedrock player votes and in the proxy console the message arrives that the player has voted but his name arrives without a dot. So the problem is of the web, it means that the voting pages are limited for Bedrocks players.
> 
> What is BedrockPlayerPrefix: '.' used for in the VotingPlugin configuration?

Some sites don't support it as well as others, could always use a prefix that does support it, but thats hard to change after the fact.

Config option is used to know what the prefix is.

**Comment by LordYarkan** [comment]
> Some sites don't support it as well as others, could always use a prefix that does support it, but thats hard to change after the fact.
> 
> Config option is used to know what the prefix is.

Understood, I see that it is my mistake, I did not know that you had to vote with a period. Thank you for your time.
