### ISSUE TITLE
Vote Rewards

### ISSUE THREAD

**Issue by Ironsicecream** [Ben12345rocks/VotingPlugin#1369]
![image](https://github.com/user-attachments/assets/5022615b-23c5-40ff-ac62-1fcf6d492e75)
I tried making the rewards config using the references provided but I cant seem to get it work, any advice will be appreciated 🍡 .

**Comment by Ironsicecream** [comment]
https://pastebin.com/0ebFJjd2#google_vignette

**Comment by BenCodez** [comment]
Just set the rewards in votesites.yml under Rewards 

https://github.com/BenCodez/VotingPlugin/wiki/Rewards
