### ISSUE TITLE
milestone reward

### ISSUE THREAD

**Issue by rentalmodding** [Ben12345rocks/VotingPlugin#1371]
**Versions**
6.17 spigot 1.21

**Relevant information**
# One time reward to be given (unless you reset it somehow)
MileStones:
  # Number of votes required
  # Allows multiple milestones
  # Number be around ' (E.g. '1')
  # Can have multiple listed here
  '1':
    Enabled: true
    Rewards: 
      Messages:
        Player: '&aYou got %milestone% milestone votes!'
      Commands:
      Console:
      - 'lp user %player% promote pluto'

**Context**
how do i do milestones with luckperm ranks I got told do tracks but I'm trying to figure out the user part I'm not sure on how I do a specific user that voted get that said milestone and how do I add more milestones as well

**Comment by BenCodez** [comment]
You do that just by running a command, not sure how you do the tracks part but this not within votingplugin
