### ISSUE TITLE
unable to bind to my server

### ISSUE THREAD

**Issue by Patatatta** [Ben12345rocks/VotingPlugin#1373]
**Versions**
NuVotifier 2.7.3
VotingPlugin 6.17

**Relevant information**
[20:33:49 ERROR]: [null] Votifier was not able to bind to /0.0.0.0:25720
sorry i didnt do a pastebin because its just 1 line

**Context**
I put in everything correctly I have an external server from minehut>sparkedhost and I'm using the SparkedHost IP and port, but the plugin wont bind to it for some reason, the /testvote command works fine but when I press test vote from minecraftservers.org it doesn't send to the server.

**Comment by BenCodez** [comment]
issue is with votifier, can't use the port you set

**Comment by Patatatta** [comment]
Oh, well how do I get a port it can use? this is the port for my server... is that not what im supposed to use?

**Comment by BenCodez** [comment]
you need a port that is not in use

**Comment by Patatatta** [comment]
do i have to ask my server provider to do that or is there a way to do it myself

**Comment by BenCodez** [comment]
ask your host first, sometimes they have a port for you
