### ISSUE TITLE
/voteparty says Voteparty not enabled

### ISSUE THREAD

**Issue by riniki5** [Ben12345rocks/VotingPlugin#1375]
**Versions**
6.17.1 and 1.21.1

**Relevant information**
So i installed the plugin and typed /voteparty and it said voteparty not enabled

**Context**
Im not sure what im doing wrong i didnt find something about this nowhere, could you help?

**Comment by BenCodez** [comment]
Did you enable vote party?

**Comment by riniki5** [comment]
im not sure how tho

**Comment by BenCodez** [comment]
SpecialRewards.yml, under VoteParty set enabled to true

**Comment by riniki5** [comment]
Thanks and sorry if i wasted your time
