### ISSUE TITLE
Placeholders not working

### ISSUE THREAD

**Issue by Rashdonkey** [Ben12345rocks/VotingPlugin#1377]
**Versions**
VotingPlugin 6.17.1
Server 1.21

**Describe the bug**
Some placeholders not working such as "%plugin_name% >>You recieved x1 of ..."
I couldn't find anywhere in the configs to modify that particular message either.

**To Reproduce**
/testvote produces that message

**Expected behavior**
Either show the plugin name or remove the placeholder completely, I'd like to know where I can modify this

**Screenshots/Configs**
![Screenshot 2024-08-25 155604](https://github.com/user-attachments/assets/d3ce64a4-4374-45cb-b1e9-818340761104)

**Additional context**

I had the same issue with the %player_name% placeholder but I was able to fix it using the "/papi ecloud download player" command
Is there a specific extension that will fix the plugin_name one?

**Comment by BenCodez** [comment]
What do you need the %plugin_name% for? Can't you just set the name?

**Comment by Rashdonkey** [comment]
It was already set like this and honestly, I've literally looked everywhere in my configs to simply remove it completely but never found it even after using the quick search features.

**Comment by BenCodez** [comment]
There is no default votingplugin message with %plugin_name%

**Comment by Rashdonkey** [comment]
Alright, thanks. I'll look through other plugins I guess. I do use VoteParty as well but didnt find it in that either..
