### ISSUE TITLE
VotingPlugin spamming chat and console

### ISSUE THREAD

**Issue by FayaTV** [Ben12345rocks/VotingPlugin#1380]
Hello BenzCodes I use your Votingplugin in my server and i love it! Butt.. with every vote it keeps spamming the chat and console, is there a way to stop the spamming but keep the message?

thank you in advance! 🙏🏼

**Comment by BenCodez** [comment]
What messages are spamming?

**Comment by FayaTV** [comment]
The "&aThanks for voting"

**Comment by FayaTV** [comment]
But my console is also spamming after I use the test vote ingame my whole console freezes..

**Comment by BenCodez** [comment]
> The "&aThanks for voting"

Just remove that message?



> But my console is also spamming after I use the test vote ingame my whole console freezes..

What's all in console?

**Comment by FayaTV** [comment]
I'll put in a screenshot because the latest log is to big to put here.. just keep in mind the spamming you see quits when i stop my server..
![image](https://github.com/user-attachments/assets/56360ce4-5f8a-462f-a4ca-0a6143c0065b)

**Comment by FayaTV** [comment]
I deleted the messages but it keeps spamming my console and freezing everything any ideas?

**Comment by BenCodez** [comment]
Looks to me you set up vote forwarding to forward to itself?

**Comment by FayaTV** [comment]
How can i change that? I havent changed anything with "forwarding"

**Comment by BenCodez** [comment]
look in votifierplus config

**Comment by FayaTV** [comment]
I fixed it thank you! Now im going to try to get the rewards working.. thanks for your help!
