### ISSUE TITLE
Rewards not working for VotingPlugin

### ISSUE THREAD

**Issue by FayaTV** [Ben12345rocks/VotingPlugin#1381]
Hello BenCodez, I have setup my voterewards but nothing is working after my friends and i vote for the server we dont get the rewards.. can you maybe check my paste bin and tell me whats wrong?

**Comment by FayaTV** [comment]
[Nrnvpm6V.txt](https://github.com/user-attachments/files/16820401/Nrnvpm6V.txt)

**Comment by BenCodez** [comment]
Try Commands, not commands

**Comment by FayaTV** [comment]
Thanks! There was one more problem maybe it wil help future users:


I Had:
Command:
  - 'command'

Now i have:
Command:
-'command'
