### ISSUE TITLE
Player not getting offline rewards

### ISSUE THREAD

**Issue by Cruwzky** [Ben12345rocks/VotingPlugin#1383]
**Versions**
VotingPlugin: 6.17.1
Current Purpur Version: 1.21-2281-7950960 (MC: 1.21)

**Describe the bug**
One of our players does not receive offline rewards then he joins the server. This is both on his main account and his secondary account. All other players does receive the rewards.

We see the vote message in chat, but as said then the player joins the server it does not give the player the offline rewards.
![db-screenshot](https://github.com/user-attachments/assets/7a9b52b2-0f79-44ec-af31-fd4d11a55dc5)

Everything else on the user in the DB seems to be the same as the rest of the users.

**To Reproduce**
I don't know how to reproduce the issue.

**Expected behavior**
I expect the player to recieve the offline rewards which I can see in the database on both his accounts.

**Screenshots/Configs**
I have added a screenshot of the players "OfflineVotes" cell in the database.

Config: https://mclo.gs/7aWysB2
Vote sites config: https://mclo.gs/9xK58Jz

**Comment by BenCodez** [comment]
# Wait until user is logged in with AuthMe
    # Requires AuthMe
    WaitUntilLoggedIn: true

Try disabling that?

**Comment by Cruwzky** [comment]
We do not use AutMe, but I have tried disabling it now and restarting the server. But unfortunately the player does still not get the offline rewards.

It one player out of maybe 50-60 players and it both his main and smurf account. So it quite weird.

**Comment by BenCodez** [comment]
Using any proxy server at all? Is it consistent/very repeatable?

**Comment by Cruwzky** [comment]
We use Velocity, but the voting plugin is only running on one of the backend servers.

It is consistent yes the specific player never gets offline rewards. But if the player is online he gets the rewards

**Comment by BenCodez** [comment]
Try the latest dev build and see what happens now. If not set debug level
to EXTRA and send the logs

**Comment by Cruwzky** [comment]
After restart tonight we will be running on dev build and with debug level EXTRA, i will followup

**Comment by WarnDa** [comment]
I can confirm the issue.
It happens on some users, not everyone, I had to reset the database, fixed the issue, but hapepened again to other player after some weeks...

**Comment by Cruwzky** [comment]
We have the newest dev build and debug EXTRA on now, here is our log for today that shows the player voting and logging in: https://mclo.gs/eYUn0JJ

It's the player "3e3ee9d6-933a-4bca-a211-2f1d06dbb616" that has the problem. In the database I still can see that the column "OfflineVotes" just keep growing for this specific player. The column "OfflineRewards" is empty.

**Comment by BenCodez** [comment]
Wanna try the next build out?

**Comment by Cruwzky** [comment]
We have tested with the newest build but no luck. The user does still not get the offline rewards. Here is a new log: https://mclo.gs/Ho3FUuQ

**Comment by BenCodez** [comment]
Just wanna double check, it's just the one player that has the problem?

**Comment by Cruwzky** [comment]
Yes we only know of one player having this issue

**Comment by BenCodez** [comment]
Can you do /av user (player) viewdata - do it in console and copy/paste it here

**Comment by Cruwzky** [comment]
This got a little weird.

The player now sometimes seems to get the keys. It seems to happen if he jumps servers though our proxy and back again to the primary server. But not always.

So right now that commands does not show anything because he got his keys, however here is the result: https://mclo.gs/Fa3USTq

**Comment by BenCodez** [comment]
set DelayLoginEvent to 5000 and see what happens?

**Comment by BenCodez** [comment]
Does this happen to fix it? https://bencodez.com/job/VotingPlugin/

**Comment by BenCodez** [comment]
Latest spigot release fixes this.
