### ISSUE TITLE
Rewards not paying for Offline Users

### ISSUE THREAD

**Issue by SlyGuy89** [Ben12345rocks/VotingPlugin#1384]
**Versions**
VotingPlugin 6.17.1
Paper version 1.21.1-35-master@be1078f

**Describe the bug**
Since updating to 1.21 and latest version of VP, players no longer receive rewards for voting while offline. The votes still count, and players still get the "Voted on all sites" reward when they log in, but don't get any of the per-vote rewards. The rewards work as intended while players are logged in, and these same configurations worked perfectly prior to updating.

**To Reproduce**
Cast vote while not logged in to server

**Expected behavior**
The reward commands should run when players log in.

**Comment by BenCodez** [comment]
set debuglevel to EXTRA and send the logs on vote then login

**Comment by SlyGuy89** [comment]
Sorry it took so long to get back to you on this!

I've linked the log with debuglevel set to Extra. Votes were cast while the player "UntimelyWizard" was offline, and then the player logged in. They didn't receive any rewards from their votes, and this time they also didn't receive the "Voted on all Sites" reward either.

Thanks!

https://mclo.gs/kgGOPDK

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/ wanna see what this does?

**Comment by SlyGuy89** [comment]
Still no luck. Here's a new logs, player "Fyecam" voted offline then logged in. They DID receive "Voted on all sites" rewards though.

https://mclo.gs/Im9OSrJ

**Comment by BenCodez** [comment]
Can you send your configs? In the middle of moving it's hard to troubleshoot this

**Comment by SlyGuy89** [comment]
Attached Plugin files. I appreciate your help on this!
    On Wednesday, September 18, 2024 at 07:48:35 PM EDT, Ben ***@***.***> wrote:  
 
 


Can you send your configs? In the middle of moving it's hard to troubleshoot this

**Comment by BenCodez** [comment]
Don't see any files attached

**Comment by SlyGuy89** [comment]
How about this?


[VotingPlugin.zip](https://github.com/user-attachments/files/17052203/VotingPlugin.zip)

**Comment by SlyGuy89** [comment]
I think I've only ever messed with the main Config, SpecialRewards, and VoteSites configs.

**Comment by BenCodez** [comment]
Wanna just confirm that you restarted since using the latest dev build? /av version shows the correct build? And it always works right if player is online?

**Comment by SlyGuy89** [comment]
Restarted after installing the jar, /av version shows "Using advanced core 3.7.8 built on 2024-9-18 02:32, Advanced Core Jenkins build number: 657, VotingPlugin Jenkins build: 1365. We've had no reported errors for vote rewards when players vote while online.

**Comment by BenCodez** [comment]
Do you have a way to test with mysql? Might be able to look super into the issue until I'm done with my move

**Comment by SlyGuy89** [comment]
That would be new territory for me, I know very little about MySQL.
It's really not an urgent issue for me. I could try regenerating the configs and setting things up again, it wouldn't be too difficult.

**Comment by BenCodez** [comment]
Remind me in a few days and I might get more time to look at it

**Comment by joeyfogas** [comment]
Same issues here - figured i'd drop that reminder :)

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/ Wanna see what this does?

**Comment by joeyfogas** [comment]
same issue.

Noticed the specialrewards aren't processing while offline either - They are supposed to rank up after a certain amount of votes - they do if they are online, but gets lost in ether if they are offline. votepoints seem to still be awarded.

Before going to 1.21 this wasn't an issue.

[configs.zip](https://github.com/user-attachments/files/17179778/configs.zip)

**Comment by joeyfogas** [comment]
using build 1369

**Comment by SlyGuy89** [comment]
Sorry for delayed response. I've installed the new jar, will be able to test it tonight to see if the issue is resolved.

**Comment by BenCodez** [comment]
> same issue.
> 
> Noticed the specialrewards aren't processing while offline either - They are supposed to rank up after a certain amount of votes - they do if they are online, but gets lost in ether if they are offline. votepoints seem to still be awarded.
> 
> Before going to 1.21 this wasn't an issue.
> 
> [configs.zip](https://github.com/user-attachments/files/17179778/configs.zip)

Set DebugLevel to EXTRA and send the logs on login after an offline vote, for some reason 1.21 changed something and haven't quite figured out what it was yet and really hadn't the chance to troubleshoot just yet

**Comment by SlyGuy89** [comment]
No luck... Player UntimelyWizard voted while offline, and did not receive any rewards when they logged in, not even the "voted on all sites" rewards.

As an additional note, this was the first time the player has logged in since the Jar file was updated.

https://mclo.gs/DJjiVR0

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/ wanna send debug logs with that? Also double check your on the latest spigot version?

**Comment by BenCodez** [comment]
Latest spigot release fixes this issue
