### ISSUE TITLE
How to disable or change broadcast on vote?

### ISSUE THREAD

**Issue by KermitCloud** [Ben12345rocks/VotingPlugin#1385]
**Versions**
Plugin version and spigot version

**Relevant information**
Configs that relate to the issue in a pastebin.

**Context**
Context about the question/concern

How do I disabled the broadcast on vote

**Comment by BenCodez** [comment]
Config.yml under Format

**Comment by KermitCloud** [comment]
I did i disabled them ands its still sending

**Comment by BenCodez** [comment]
set it to ''
