### ISSUE TITLE
Add %reward% and %reward_amount% as valid global BroadcastMsg placeholders

### ISSUE THREAD

**Issue by redbau** [Ben12345rocks/VotingPlugin#1387]
**Is your feature request related to a problem? Please describe.**
I have about 100 custom messages for every reward I've setup that all have the same format, this is so tedious!

**Describe the solution you'd like**
Add `%reward%` and `%reward_amount%` as valid placeholders for use in `BroadcastMsg` in the main config

**Describe alternatives you've considered**
One by one adding messages for each reward, and manually changing the qty and name, even tho it's right there! ARG.

**Additional context**
Nope. Pleeeease!

**Comment by BenCodez** [comment]
Can you send what rewards you have exactly?
