### ISSUE TITLE
Can I create Top Vote leaderboard with this plugin in my website ?

### ISSUE THREAD

**Issue by abusuhan26** [Ben12345rocks/VotingPlugin#1389]
**Versions**
Latest

**Context**
I am creating a website .
I need when someone vote for server 
That will also show in my website which i am designing 
Can i do this with this plugin ?
If so then can just give me a context about this 
Thank you

**Comment by BenCodez** [comment]
You'll have to pull the vote totals and sort them.

There is an example here: https://github.com/BenCodez/VotingPlugin/wiki/Web-Support

**Comment by BenCodez** [comment]
Did you manage to get this to work? I have future plans to add web api support
