### ISSUE TITLE
TimeZone: " " Doesn't work

### ISSUE THREAD

**Issue by the-w41k3r** [Ben12345rocks/VotingPlugin#1400]
**Versions**
VP: v6.17.4
Spigot: 1.21

**Describe the bug**
TimeZone: "UTC-4:00" or TimeZone: "America/New_York" does not work at all in any server. If I put a wrong time zone, it shows error that timezone is not recognized, but on putting the right rimzeone, it just doesnt work.

**To Reproduce**
1. Go to `config.yml` or `bungeeconfig.yml` and set TimeZone: "UTC-4:00" or TimeZone: "America/New_York"
2. Restart/reload. The plugin still uses system timezone.

**Expected behavior**
The plugin is supposed to use the timzeone provided rather than the system timezone which creates problems with players not being able to vote at the right time.

**Screenshots/Configs**
![image](https://github.com/user-attachments/assets/32e8127c-d2ac-4dac-8b79-a7de1f908b75)
![image](https://github.com/user-attachments/assets/80cac143-163a-478b-91f8-65f7b817b52b)

**Comment by BenCodez** [comment]
https://garygregory.wordpress.com/2013/06/18/what-are-the-java-timezone-ids/

Should work with something on that list. Any errors in console?

**Comment by the-w41k3r** [comment]
As i mentioned, i have tried TimeZone: "America/New_York" that doesnt work either, there is no error on the console.

**Comment by BenCodez** [comment]
Send your config

**Comment by the-w41k3r** [comment]
I was going through the published code on the repo and found there is only 2 instance of "TimeZone" that is being checked, could that be causing an issue?
![image](https://github.com/user-attachments/assets/9679a655-85aa-4aa0-a6f1-a25a2d3a94b9)
Additonally attached my configs from bungee as well as spigots

Config.yml: https://pastebin.com/9YKS9Bgr
BungeeSettings.yml: https://pastebin.com/cDSdK32Q
bungeeconfig.yml: https://pastebin.com/NH43y27c

**Comment by BenCodez** [comment]
> I was going through the published code on the repo and found there is only 2 instance of "TimeZone" that is being checked, could that be causing an issue? ![image](https://private-user-images.githubusercontent.com/64218536/392566868-9679a655-85aa-4aa0-a6f1-a25a2d3a94b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDcwNDAsIm5iZiI6MTczMzM0Njc0MCwicGF0aCI6Ii82NDIxODUzNi8zOTI1NjY4NjgtOTY3OWE2NTUtODVhYS00YWEwLWE2ZjEtYTI1YTJkM2E5NGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIxMTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZGE0YWM3MWNlMzMxNmYwNmZlZDdlZDY3ODViOWY1NzQzMDAwNzQ5MjM5Njk1OTJjMWViNzY1MjdiNjk4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tEO5uxU92okBhtvo5yGOZC3_t6-JMNmwzRgCTXKrObE) Additonally attached my configs from bungee as well as spigots
> 
> Config.yml: https://pastebin.com/9YKS9Bgr BungeeSettings.yml: https://pastebin.com/cDSdK32Q bungeeconfig.yml: https://pastebin.com/NH43y27c

Those 2 are for different version, one for velocity, one for bungee.

What does /av CurrentPluginTime show?

**Comment by the-w41k3r** [comment]
Shows my local time, when it should be New York time.
![image](https://github.com/user-attachments/assets/5d549c76-c76b-4a4e-9fa8-faa6323468fc)
![image](https://github.com/user-attachments/assets/282f5633-1e79-4e20-9300-1be21ded7db8)

**Comment by BenCodez** [comment]
What time zone is your server in? If you don't set a time zone what does it show?

**Comment by the-w41k3r** [comment]
My server's timezone is GMT+5:30 (Asia/Kolkata)

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/ What's this do?

**Comment by the-w41k3r** [comment]
I should only try on spigot servers or bungee as well?

**Comment by BenCodez** [comment]
Spigot for now

**Comment by the-w41k3r** [comment]
![image](https://github.com/user-attachments/assets/8207000a-c7cf-4afa-981a-2996cbc413ad)
ah yes that works!

**Comment by the-w41k3r** [comment]
another suggestion: there should be minutes option as well for `TimeHourOffSet: 0` 
but with this fix of timezone, the offset doesnt really matter that much

Thanks  a lot for the express support!!

**Comment by BenCodez** [comment]
should also work on proxy, made the same changes

**Comment by the-w41k3r** [comment]
Thanks! you can close this now ^^

**Comment by the-w41k3r** [comment]
Oh wait, do i use the same plugin jar for bungee now or do i wait for a release?

**Comment by BenCodez** [comment]
All the same jar

**Comment by the-w41k3r** [comment]
alright thanks again!
