### ISSUE TITLE
Every multiple not working with votestreak

### ISSUE THREAD

**Issue by kaimokene** [Ben12345rocks/VotingPlugin#1403]
**Versions**
VotingPlugin 6.17.4 MC Ver: 1.21.4 

**Describe the bug**
The config suggests using - to give a reward for every multiple, but when trying it out i can't get the reward listed in config using forcevotestreak. Whilst after removing the - from '3-' seems to make the forcevotestreak command work, but no every multiple functionality.

**To Reproduce**
1. Go to VoteStreak in file SpecialRewards.yml
2. Change the Day number as an example to '3-'
3. Enable it and test it ingame using '/av user <playername> ForceVoteStreak Day 3'
4. Nothing happens.
5. Change the Day number to '3'
6. Test it again using the same command and watch it work.

**Expected behavior**
I Expect the every multiple functionality that's suggested by the config to work properly and give the reward using forcevotestreak command as a test.

**Screenshots/Configs**
 Doesn't work: https://prnt.sc/mdGCrpr_qspd
 Works: https://prnt.sc/9kIG4NbOEDtg

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/

What does that build do? If it still doesn't work set debuglevel to EXTRA and send the log on a vote that should trigger vote streak

**Comment by kaimokene** [comment]
```
[19:28:07] [Server thread/INFO]: kaimokene issued server command: /av user kaimokene ForceVoteStreak Day 3
[19:28:07] [Craft Scheduler Thread - 6 - VotingPlugin/INFO]: [VotingPlugin] Debug: Not giving reward  from path VoteStreak.Day.3.Rewards, Options: Online: true, OnlineSet: true, GiveOffline: true, ForceOffline: false, CheckTimed: true, IgnoreChance: false, IgnoreRequirements: false, Placeholders: Type%pair%Day%entry%Streak%pair%3%entry%Date%pair%Sun, 8 Dec 2024 19:28, Prefix: , Suffix: 
```

**Comment by BenCodez** [comment]
I meant triggering via a vote, not by command since the command can't handle it with a -. Next build should fix that though. 

Can you test with a vote?

**Comment by kaimokene** [comment]
https://pastebin.com/vEVHZtDx

**Comment by BenCodez** [comment]
Can I see your specialrewads.yml? Did that player already get a votestreak?

**Comment by kaimokene** [comment]
https://pastebin.com/EsaGdk5C  I did get it once when i didn't use the - for every multiple. I am setting the streak via command though (/av user kaimokene SetVoteStreak DAY 3), so it might just be my user error for using that cmd.

**Comment by BenCodez** [comment]
There is a failsafe that prevents getting more than one vote streak a day, might be what's happening here. Can you try tomorrow and see if it works when voting?

**Comment by kaimokene** [comment]
Works for me, i was gonna head to bed anyways.

**Comment by kaimokene** [comment]
Seems to still not work, got this when first time testvoting though, still no reward (votestreak section still being this https://pastebin.com/XHs7wyk2): `[07:55:29] [pool-60-thread-1/INFO]: [VotingPlugin] ExtraDebug: PlayerData SQLITE: Setting DayVoteStreak to '6' for 'kaimokene/45d7a3cc-d840-3691-a16e-2b1cae0806de' Queue: true
[07:55:29] [pool-60-thread-1/INFO]: [VotingPlugin] Debug: Streak: 3 multiple: false
[07:55:29] [pool-60-thread-1/INFO]: [VotingPlugin] Debug: Streak: 7- multiple: true`

**Comment by BenCodez** [comment]
According to the log it's not reading the - on 3-. Have you restarted since readding that?

**Comment by kaimokene** [comment]
Yeah it seemed to work with fakevote now, probably assumed in the morning that i had everything properly configured and config seemed fine, so i didn't reload/restart. Will close the issue, since it seems to work properly now.
