### ISSUE TITLE
Cant launch on 1.16.5

### ISSUE THREAD

**Issue by Merhba12** [Ben12345rocks/VotingPlugin#1406]
**Versions**
Voting Plugin-6.18 / Latest paperMC

**Relevant information**
[13:40:02 ERROR]: Could not load 'plugins\VotingPlugin-6.18.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/bencodez/votingplugin/VotingPluginMain has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0

**Context**
I cannot go to java 17 or higher, as i tried it and i cannot open my 1.16.5 server.

**Comment by BenCodez** [comment]
Well, you need to update java. Should work fine to update that

**Comment by Merhba12** [comment]
i tried java 17, 18, and 21. It says the same thing. I need to use java 16 for 1.16.5 or it doesnt allow me to open the server. Is there a workaround for it?

**Comment by BenCodez** [comment]
What's in console when you start with java 17?

**Comment by Merhba12** [comment]
C:\Users\Administrator\Desktop\boxpvp aethernv>∩╗┐@echo off
'∩╗┐@echo' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Administrator\Desktop\boxpvp aethernv>title AetherNW BoxPVP

C:\Users\Administrator\Desktop\boxpvp aethernv>color 0c
------------------------------------
AetherNW BoxPVP
peketi a├º─▒l─▒yor
------------------------------------
Sunucu baslatiliyor...

C:\Users\Administrator\Desktop\boxpvp aethernv>"C:\Program Files\Java\jdk-17\bin/java" -Xms1G -Xmx10G -Duser.language=en -Duser.region=EN -Dfile.encoding=UTF-8 -jar server.jar -o true --nogui
Unsupported Java detected (61.0). Only up to Java 16 is supported.

C:\Users\Administrator\Desktop\boxpvp aethernv>PAUSE
Press any key to continue . . .

**Comment by BenCodez** [comment]
A quick google search: https://www.spigotmc.org/threads/running-java-17-on-a-1-16-5-server.574385/

**Comment by Merhba12** [comment]
"-DPaper.IgnoreJavaVersion=true and then it will work" so i gotta do this one then?

**Comment by BenCodez** [comment]
Probably

**Comment by Merhba12** [comment]
C:\Users\Administrator\Desktop\boxpvp aethernv>∩╗┐@echo off
'∩╗┐@echo' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Administrator\Desktop\boxpvp aethernv>title AetherNW BoxPVP

C:\Users\Administrator\Desktop\boxpvp aethernv>color 0c
------------------------------------
AetherNW BoxPVP
peketi a├º─▒l─▒yor
------------------------------------
Sunucu baslatiliyor...

C:\Users\Administrator\Desktop\boxpvp aethernv>"C:\Program Files\Java\jdk-21\bin/java" -Xms1G -Xmx10G -Duser.language=en -Duser.region=EN -Dfile.encoding=UTF-8 -jar server.jar -o true -DPaper.IgnoreJavaVersion=true --nogui
Dec 19, 2024 11:14:05 PM org.bukkit.craftbukkit.Main main
SEVERE: D is not a recognized option
Option                                  Description
------                                  -----------
-?, --help                              Show the help
-C, --commands-settings <File: Yml      File for command settings (default:
  file>                                   commands.yml)
-P, --plugins <File: Plugin directory>  Plugin directory to use (default:
                                          plugins)
-S, --spigot-settings <File: Yml file>  File for spigot settings (default:
                                          spigot.yml)
-W, --universe, --world-container, --   World container (default: .)
  world-dir <File: Directory
  containing worlds>
--add-extra-plugin-jar, --add-plugin
  <File: Specify paths to extra plugin
  jars to be loaded in addition to
  those in the plugins folder. This
  argument can be specified multiple
  times, once for each extra plugin
  jar path.>
-b, --bukkit-settings <File: Yml file>  File for bukkit settings (default:
                                          bukkit.yml)
-c, --config <File: Properties file>    Properties file to use (default:
                                          server.properties)
-d, --date-format <SimpleDateFormat:    Format of the date to display in the
  Log date format>                        console (for log entries)
--demo                                  Demo mode
--eraseCache                            Whether to force cache erase during
                                          world upgrade
--forceUpgrade                          Whether to force a world upgrade
-h, --host, --server-ip <String:        Host to listen on
  Hostname or IP>
--log-append <Boolean: Log append>      Whether to append to the log file
                                          (default: true)
--log-count <Integer: Log count>        Specified how many log files to cycle
                                          through (default: 1)
--log-limit <Integer: Max log size>     Limits the maximum size of the log
                                          file (0 = unlimited) (default: 0)
--log-pattern <String: Log filename>    Specfies the log filename pattern
                                          (default: server.log)
--log-strip-color                       Strips color codes from log file
--noconsole                             Disables the console
--nogui                                 Disables the graphical console
--nojline                               Disables jline and emulates the
                                          vanilla console
-o, --online-mode <Boolean:             Whether to use online authentication
  Authentication>
-p, --port, --server-port <Integer:     Port to listen on
  Port>
--paper, --paper-settings <File: Yml    File for paper settings (default:
  file>                                   paper.yml)
-s, --max-players, --size <Integer:     Maximum amount of players
  Server size>
--server-name <String: Name>            Name of the server (default: Unknown
                                          Server)
-v, --version                           Show the CraftBukkit Version
-w, --level-name, --world <String:      World name
  World name>

C:\Users\Administrator\Desktop\boxpvp aethernv>PAUSE
Press any key to continue . . .

i got this error

**Comment by BenCodez** [comment]
Your going to be on your own on how to fix this. Not much I can do

**Comment by Merhba12** [comment]
welp thx for your efforts
